In [2]:
import numpy as np 
import pandas as pd

In [3]:
df=pd.read_csv('gurgaon_properties.csv')

In [4]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [5]:
df.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,4 BHK Flat in Sector 37D Gurgaon,flat,bptp terra,1.67,7622.0,2191.0,Super Built up area 2191(203.55 sq.m.)Built Up...,4,4,3,not available,"1104, Sector 37D Gurgaon, Gurgaon, Haryana",11.0,West,1 to 5 Year Old,"['Airia Mall', 'Dwarka Expressway', 'Golf Cour...",Bptp terra is one of the most popular destinat...,"['7 Fan', '18 Light', '5 AC', '1 Chimney', '1 ...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area4.5 out of 5', 'Construction4.5 ou..."
1,5 Bedroom House for sale in New Colony,house,rattan garden,1.30,13499.0,963.0,Built Up area: 963 (89.47 sq.m.),5,3,2,not available,"New Colony, Sector 7, New Colony, Gurgaon, Har...",3.0,NaN,10+ Year Old,"['Chintapurni Mandir', 'Aryan Hospital', 'D.R....",Best in class property available at new colony...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
2,5 Bedroom House for sale in Sector 14 Gurgaon,house,independent,4.15,18444.0,2250.0,Plot area 250(209.03 sq.m.),5,4,2,not available,"Sector 14 Gurgaon, Gurgaon, Haryana",2.0,North-West,10+ Year Old,"['Sheetla Mata Mandir', 'Hsbc bank ATM', 'Hdfc...",250 sqyds independent house for sale in sector...,"['5 Wardrobe', '8 Fan', '1 Exhaust Fan', '4 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
3,3 BHK Flat in Sector 92 Gurgaon,flat,apartment,0.75,4687.0,1600.2,Carpet area: 1600 (148.64 sq.m.),3,4,3,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",2.0,East,5 to 10 Year Old,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...","Within 2-3 kms schools, malls, hospital are av...","['5 Fan', '7 Light', 'No AC', 'No Bed', 'No Ch...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment5 out of 5', 'Safety3 out of 5', ..."
4,5 Bedroom House for sale in Laxman Vihar,house,independent,50.00,10482.0,47701.0,Built Up area: 53 (44.31 sq.m.),5,3,0,not available,"Laxman Vihar, Sector 3a, Laxman Vihar, Gurgaon...",1.0,NaN,undefined,NaN,5bhk residential house for resale in laxman vi...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."

In [6]:
df.shape

(3942, 20)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3942 entries, 0 to 3941
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3942 non-null   object
 1   property_type    3942 non-null   object
 2   society          3941 non-null   object
 3   price            3941 non-null   float64
 4   price_per_sqft   3941 non-null   float64
 5   area             3941 non-null   float64
 6   areaWithType     3942 non-null   object
 7   bedRoom          3942 non-null   int64
 8   bathroom         3942 non-null   int64
 9   balcony          3942 non-null   object
 10  additionalRoom   3942 non-null   object
 11  address          3931 non-null   object
 12  floorNum         3940 non-null   float64
 13  facing           2771 non-null   object
 14  agePossession    3941 non-null   object
 15  nearbyLocations  3736 non-null   object
 16  description      3942 non-null   object
 17  furnishDetails   2915 non-null   object
 18  features         3237 non-null   object
 19  rating           3493 non-null   object
dtypes: float64(4), int64(2), object(14)
memory usage: 616.1+ KB

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df.isnull().sum()

property_name         0
property_type         0
society               1
price                 1
price_per_sqft        1
area                  1
areaWithType          0
bedRoom               0
bathroom              0
balcony               0
additionalRoom        0
address              11
floorNum              2
facing             1171
agePossession         1
nearbyLocations     206
description           0
furnishDetails     1027
features            705
rating              449
dtype: int64

In [10]:
df.insert(loc=3,column='sector',value=df['property_name'].str.split('in').str.get(1).str.replace('Gurgaon','').str.strip())

In [11]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,4 BHK Flat in Sector 37D Gurgaon,flat,bptp terra,Sector 37D,1.67,7622.0,2191.0,Super Built up area 2191(203.55 sq.m.)Built Up...,4,4,3,not available,"1104, Sector 37D Gurgaon, Gurgaon, Haryana",11.0,West,1 to 5 Year Old,"['Airia Mall', 'Dwarka Expressway', 'Golf Cour...",Bptp terra is one of the most popular destinat...,"['7 Fan', '18 Light', '5 AC', '1 Chimney', '1 ...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area4.5 out of 5', 'Construction4.5 ou..."
1,5 Bedroom House for sale in New Colony,house,rattan garden,New Colony,1.30,13499.0,963.0,Built Up area: 963 (89.47 sq.m.),5,3,2,not available,"New Colony, Sector 7, New Colony, Gurgaon, Har...",3.0,NaN,10+ Year Old,"['Chintapurni Mandir', 'Aryan Hospital', 'D.R....",Best in class property available at new colony...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
2,5 Bedroom House for sale in Sector 14 Gurgaon,house,independent,Sector 14,4.15,18444.0,2250.0,Plot area 250(209.03 sq.m.),5,4,2,not available,"Sector 14 Gurgaon, Gurgaon, Haryana",2.0,North-West,10+ Year Old,"['Sheetla Mata Mandir', 'Hsbc bank ATM', 'Hdfc...",250 sqyds independent house for sale in sector...,"['5 Wardrobe', '8 Fan', '1 Exhaust Fan', '4 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
3,3 BHK Flat in Sector 92 Gurgaon,flat,apartment,Sector 92,0.75,4687.0,1600.2,Carpet area: 1600 (148.64 sq.m.),3,4,3,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",2.0,East,5 to 10 Year Old,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...","Within 2-3 kms schools, malls, hospital are av...","['5 Fan', '7 Light', 'No AC', 'No Bed', 'No Ch...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment5 out of 5', 'Safety3 out of 5', ..."
4,5 Bedroom House for sale in Laxman Vihar,house,independent,Laxman Vihar,50.00,10482.0,47701.0,Built Up area: 53 (44.31 sq.m.),5,3,0,not available,"Laxman Vihar, Sector 3a, Laxman Vihar, Gurgaon...",1.0,NaN,undefined,NaN,5bhk residential house for resale in laxman vi...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."

In [12]:
df['sector'].value_counts()

sector
Sohna                                                        163
Sector 102                                                   113
Sector 85                                                    110
Sector 92                                                    104
Sector 69                                                     94
Sector 65                                                     90
Sector 90                                                     90
Sector 81                                                     90
Sector 109                                                    88
Sector 79                                                     80
Sector 83                                                     69
Sector 37D                                                    68
Sector 86                                                     67
Sector 104                                                    66
Sector 107                                                    60
Sector 108                                                    58
Sector 56                                                     57
Sector 95                                                     57
Sector 48                                                     56
Sector 89                                                     56
Sector 70A                                                    54
Sector 37C                                                    53
Sector 70                                                     53
Nirvana Country                                               52
Sector-33 Sohna                                               51
Sector 84                                                     51
Palam Vihar                                                   50
Sector 67                                                     48
Sector 103                                                    45
DLF Phase 1                                                   43
Sector 113                                                    43
Sector 61                                                     42
Sector 82                                                     42
Sector 66                                                     42
DLF Phase 2                                                   41
Sector 106                                                    38
Sector 49                                                     36
Sector 99A                                                    32
Sushant Lok Phase 1                                           31
Sector 68                                                     30
Sector 77                                                     29
Sector 72                                                     29
Sector 54                                                     27
Sector 71                                                     27
Laxman Vihar                                                  26
DLF Phase 4                                                   25
Sector 112                                                    24
Sector 88A                                                    23
Sector 111                                                    22
Sector 67A                                                    22
DLF Phase 3                                                   21
Sector 33                                                     20
Sector 22                                                     20
Sector 82A                                                    20
Sector 78                                                     19
Sector 74                                                     18
Sector 63A                                                    18
Sector 62                                                     17
Sector 91                                                     17
Sector 110                                                    16
Sushant Lok Phase 3                                           16
Sector 99                                                     16
Sector 63                                                     15
Sector 60                                                     15
Sector 14                                                     15
Sector 53                                                     14
Sector 1 Imt Manesar                                          14
Gwal Pahari                                                   14
Sector 76                                                     14
Rajendra Park                                                 14
DLF Phase 5                                                   14
Sector 52                                                     14
Sector 3                                                      14
Sector 46                                                     13
Sector 36A                                                    13
Laxman Vihar Phase 2                                          13
Uppals Southend                                               12
Sohna Road                                                    12
Sector 93                                                     12
Sector 50                                                     12
Sector 38                                                     12
Sector 31                                                     12
Sector 39                                                     12
Sector 47                                                     11
Ashok Vihar Phase 3 Extension                                 11
Sector 9A                                                     11
Sector 1A IMT Manesar                                         10
Sector 7                                                      10
Sector 55                                                      9
Sector 4                                                       9
South City 1                                                   9
Ashok Vihar Phase 2                                            9
Sector 95A                                                     9
Dwarka Expressway                                              8
C Block Sushant Lok Phase 1                                    8
Sector 43                                                      8
Sector 10A                                                     8
Sector 57                                                      8
Sector 59                                                      8
Sector 89 A                                                    8
Sector 40                                                      8
Malibu Town                                                    8
Palam Vihar Extension                                          8
Mehrauli  Road                                                 8
Sector 51                                                      7
Sector 26                                                      7
New Colony                                                     7
sector 58                                                      7
Sector 36 Sohna                                                7
Mianwali Colony                                                7
Surat Nagar 1                                                  7
Sector 1                                                       6
Jacobpura                                                      6
Rajiv Nagar                                                    6
Sector 11                                                      6
Jyoti Park                                                     6
Ashok Vihar                                                    6
Sector 5                                                       6
Sector 23A                                                     5
Sushant Lok Phase 2                                            5
Sector 105                                                     5
Subhash Nagar                                                  5
Greenwood City                                                 5
Sector 30                                                      5
Sector 80                                                      5
Sector 9                                                       5
New Palam Vihar                                                5
Arjun Nagar                                                    5
Dayanand Colony                                                5
Sector 28                                                      5
Saraswati Vihar                                                5
Manesar                                                        5
Sector 2                                                       5
Chakkarpur                                                     5
Ansal Plaza                                                    5
IMT Manesar                                                    4
Sector 17                                                      4
Suncity                                                        4
Surya Vihar                                                    4
Bhim Nagar                                                     4
Dharam Colony                                                  4
Garhi Harsaru                                                  4
Vishnu Garden                                                  4
Sector 12                                                      4
Shivpuri                                                       4
Baldev Nagar                                                   4
Adarsh Nagar                                                   4
Bhondsi                                                        4
Madanpuri                                                      4
Sector 3A                                                      4
Sector 6                                                       4
Krishna Colony                                                 4
Valley View Estate                                             4
Ravi Nagar                                                     4
Sector 36                                                      4
Shivaji Nagar                                                  4
Devilal Colony                                                 4
New                                                            4
Sector 12A                                                     4
A Block Sushant Lok Phase 1                                    3
Laxmi Garden                                                   3
Sector 73                                                      3
Sector 8                                                       3
Sector 23                                                      3
Sector 110 A                                                   3
Sector 15                                                      3
Sector 45                                                      3
Patel Nagar                                                    3
Sector 27                                                      3
Sector 17A                                                     3
MG Road                                                        3
B Block Sushant Lok Phase 1                                    3
Sector 88B                                                     3
Prem Nagar                                                     3
Gandhi Nagar                                                   3
Sector 17B                                                     3
Maruti Kunj                                                    3
Acharya Puri                                                   2
Golf Course Road                                               2
Ambience Island                                                2
Daulatabad                                                     2
Manohar Nagar                                                  2
Surat Nagar Phase 2                                            2
Samaspur                                                       2
Sector 15 Part 1                                               2
Farukhnagar                                                    2
West Rajiv Nagar                                               2
New Basti                                                      2
Mayfield Garden                                                2
Sector 15 Part 2                                               2
Sispal Vihar                                                   2
Rajiv Chowk                                                    2
Surat Nagar                                                    2
Sector 32                                                      2
Sector 41                                                      2
Hira Nagar                                                     2
Faridabad Road                                                 2
Mohan Nagar                                                    2
Shankar Vihar                                                  2
New Palam Vihar Phase 2                                        2
Sector-11 sohna                                                2
New Palam Vihar Phase 1                                        2
Sheetla Colony                                                 2
Sushant Lok                                                    2
Nars                                                           2
Rosewood                                                       2
Block A Surya Vihar                                            2
Pratap Nagar                                                   2
Shakti Nagar                                                   2
Sector-2 Sohna                                                 2
Bissar                                                         2
Golf Course Ext Road                                           2
IFFCO Chowk                                                    2
Sector 24                                                      2
Sector 21                                                      2
Shanti Nagar                                                   2
Sohna  Road                                                    2
Bhawani Enclave                                                2
, Delhi NCR                                                    2
Lajpat Nagar                                                   2
Mahalaxmi Garden, Rajendra Place                               1
laxmna vihar, phase 2                                          1
Cyber City                                                     1
Dhankot                                                        1
Ashok Vihar Phase I                                            1
Rajiv Colony                                                   1
devi lal colony gali no 12 gurgaon nr omkar public school      1
Om Nagar                                                       1
Sultanpur                                                      1
Sector 37B                                                     1
Laxman Vihar, Railway Road,                                    1
Hsiidc Plot Sector 1 Imt Manesar                               1
Khandsa                                                        1
Godrej Aria , sector 79 ,                                      1
saroop garden rajendra park                                    1
ravi nager basai road                                          1
Carterpuri Village                                             1
Near Khandsa Road                                              1
Near Pataudi Chowk                                             1
Alipur                                                         1
Mahavir pura                                                   1
near sector 1 market                                           1
Sector 42                                                      1
G block DLF City Phase 1                                       1
Begampur Khatola                                               1
Sector 4 Urban Estate                                          1
Sector-5 Sohna                                                 1
V Block DLF Phase 3                                            1
New Colony, Sector 7                                           1
near nand hospital                                             1
Tekchand Nagar                                                 1
Garauli Kalan                                                  1
Hno 13 Sagar enclave Sura                                      1
ats marigold                                                   1
Vir Nagar                                                      1
Gopal Nagar, Garhi Ghasita, Sonipat                            1
Sector-7 Hous                                                  1
Sector 17C                                                     1
Block G Sector-57                                              1
Heritage City                                                  1
Saraswati Enclave                                              1
Sector 21A Faridabad                                           1
Sector 37A                                                     1
sector-5 sheetla colony                                        1
BPTP                                                           1
Sector 9B                                                      1
Lucknow                                                        1
Part 3 Sector 5                                                1
old delhi road, opp sector-14                                  1
Pataudi Road                                                   1
B1 Block Sector 57                                             1
Shivji Park Colony                                             1
Bhora Kalan                                                    1
URBAN ESTATE, SECTOR 5                                         1
Sector 5 chowk                                                 1
Civil L                                                        1
Damdma                                                         1
Block H Ashok Vihar Phase III Extension                        1
Sector 13                                                      1
Sec 3 Bhim Vihar Part 1 Bhimgher Kheri                         1
Bhimgarh Kheri Phase 3                                         1
New Jyoti Park                                                 1
Park View                                                      1
Ansal's Palam Vihar                                            1
Anand Garden, Sector-105                                       1
HUDA Saraswati Vihar                                           1
Near euro                                                      1
Ram Nagar                                                      1
South City                                                     1
Rattan Garden                                                  1
Jat Colony,Fazilpur/Taj Nagar Road                             1
Jacobpura Near Sadar Bazar                                     1
Sector-35 Sohna                                                1
Sai Kunj                                                       1
Kheri                                                          1
Sadar Bazar                                                    1
Kanahi                                                         1
Nirvana country Pocket H                                       1
Ashok Vihar Phase 3                                            1
Name: count, dtype: int64

In [13]:
df['sector']=df['sector'].str.lower()

In [14]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,4 BHK Flat in Sector 37D Gurgaon,flat,bptp terra,sector 37d,1.67,7622.0,2191.0,Super Built up area 2191(203.55 sq.m.)Built Up...,4,4,3,not available,"1104, Sector 37D Gurgaon, Gurgaon, Haryana",11.0,West,1 to 5 Year Old,"['Airia Mall', 'Dwarka Expressway', 'Golf Cour...",Bptp terra is one of the most popular destinat...,"['7 Fan', '18 Light', '5 AC', '1 Chimney', '1 ...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area4.5 out of 5', 'Construction4.5 ou..."
1,5 Bedroom House for sale in New Colony,house,rattan garden,new colony,1.30,13499.0,963.0,Built Up area: 963 (89.47 sq.m.),5,3,2,not available,"New Colony, Sector 7, New Colony, Gurgaon, Har...",3.0,NaN,10+ Year Old,"['Chintapurni Mandir', 'Aryan Hospital', 'D.R....",Best in class property available at new colony...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
2,5 Bedroom House for sale in Sector 14 Gurgaon,house,independent,sector 14,4.15,18444.0,2250.0,Plot area 250(209.03 sq.m.),5,4,2,not available,"Sector 14 Gurgaon, Gurgaon, Haryana",2.0,North-West,10+ Year Old,"['Sheetla Mata Mandir', 'Hsbc bank ATM', 'Hdfc...",250 sqyds independent house for sale in sector...,"['5 Wardrobe', '8 Fan', '1 Exhaust Fan', '4 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
3,3 BHK Flat in Sector 92 Gurgaon,flat,apartment,sector 92,0.75,4687.0,1600.2,Carpet area: 1600 (148.64 sq.m.),3,4,3,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",2.0,East,5 to 10 Year Old,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...","Within 2-3 kms schools, malls, hospital are av...","['5 Fan', '7 Light', 'No AC', 'No Bed', 'No Ch...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment5 out of 5', 'Safety3 out of 5', ..."
4,5 Bedroom House for sale in Laxman Vihar,house,independent,laxman vihar,50.00,10482.0,47701.0,Built Up area: 53 (44.31 sq.m.),5,3,0,not available,"Laxman Vihar, Sector 3a, Laxman Vihar, Gurgaon...",1.0,NaN,undefined,NaN,5bhk residential house for resale in laxman vi...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."

In [15]:
df['sector'].value_counts()

sector
sohna                                                        163
sector 102                                                   113
sector 85                                                    110
sector 92                                                    104
sector 69                                                     94
sector 65                                                     90
sector 90                                                     90
sector 81                                                     90
sector 109                                                    88
sector 79                                                     80
sector 83                                                     69
sector 37d                                                    68
sector 86                                                     67
sector 104                                                    66
sector 107                                                    60
sector 108                                                    58
sector 56                                                     57
sector 95                                                     57
sector 48                                                     56
sector 89                                                     56
sector 70a                                                    54
sector 37c                                                    53
sector 70                                                     53
nirvana country                                               52
sector-33 sohna                                               51
sector 84                                                     51
palam vihar                                                   50
sector 67                                                     48
sector 103                                                    45
dlf phase 1                                                   43
sector 113                                                    43
sector 61                                                     42
sector 82                                                     42
sector 66                                                     42
dlf phase 2                                                   41
sector 106                                                    38
sector 49                                                     36
sector 99a                                                    32
sushant lok phase 1                                           31
sector 68                                                     30
sector 77                                                     29
sector 72                                                     29
sector 54                                                     27
sector 71                                                     27
laxman vihar                                                  26
dlf phase 4                                                   25
sector 112                                                    24
sector 88a                                                    23
sector 111                                                    22
sector 67a                                                    22
dlf phase 3                                                   21
sector 33                                                     20
sector 22                                                     20
sector 82a                                                    20
sector 78                                                     19
sector 74                                                     18
sector 63a                                                    18
sector 62                                                     17
sector 91                                                     17
sector 110                                                    16
sushant lok phase 3                                           16
sector 99                                                     16
sector 63                                                     15
sector 60                                                     15
sector 14                                                     15
sector 53                                                     14
sector 1 imt manesar                                          14
gwal pahari                                                   14
sector 76                                                     14
rajendra park                                                 14
dlf phase 5                                                   14
sector 52                                                     14
sector 3                                                      14
sector 46                                                     13
sector 36a                                                    13
laxman vihar phase 2                                          13
uppals southend                                               12
sohna road                                                    12
sector 93                                                     12
sector 50                                                     12
sector 38                                                     12
sector 31                                                     12
sector 39                                                     12
sector 47                                                     11
ashok vihar phase 3 extension                                 11
sector 9a                                                     11
sector 1a imt manesar                                         10
sector 7                                                      10
sector 55                                                      9
sector 4                                                       9
south city 1                                                   9
ashok vihar phase 2                                            9
sector 95a                                                     9
dwarka expressway                                              8
c block sushant lok phase 1                                    8
sector 43                                                      8
sector 10a                                                     8
sector 57                                                      8
sector 59                                                      8
sector 89 a                                                    8
sector 40                                                      8
malibu town                                                    8
palam vihar extension                                          8
mehrauli  road                                                 8
sector 51                                                      7
sector 26                                                      7
new colony                                                     7
sector 58                                                      7
sector 36 sohna                                                7
mianwali colony                                                7
surat nagar 1                                                  7
sector 1                                                       6
jacobpura                                                      6
rajiv nagar                                                    6
sector 11                                                      6
jyoti park                                                     6
ashok vihar                                                    6
sector 5                                                       6
sector 23a                                                     5
sushant lok phase 2                                            5
sector 105                                                     5
subhash nagar                                                  5
greenwood city                                                 5
sector 30                                                      5
sector 80                                                      5
sector 9                                                       5
new palam vihar                                                5
arjun nagar                                                    5
dayanand colony                                                5
sector 28                                                      5
saraswati vihar                                                5
manesar                                                        5
sector 2                                                       5
chakkarpur                                                     5
ansal plaza                                                    5
imt manesar                                                    4
sector 17                                                      4
suncity                                                        4
surya vihar                                                    4
bhim nagar                                                     4
dharam colony                                                  4
garhi harsaru                                                  4
vishnu garden                                                  4
sector 12                                                      4
shivpuri                                                       4
baldev nagar                                                   4
adarsh nagar                                                   4
bhondsi                                                        4
madanpuri                                                      4
sector 3a                                                      4
sector 6                                                       4
krishna colony                                                 4
valley view estate                                             4
ravi nagar                                                     4
sector 36                                                      4
shivaji nagar                                                  4
devilal colony                                                 4
new                                                            4
sector 12a                                                     4
a block sushant lok phase 1                                    3
laxmi garden                                                   3
sector 73                                                      3
sector 8                                                       3
sector 23                                                      3
sector 110 a                                                   3
sector 15                                                      3
sector 45                                                      3
patel nagar                                                    3
sector 27                                                      3
sector 17a                                                     3
mg road                                                        3
b block sushant lok phase 1                                    3
sector 88b                                                     3
prem nagar                                                     3
gandhi nagar                                                   3
sector 17b                                                     3
maruti kunj                                                    3
acharya puri                                                   2
golf course road                                               2
ambience island                                                2
daulatabad                                                     2
manohar nagar                                                  2
surat nagar phase 2                                            2
samaspur                                                       2
sector 15 part 1                                               2
farukhnagar                                                    2
west rajiv nagar                                               2
new basti                                                      2
mayfield garden                                                2
sector 15 part 2                                               2
sispal vihar                                                   2
rajiv chowk                                                    2
surat nagar                                                    2
sector 32                                                      2
sector 41                                                      2
hira nagar                                                     2
faridabad road                                                 2
mohan nagar                                                    2
shankar vihar                                                  2
new palam vihar phase 2                                        2
sector-11 sohna                                                2
new palam vihar phase 1                                        2
sheetla colony                                                 2
sushant lok                                                    2
nars                                                           2
rosewood                                                       2
block a surya vihar                                            2
pratap nagar                                                   2
shakti nagar                                                   2
sector-2 sohna                                                 2
bissar                                                         2
golf course ext road                                           2
iffco chowk                                                    2
sector 24                                                      2
sector 21                                                      2
shanti nagar                                                   2
sohna  road                                                    2
bhawani enclave                                                2
, delhi ncr                                                    2
lajpat nagar                                                   2
mahalaxmi garden, rajendra place                               1
laxmna vihar, phase 2                                          1
cyber city                                                     1
dhankot                                                        1
ashok vihar phase i                                            1
rajiv colony                                                   1
devi lal colony gali no 12 gurgaon nr omkar public school      1
om nagar                                                       1
sultanpur                                                      1
sector 37b                                                     1
laxman vihar, railway road,                                    1
hsiidc plot sector 1 imt manesar                               1
khandsa                                                        1
godrej aria , sector 79 ,                                      1
saroop garden rajendra park                                    1
ravi nager basai road                                          1
carterpuri village                                             1
near khandsa road                                              1
near pataudi chowk                                             1
alipur                                                         1
mahavir pura                                                   1
near sector 1 market                                           1
sector 42                                                      1
g block dlf city phase 1                                       1
begampur khatola                                               1
sector 4 urban estate                                          1
sector-5 sohna                                                 1
v block dlf phase 3                                            1
new colony, sector 7                                           1
near nand hospital                                             1
tekchand nagar                                                 1
garauli kalan                                                  1
hno 13 sagar enclave sura                                      1
ats marigold                                                   1
vir nagar                                                      1
gopal nagar, garhi ghasita, sonipat                            1
sector-7 hous                                                  1
sector 17c                                                     1
block g sector-57                                              1
heritage city                                                  1
saraswati enclave                                              1
sector 21a faridabad                                           1
sector 37a                                                     1
sector-5 sheetla colony                                        1
bptp                                                           1
sector 9b                                                      1
lucknow                                                        1
part 3 sector 5                                                1
old delhi road, opp sector-14                                  1
pataudi road                                                   1
b1 block sector 57                                             1
shivji park colony                                             1
bhora kalan                                                    1
urban estate, sector 5                                         1
sector 5 chowk                                                 1
civil l                                                        1
damdma                                                         1
block h ashok vihar phase iii extension                        1
sector 13                                                      1
sec 3 bhim vihar part 1 bhimgher kheri                         1
bhimgarh kheri phase 3                                         1
new jyoti park                                                 1
park view                                                      1
ansal's palam vihar                                            1
anand garden, sector-105                                       1
huda saraswati vihar                                           1
near euro                                                      1
ram nagar                                                      1
south city                                                     1
rattan garden                                                  1
jat colony,fazilpur/taj nagar road                             1
jacobpura near sadar bazar                                     1
sector-35 sohna                                                1
sai kunj                                                       1
kheri                                                          1
sadar bazar                                                    1
kanahi                                                         1
nirvana country pocket h                                       1
ashok vihar phase 3                                            1
Name: count, dtype: int64

In [16]:
df['sector'] = df['sector'].str.replace('dharam colony','sector 12')
df['sector'] = df['sector'].str.replace('krishna colony','sector 7')
df['sector'] = df['sector'].str.replace('suncity','sector 54')
df['sector'] = df['sector'].str.replace('prem nagar','sector 13')
df['sector'] = df['sector'].str.replace('mg road','sector 28')
df['sector'] = df['sector'].str.replace('gandhi nagar','sector 28')
df['sector'] = df['sector'].str.replace('laxmi garden','sector 11')
df['sector'] = df['sector'].str.replace('shakti nagar','sector 11')

In [17]:
df['sector'] = df['sector'].str.replace('baldev nagar','sector 7')
df['sector'] = df['sector'].str.replace('shivpuri','sector 7')
df['sector'] = df['sector'].str.replace('garhi harsaru','sector 17')
df['sector'] = df['sector'].str.replace('imt manesar','manesar')
df['sector'] = df['sector'].str.replace('adarsh nagar','sector 12')
df['sector'] = df['sector'].str.replace('shivaji nagar','sector 11')
df['sector'] = df['sector'].str.replace('bhim nagar','sector 6')
df['sector'] = df['sector'].str.replace('madanpuri','sector 7')

In [18]:
df['sector'] = df['sector'].str.replace('saraswati vihar','sector 28')
df['sector'] = df['sector'].str.replace('arjun nagar','sector 8')
df['sector'] = df['sector'].str.replace('ravi nagar','sector 9')
df['sector'] = df['sector'].str.replace('vishnu garden','sector 105')
df['sector'] = df['sector'].str.replace('bhondsi','sector 11')
df['sector'] = df['sector'].str.replace('surya vihar','sector 21')
df['sector'] = df['sector'].str.replace('devilal colony','sector 9')
df['sector'] = df['sector'].str.replace('valley view estate','gwal pahari')

In [19]:
df['sector'] = df['sector'].str.replace('mehrauli  road','sector 14')
df['sector'] = df['sector'].str.replace('jyoti park','sector 7')
df['sector'] = df['sector'].str.replace('ansal plaza','sector 23')
df['sector'] = df['sector'].str.replace('dayanand colony','sector 6')
df['sector'] = df['sector'].str.replace('sushant lok phase 2','sector 55')
df['sector'] = df['sector'].str.replace('chakkarpur','sector 28')
df['sector'] = df['sector'].str.replace('greenwood city','sector 45')
df['sector'] = df['sector'].str.replace('subhash nagar','sector 12')

In [20]:
df['sector'] = df['sector'].str.replace('sohna road road','sohna road')
df['sector'] = df['sector'].str.replace('malibu town','sector 47')
df['sector'] = df['sector'].str.replace('surat nagar 1','sector 104')
df['sector'] = df['sector'].str.replace('new colony','sector 7')
df['sector'] = df['sector'].str.replace('mianwali colony','sector 12')
df['sector'] = df['sector'].str.replace('jacobpura','sector 12')
df['sector'] = df['sector'].str.replace('rajiv nagar','sector 13')
df['sector'] = df['sector'].str.replace('ashok vihar','sector 3')

In [21]:
df['sector'] = df['sector'].str.replace('sushant lok phase 3','sector 57')
df['sector'] = df['sector'].str.replace('dlf phase 5','sector 43')
df['sector'] = df['sector'].str.replace('rajendra park','sector 105')
df['sector'] = df['sector'].str.replace('uppals southend','sector 49')
df['sector'] = df['sector'].str.replace('sohna','sohna road')
df['sector'] = df['sector'].str.replace('ashok vihar phase 3 extension','sector 5')
df['sector'] = df['sector'].str.replace('south city 1','sector 41')
df['sector'] = df['sector'].str.replace('ashok vihar phase 2','sector 5')
df['sector'] = df['sector'].str.replace('dlf phase 1','sector 26')
df['sector'] = df['sector'].str.replace('nirvana country','sector 50')
df['sector'] = df['sector'].str.replace('palam vihar','sector 2')
df['sector'] = df['sector'].str.replace('dlf phase 2','sector 25')
df['sector'] = df['sector'].str.replace('sushant lok phase 1','sector 43')
df['sector'] = df['sector'].str.replace('laxman vihar','sector 4')
df['sector'] = df['sector'].str.replace('dlf phase 4','sector 28')
df['sector'] = df['sector'].str.replace('dlf phase 3','sector 24')
df['sector'] = df['sector'].str.replace('sector 95a','sector 95')
df['sector'] = df['sector'].str.replace('sector 23a','sector 23')
df['sector'] = df['sector'].str.replace('sector 12a','sector 12')
df['sector'] = df['sector'].str.replace('sector 3a','sector 3')
df['sector'] = df['sector'].str.replace('sector 110 a','sector 110')
df['sector'] = df['sector'].str.replace('patel nagar','sector 15')
df['sector'] = df['sector'].str.replace('a block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('maruti kunj','sector 12')
df['sector'] = df['sector'].str.replace('b block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('sector-33 sohna road','sector 33')
df['sector'] = df['sector'].str.replace('sector 1 manesar','manesar')
df['sector'] = df['sector'].str.replace('sector 4 phase 2','sector 4')
df['sector'] = df['sector'].str.replace('sector 1a manesar','manesar')
df['sector'] = df['sector'].str.replace('c block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('sector 89 a','sector 89')
df['sector'] = df['sector'].str.replace('sector 2 extension','sector 2')
df['sector'] = df['sector'].str.replace('sector 36 sohna road','sector 36')
df['sector']=df['sector'].str.replace('hsiidc plot manesar','sector 1')

In [22]:
df[~df['sector'].str.contains('sector')]['sector'].shape

(342,)

In [23]:
df[df['sector'].str.contains('sector')]['sector'].shape

(3600,)

In [24]:
df[~df['sector'].str.contains('sector')]['sector']

7                                              sohna road
35                                            iffco chowk
37                                             sohna road
50                                             sohna road
60                                             sohna road
84                                             sohna road
94                                             sohna road
130                                            sohna road
136                                       sohna road road
148                                                  nars
152                                               manesar
157                                           surat nagar
158                                            sohna road
161                                            sohna road
162                                                   new
198                                            sohna road
201                                            sohna road
218                                    near pataudi chowk
221                                               manesar
228                                            sohna road
230                                            sohna road
238                                            sohna road
239                                           mohan nagar
240                                            sohna road
249                                            sohna road
254                                            sohna road
267                                            sohna road
270                                                alipur
281                                          mahavir pura
287                                     dwarka expressway
290                                        faridabad road
296                                            hira nagar
304                                          rajiv colony
309                                            sohna road
314                                               manesar
328     devi lal colony gali no 12 gurgaon nr omkar pu...
357                                     near khandsa road
359                                            sohna road
372                                            sohna road
380                                           gwal pahari
426                                               manesar
428                                       sohna road road
436                                            sohna road
443                                               manesar
456                                    carterpuri village
462                                                   new
481                                            sohna road
485                                            sohna road
496                                         shankar vihar
501                                           gwal pahari
505                                            sohna road
507                                 ravi nager basai road
511                                            sohna road
529                                               manesar
538                                           , delhi ncr
568                                            sohna road
580                                               manesar
587                                               manesar
588                                  golf course ext road
644                                         garauli kalan
649                                            sohna road
651                                            sohna road
652                                            sohna road
687                                    near nand hospital
692                                            sohna road
698                                            sohna road
703                                               manesar
707                                            sohna road
711                                           gwal pahari
712                                              samaspur
716                                            sohna road
725                                           farukhnagar
736                                        tekchand nagar
747                                            sohna road
764                                                bissar
790                                       sohna road road
806                                               manesar
868                                               manesar
870                                       bhawani enclave
892                                            sohna road
893                                      sohna road  road
911                                               manesar
927                                     dwarka expressway
933                                            sohna road
948                                            sohna road
962                                            sohna road
973                                            sohna road
985                              g block dlf city phase 1
996                                           gwal pahari
998                                            sohna road
1011                                           sohna road
1033                                  surat nagar phase 2
1041                                      sohna road road
1052                                           sohna road
1059                                           sohna road
1064                                           sohna road
1065                                           sohna road
1082                                           sohna road
1084                                          gwal pahari
1091                                           sohna road
1110                                           sohna road
1134                                           sohna road
1136                                           sohna road
1156                                           sohna road
1158                                         shanti nagar
1166                                     begampur khatola
1185                                           sohna road
1189                                           sohna road
1207                                           sohna road
1242                                              manesar
1261                                           sohna road
1271                                           daulatabad
1276                                          gwal pahari
1285                                              manesar
1290                                              manesar
1315                  gopal nagar, garhi ghasita, sonipat
1339                                           sohna road
1342                                              manesar
1355                                            vir nagar
1356                                      sohna road road
1357                            hno 13 sagar enclave sura
1368                                           sohna road
1376                                         ats marigold
1384                                        manohar nagar
1398                                           sohna road
1422                                              manesar
1435                                      ambience island
1444                                           sohna road
1462                                      sohna road road
1467                                           sohna road
1468                                              lucknow
1489                                           sohna road
1491                                                 bptp
1508                                           sohna road
1513                                              manesar
1522                                            new basti
1540                                  surat nagar phase 2
1564                                              civil l
1596                                           sohna road
1618                                           sohna road
1641                                    saraswati enclave
1643                                           sohna road
1660                                           hira nagar
1662                                        heritage city
1684                                           sohna road
1689                                           sohna road
1696                                           sohna road
1704                                           sohna road
1705                                           sohna road
1712                                           sohna road
1723                                           sohna road
1741                                           sohna road
1752                                           sohna road
1757                                         sispal vihar
1762                                              manesar
1783                                     sohna road  road
1809                                           sohna road
1810                                           sohna road
1823                                              manesar
1824                                          gwal pahari
1835                                           sohna road
1837                                          bhora kalan
1841                                          rajiv chowk
1851                                           sohna road
1864                                           sohna road
1870                                           sohna road
1880                                              manesar
1891                                           sohna road
1924                                         lajpat nagar
1932                                           sohna road
1934                                    dwarka expressway
1958                                   shivji park colony
1971                                           sohna road
1976                                           sohna road
1995                                           sohna road
2008                                           sohna road
2011                                           sohna road
2016                                          gwal pahari
2029                                           sohna road
2033                                      mayfield garden
2042                                         pataudi road
2089                                           sohna road
2091                                              manesar
2094                                            park view
2097                                              manesar
2100                                                 nars
2111                                           sohna road
2114                                           sohna road
2116                                           sohna road
2120                                           sohna road
2124                                           sohna road
2125               sec 3 bhim vihar part 1 bhimgher kheri
2129                                           sohna road
2131                                           sohna road
2133                                           sohna road
2138                               bhimgarh kheri phase 3
2141                                          gwal pahari
2153                                           sohna road
2154                                         acharya puri
2160                                           sohna road
2161                                    dwarka expressway
2165                                               damdma
2197                                           sohna road
2204                                           sohna road
2208                                           sohna road
2214                                         acharya puri
2218                                            ram nagar
2220                                           sohna road
2230                                            near euro
2235                                              manesar
2246                                           sohna road
2282                                           sohna road
2285                                      bhawani enclave
2297                                          gwal pahari
2312                                           sohna road
2329                                           sohna road
2334                                          , delhi ncr
2349                                           sohna road
2362                                              manesar
2379                                           sohna road
2380                                              manesar
2401                                           south city
2403                                           sohna road
2413                                          gwal pahari
2438                                      sohna road road
2454                                           sohna road
2501                                           sohna road
2503                                           sohna road
2523                                           sohna road
2529                                        rattan garden
2530                                    dwarka expressway
2555                                         lajpat nagar
2565                                              manesar
2571                                     golf course road
2610                                            new basti
2627                                    dwarka expressway
2631                   jat colony,fazilpur/taj nagar road
2637                                              manesar
2641                                           sohna road
2651                                               bissar
2653                                          gwal pahari
2658                                           sohna road
2692                                           sohna road
2723                                      sohna road road
2728                                           sohna road
2740                                           sohna road
2763                                           sohna road
2774                                           sohna road
2785                                              dhankot
2808                                           sohna road
2811                                laxmna vihar, phase 2
2822                                           cyber city
2825                                              manesar
2838                                             om nagar
2858                                       sheetla colony
2863                                           sohna road
2879                                           sohna road
2914                                        shankar vihar
2958                                           sohna road
2959                                         sispal vihar
2964                                          farukhnagar
2965                                           sohna road
2969                                              manesar
2973                                           sohna road
2986                                           sohna road
3031                                           sohna road
3037                                          sushant lok
3040                                           sohna road
3084                                      ambience island
3089                                             samaspur
3098                                          iffco chowk
3099                                          gwal pahari
3100                                           sohna road
3101                                           sohna road
3115                                           sohna road
3142                                            sultanpur
3190                                           daulatabad
3214                                           sohna road
3215                                          gwal pahari
3220                                           sohna road
3221                                              khandsa
3223                                           sohna road
3224                                           sohna road
3231                                           sohna road
3242                                           sohna road
3257                                 golf course ext road
3258                                           sohna road
3260                                          rajiv chowk
3261                                          sushant lok
3292                                      sohna road road
3295                                      mayfield garden
3324                                           sohna road
3337                                           sohna road
3345                                           sohna road
3353                                          surat nagar
3360                                          gwal pahari
3361                                        manohar nagar
3365                                           sohna road
3370                                           sohna road
3379                                          mohan nagar
3381                                       sheetla colony
3394                                          gwal pahari
3400                                           sohna road
3401                                       faridabad road
3414                                              manesar
3448                                             rosewood
3457                                         pratap nagar
3472                                                  new
3495                                    dwarka expressway
3517                                             sai kunj
3521                                           sohna road
3528                                              manesar
3552                                         shanti nagar
3561                                          gwal pahari
3564                                    dwarka expressway
3568                                                kheri
3582                                           sohna road
3583                                           sohna road
3587                                           sohna road
3588                                          sadar bazar
3593                                               kanahi
3611                                      sohna road road
3627                                              manesar
3628                                      sohna road road
3629                                           sohna road
3649                                             rosewood
3652                                         pratap nagar
3656                                           sohna road
3724                                      sohna road road
3749                                           sohna road
3759                                           sohna road
3771                                           sohna road
3777                                           sohna road
3789                                           sohna road
3804                                           sohna road
3831                                           sohna road
3853                                                  new
3855                                           sohna road
3875                                           sohna road
3895                                           sohna road
3908                                     golf course road
3917                                          gwal pahari
Name: sector, dtype: object

In [25]:
import re

def normalize(text):
    text = str(text).lower()

    # remove duplicate words: "road road"
    text = re.sub(r'\b(\w+)\s+\1\b', r'\1', text)

    # remove punctuation
    text = re.sub(r'[^a-z0-9\s]', ' ', text)

    # remove extra spaces
    text = re.sub(r'\s+', ' ', text).strip()

    return text

df["sector"] = df["sector"].apply(normalize)

In [26]:
sector_map = {
    "sohna road": 48,
    "iffco chowk": 29,
    "manesar": 1,
    "nars": -1,
    "surat nagar": 104,
    "near pataudi chowk": 10,
    "mohan nagar": 5,
    "alipur": 110,
    "patel nagar": 15,
    "mahavir pura": 4,
    "dwarka expressway": 106,
    "faridabad road": 56,
    "hira nagar": 7,
    "rajiv colony": 33,
    "near khandsa road": 37,
    "gwal pahari": 59,
    "carterpuri village": 23,
    "shankar vihar": 110,
    "ravi nager basai road": 9,
    ", delhi ncr": -1,
    "garauli kalan": 68,
    "near nand hospital": 15,
    "samaspur": 37,
    "farukhnagar": 2,
    "tekchand nagar": 12,
    "bissar": 9,
    "bhawani enclave": 9,
    "g block dlf city phase 1": 26,
    "shanti nagar": 11,
    "begampur khatola": 38,
    "daulatabad": 104,
    "vir nagar": 11,
    "ats marigold": 89,
    "manohar nagar": 11,
    "ambience island": 24,
    "lucknow": -1,
    "bptp": 102,
    "new basti": 7,
    "civil l": 12,
    "saraswati enclave": 10,
    "heritage city": 25,
    "sispal vihar": 49,
    "bhora kalan": 81,
    "rajiv chowk": 33,
    "lajpat nagar": 12,
    "shivji park colony": 10,
    "pataudi road": 10,
    "park view": 48,
    "maruti kunj": 9,
    "bhimgarh kheri": 3,
    "acharya puri": 4,
    "damdma": 68,
    "ram nagar": 4,
    "south city": 41,
    "rattan garden": 7,
    "cyber city": 24,
    "om nagar": 11,
    "sheetla colony": 5,
    "sultanpur": 57,
    "khandsa": 37,
    "pratap nagar": 8,
    "sai kunj": 83,
    "kheri": 3,
    "sadar bazar": 12,
    "kanahi": 35,
    "dhankot": 102,
    "laxmna vihar phase 2": 4,
    "sushant lok": 43,
    "sonipat (garhi ghasita)": -1,
    "new": -1,
    "delhi ncr": -1,
    "devi lal colony gali no 12 gurgaon nr omkar public school": 9,
    "golf course ext road": 65,
    "surat nagar phase 2": 104,
    "gopal nagar garhi ghasita sonipat": -1,
    "hno 13 sagar enclave sura": 3,
    "mayfield garden": 51,
    "sec 3 bhim vihar part 1 bhimgher kheri": 3,
    "bhimgarh kheri phase 3": 3,
    "near euro": 47,
    "golf course road": 54,
    "jat colony fazilpur taj nagar road": 10,
    "rosewood": 49
}

In [27]:
def fill_sector(text):
    if pd.isna(text):
        return text
    text_l=text.lower().strip()
    if 'sector' in text_l:
        return text_l
    if text_l in sector_map.keys():
        return 'sector '+ str(sector_map[text])
    return text_l

In [28]:
mask=df[~df['sector'].str.contains('sector')]['sector'].apply(fill_sector)

In [29]:
df.loc[mask.index,'sector']=mask

In [30]:
mask.index

Index([   7,   35,   37,   50,   60,   84,   94,  130,  136,  148,
       ...
       3777, 3789, 3804, 3831, 3853, 3855, 3875, 3895, 3908, 3917],
      dtype='int64', length=342)

In [31]:
df[~df['sector'].str.contains('sector')]['sector'].shape

(0,)

In [32]:
df[~df['sector'].str.contains('sector')]['sector']

Series([], Name: sector, dtype: object)

In [33]:
df['sector']

0                                 sector 37d
1                                   sector 7
2                                  sector 14
3                                  sector 92
4                                   sector 4
5                                  sector 53
6                                 sector 37c
7                                  sector 48
8                                 sector 108
9                                   sector 4
10                                 sector 50
11                                 sector 78
12                                 sector 69
13                                 sector 61
14                                 sector 85
15                                 sector 26
16                                 sector 83
17                                 sector 43
18                                 sector 84
19                                sector 102
20                                 sector 91
21                                 sector 79
22                                 sector 90
23                                sector 108
24                                sector 106
25                                 sector 95
26                                 sector 50
27                                sector 113
28                                sector 102
29                                 sector 79
30                                 sector 67
31                                 sector 95
32                                  sector 3
33                                sector 111
34                                sector 108
35                                 sector 29
36                                 sector 33
37                                 sector 48
38                                 sector 82
39                                sector 108
40                                sector 70a
41                                sector 103
42                                 sector 60
43                                 sector 51
44                                 sector 22
45                                 sector 33
46                                sector 102
47                                 sector 13
48                                 sector 83
49                                sector 103
50                                 sector 48
51                                sector 99a
52                                sector 37d
53                                sector 106
54                                 sector 43
55                                 sector 59
56                                 sector 12
57                                 sector 79
58                                 sector 56
59                                 sector 92
60                                 sector 48
61                                 sector 26
62                                 sector 85
63                                 sector 66
64                                 sector 92
65                                 sector 25
66                                sector 104
67                                sector 82a
68                                sector 113
69                                 sector 62
70                                sector 70a
71                                 sector 49
72                                 sector 45
73                                sector 37c
74                                sector 109
75                                 sector 15
76                                 sector 56
77                          sector 3 phase 2
78                                 sector 33
79                      sector 11 sohna road
80                                 sector 86
81                                 sector 83
82                                  sector 2
83                                  sector 8
84                                 sector 48
85                                sector 37d
86                                 sector 69
87                                 sector 65
88                                 sector 54
89                                 sector 21
90                                sector 103
91                                sector 106
92                                  sector 3
93                                 sector 33
94                                 sector 48
95                                 sector 26
96                                 sector 83
97                                 sector 71
98                                 sector 81
99                                 sector 22
100                               sector 107
101                                sector 54
102                               sector 111
103                                sector 79
104                                sector 48
105                                sector 82
106                                sector 85
107                                sector 67
108                                sector 81
109                               sector 102
110                                sector 93
111                                sector 48
112                               sector 70a
113                                sector 79
114                                sector 12
115                                sector 79
116                                sector 25
117                                sector 90
118                                sector 54
119                                sector 26
120                                sector 41
121                               sector 70a
122                                sector 66
123                               sector 108
124                                sector 95
125                                sector 67
126                                sector 66
127                                sector 89
128                                sector 90
129                                sector 86
130                                sector 48
131                                sector 62
132                               sector 109
133                                sector 39
134                                sector 43
135                               sector 102
136                                sector 48
137                                sector 90
138                                sector 12
139                                sector 49
140                                sector 95
141                               sector 99a
142                               sector 99a
143                               sector 99a
144                                sector 72
145                                sector 69
146                               sector 102
147                                sector 49
148                                sector -1
149                                sector 12
150                                sector 62
151                                sector 21
152                                 sector 1
153                                 sector 5
154                                sector 50
155                                 sector 4
156                                sector 47
157                               sector 104
158                                sector 48
159                                sector 57
160                               sector 70a
161                                sector 48
162                                sector -1
163                                sector 79
164                                 sector 4
165                                sector 14
166                                 sector 2
167                                sector 70
168                                sector 70
169                               sector 70a
170                               sector 102
171                                sector 25
172                                 sector 6
173                               sector 103
174                                sector 54
175                                sector 11
176                                sector 22
177                                sector 71
178                                 sector 4
179                                sector 12
180                               sector 107
181                                sector 9a
182                                sector 72
183                                sector 39
184                                sector 81
185                               sector 107
186                                sector 60
187                                sector 11
188                                sector 49
189                                sector 69
190                                sector 77
191                                 sector 7
192                                sector 49
193                                sector 60
194                               sector 104
195                                sector 86
196                               sector 107
197                                sector 47
198                                sector 48
199                                sector 9a
200                                sector 85
201                                sector 48
202                                sector 48
203                               sector 112
204                                sector 65
205                                 sector 2
206                                sector 99
207                 saroop garden sector 105
208                                sector 67
209                               sector 102
210                                sector 57
211                                sector 52
212                                sector 90
213                                sector 53
214                                sector 95
215                               sector 88a
216                                sector 67
217                               sector 109
218                                sector 10
219                                sector 69
220                                sector 86
221                                 sector 1
222                                sector 86
223                                sector 46
224                                 sector 2
225                               sector 104
226                               sector 107
227                               sector 102
228                                sector 48
229                                sector 14
230                                sector 48
231                               sector 111
232                                sector 91
233                               sector 113
234                               sector 63a
235                                sector 48
236                                 sector 2
237                                sector 62
238                                sector 48
239                                 sector 5
240                                sector 48
241                                sector 65
242                                sector 69
243                                sector 82
244                                 sector 1
245                               sector 111
246                                sector 50
247                               sector 109
248                               sector 70a
249                                sector 48
250                                sector 58
251                               sector 110
252                                sector 48
253                                sector 60
254                                sector 48
255                               sector 109
256                                sector 54
257                               sector 37c
258                               sector 113
259                                sector 74
260                               sector 37c
261                                sector 72
262                                sector 84
263                                sector 49
264                                sector 24
265                                sector 89
266                               sector 63a
267                                sector 48
268                                sector 92
269                                sector 69
270                               sector 110
271                                sector 70
272                                sector 65
273                               sector 37d
274                                sector 65
275                                sector 17
276                               sector 110
277                                sector 15
278                                 sector 7
279                               sector 37d
280                                sector 13
281                                 sector 4
282                                sector 27
283                                sector 99
284                                sector 25
285                                sector 90
286                                sector 62
287                               sector 106
288                               sector 109
289                                sector 33
290                                sector 56
291                                 sector 2
292                                sector 41
293                               sector 112
294                                sector 86
295                               sector 109
296                                 sector 7
297                               sector 107
298                                sector 90
299                                sector 79
300                               sector 102
301                                sector 67
302                               sector 88a
303                               sector 104
304                                sector 33
305                               sector 106
306                                sector 82
307                               sector 104
308                                sector 24
309                                sector 48
310                                sector 41
311                                sector 82
312                                sector 69
313                                sector 33
314                                 sector 1
315                               sector 104
316                                sector 14
317                                sector 85
318                               sector 36a
319                               sector 37d
320                                sector 79
321                               sector 104
322                                sector 68
323                                 sector 9
324                                sector 13
325                                sector 85
326                                sector 70
327                               sector 111
328                                 sector 9
329                               sector 103
330                                sector 85
331                                sector 70
332                               sector 113
333                                sector 56
334                                sector 83
335                                sector 50
336                               sector 105
337                               sector 107
338                                sector 66
339                                sector 76
340                                sector 86
341                               sector 106
342                                sector 81
343                                 sector 2
344                                sector 86
345                               sector 102
346                               sector 102
347                                sector 91
348                                sector 56
349                                sector 28
350                                sector 66
351                                sector 58
352                                 sector 2
353                                sector 83
354                     new sector 2 phase 2
355                                sector 61
356                                 sector 4
357                                sector 37
358                                 sector 2
359                                sector 48
360                               sector 70a
361                                sector 90
362                                sector 77
363                                sector 71
364                                sector 83
365                               sector 108
366                               sector 37d
367                                sector 91
368               sector 3 phase 3 extension
369                                 sector 3
370                               sector 70a
371                                sector 95
372                                sector 48
373                                sector 81
374                                sector 92
375                                sector 48
376                                sector 78
377                                sector 81
378                                sector 43
379                                sector 84
380                                sector 59
381                                sector 79
382                               sector 106
383                                sector 49
384                               sector 104
385                               sector 113
386                                sector 72
387                                sector 63
388                                sector 78
389                                sector 82
390                                sector 82
391                                sector 12
392                                sector 56
393                                sector 85
394                                sector 14
395                                sector 23
396                                sector 36
397                               sector 102
398                                sector 23
399                                sector 79
400                                sector 55
401                                sector 41
402                               sector 37d
403                               sector 108
404                                sector 81
405                                sector 60
406                                 sector 5
407                               sector 67a
408                                sector 76
409                                sector 22
410                                sector 43
411                                 sector 4
412                                sector 92
413                               sector 107
414                                sector 81
415                                sector 66
416                                sector 85
417                                sector 66
418                                sector 14
419                               sector 102
420                               sector 113
421                               sector 105
422                                sector 55
423                               sector 37d
424                               sector 106
425                               sector 102
426                                 sector 1
427                               sector 37d
428                                sector 48
429                                sector 14
430                                sector 50
431                                sector 85
432                                sector 79
433                                sector 65
434                               sector 104
435                                sector 79
436                                sector 48
437                                sector 26
438                                sector 78
439                                sector 67
440                                 sector 9
441                                sector 65
442                                sector 69
443                                 sector 1

In [34]:
df['sector'].value_counts()

sector
sector 48                               234
sector 102                              115
sector 85                               110
sector 92                               104
sector 69                                94
sector 65                                92
sector 81                                91
sector 90                                90
sector 109                               88
sector 79                                80
sector 104                               79
sector 33                                74
sector 83                                70
sector 43                                69
sector 37d                               68
sector 86                                67
sector 95                                66
sector 2                                 65
sector 89                                65
sector 50                                64
sector 107                               60
sector 56                                59
sector 108                               58
sector 70a                               54
sector 70                                53
sector 37c                               53
sector 4                                 53
sector 49                                52
sector 26                                51
sector 84                                51
sector 67                                48
sector 106                               46
sector 28                                46
sector 103                               45
sector 7                                 44
sector 113                               43
sector 82                                42
sector 25                                42
sector 66                                42
sector 12                                42
sector 61                                42
sector 1                                 40
sector 54                                33
sector 68                                32
sector 99a                               32
sector 77                                29
sector 72                                29
sector 3                                 28
sector 71                                27
sector 24                                26
sector 59                                26
sector 11                                25
sector 57                                25
sector 112                               24
sector 14                                23
sector 105                               23
sector 88a                               23
sector 111                               22
sector 67a                               22
sector 110                               22
sector 82a                               20
sector 22                                20
sector 47                                20
sector 78                                19
sector 9                                 19
sector 63a                               18
sector 74                                18
sector 62                                17
sector 91                                17
sector 99                                16
sector 63                                15
sector 60                                15
sector 53                                14
sector 52                                14
sector 76                                14
sector 55                                14
sector 23                                14
sector 46                                13
sector 6                                 13
sector 38                                13
sector 36a                               13
sector 41                                12
sector 31                                12
sector 39                                12
sector 93                                12
sector 3 phase 3 extension               11
sector 36                                11
sector 9a                                11
sector 13                                10
sector 5                                 10
sector -1                                10
sector 8                                 10
sector 51                                 9
sector 3 phase 2                          9
sector 45                                 8
sector 17                                 8
sector 10a                                8
sector 40                                 8
sector 58                                 7
sector 15                                 7
sector 21                                 6
new sector 2                              5
sector 80                                 5
sector 10                                 5
sector 30                                 5
sector 37                                 4
sector 27                                 3
sector 88b                                3
sector 17b                                3
sector 17a                                3
sector 73                                 3
new sector 2 phase 1                      2
sector 11 sohna road                      2
sector 29                                 2
new sector 2 phase 2                      2
sector 15 part 2                          2
west sector 13                            2
sector 32                                 2
block a sector 21                         2
sector 15 part 1                          2
sector 2 sohna road                       2
saroop garden sector 105                  1
sector 4 urban estate                     1
near sector 1 market                      1
sector 17c                                1
sector 7 hous                             1
sector 42                                 1
v block sector 24                         1
sector 5 sohna road                       1
sector 7 sector 7                         1
block g sector 57                         1
urban estate sector 5                     1
sector 5 chowk                            1
b1 block sector 57                        1
old delhi road opp sector 14              1
sector 5 sheetla colony                   1
sector 37a                                1
sector 21a faridabad                      1
sector 9b                                 1
huda sector 28                            1
block h sector 3 phase iii extension      1
new sector 7                              1
part 3 sector 5                           1
anand garden sector 105                   1
sector 3 phase i                          1
mahasector 11 rajendra place              1
ansal s sector 2                          1
sector 4 railway road                     1
godrej aria sector 79                     1
sector 37b                                1
sector 12 near sadar bazar                1
sector 35 sohna road                      1
sector 35                                 1
sector 50 pocket h                        1
sector 3 phase 3                          1
Name: count, dtype: int64

In [35]:
df['sector'].isna().sum()

np.int64(0)

In [36]:
#find a way to fill them
df[df['sector'].str.contains('-1')]

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
148,2 Bedroom House for sale in Narsinghpur,house,sector 37,sector -1,55.11,7290.0,75597.0,Plot area 84(70.23 sq.m.)Built Up area: 83 sq....,2,1,1,store room,"House No. 4, Narsinghpur, Gurgaon, Haryana",1.0,East,0 to 1 Year Old,"['S.R.S. Hospital and Critical Care Unit', 'Ko...",Independent house available for sale in narsin...,"['1 Wardrobe', '10 Light', '1 Modular Kitchen'...","['Feng Shui / Vaastu Compliant', 'Private Gard...",NaN
162,2 BHK Flat in New Gurgaon,flat,takshila heights sector c,sector -1,0.67,5583.0,1200.1,Super Built up area 1200(111.48 sq.m.),2,2,2,not available,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,1 to 5 Year Old,"['Shri Balaji Hospital and Trauma Center', 'S....",Check out this 2 bhk apartment for sale in tak...,[],"['Lift(s)', 'Swimming Pool', 'Visitor Parking'...",NaN
462,2 BHK Flat in New Gurgaon,flat,green court,sector -1,0.38,5507.0,690.0,Carpet area: 690 (64.1 sq.m.),2,2,1,not available,"New Gurgaon, Gurgaon, Haryana",7.0,NaN,Under Construction,"['Ing bank ATM', 'Dcb bank ATM', 'Indus ind ba...",We are the proud owners of this 2 bhk apartmen...,[],"['Intercom Facility', 'Lift(s)', 'Maintenance ...",NaN
538,"5 Bedroom House for sale in Gurgaon, Delhi NCR",house,independent,sector -1,50.00,3704.0,134989.0,Built Up area: 1350 (125.42 sq.m.),5,2,0,not available,"Gurgaon, Delhi NCR, Gurgaon, Haryana",2.0,NaN,undefined,NaN,5bhk residential house for resale in at gurgao...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,NaN
1315,"4 Bedroom House for sale in Gopal Nagar, Garhi...",house,independent,sector -1,1.00,11111.0,900.0,Plot area 100(83.61 sq.m.),4,3,3+,others,"162/28, Gopal Nagar, Garhi Ghasita, Near Malik...",4.0,North-East,1 to 5 Year Old,"['Hanuman Mandir', 'State bank of india ATM', ...","A. New building, \nB. Basement+duplex showroom...","['1 Water Purifier', '1 Exhaust Fan', '1 Chimn...",NaN,NaN
1468,7 Bedroom House for sale in Lucknow,house,dlf garden city floors,sector -1,4.00,17817.0,2245.0,Plot area 2245(208.57 sq.m.),7,7,3+,not available,"Lucknow, Gurgaon, Haryana",4.0,NaN,0 to 1 Year Old,"['Sapphire 83 Mall', 'Dwarka Expressway', 'NH-...",I have a house/villa available for sale in dlf...,[],"['Feng Shui / Vaastu Compliant', 'Private Gard...",NaN
2100,2 Bedroom House for sale in Narsinghpur,house,independent,sector -1,52.75,63554.0,8300.0,Plot area 83(7.71 sq.m.)Built Up area: 84 sq.f...,2,1,1,store room,"Narsinghpur, Gurgaon, Haryana",1.0,East,0 to 1 Year Old,"['S.R.S. Hospital and Critical Care Unit', 'Ko...",Independent house available for sale in sector...,"['1 Wardrobe', '3 Fan', '1 Exhaust Fan', '10 L...","['Feng Shui / Vaastu Compliant', 'Private Gard...",NaN
2334,"9 Bedroom House for sale in Gurgaon, Delhi NCR",house,independent,sector -1,1.50,16667.0,900.0,Carpet area: 900 (83.61 sq.m.),9,3,3+,not available,"Gurgaon, Delhi NCR, Gurgaon, Haryana",3.0,NaN,undefined,NaN,9bhk residential house for resale in at gurgao...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,NaN
3472,4 BHK Flat in New Gurgaon,flat,dlf,sector -1,4.00,11428.0,3500.2,Carpet area: 3500 (325.16 sq.m.),4,4,2,"Study Room,Servant Room","New Gurgaon, Gurgaon, Haryana",4.0,NaN,Jun-27,"['Shri Balaji Hospital and Trauma Center', 'S....",This lovely 4 bhk apartment/flat in new gurgao...,"['6 Wardrobe', '1 Fridge', '8 Fan', '1 Exhaust...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...",NaN
3853,4 BHK Flat in New Gurgaon,flat,sare homes,sector -1,0.85,4786.0,1776.0,Super Built up area 1776(165 sq.m.),4,4,3,not available,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,5 to 10 Year Old,"['Columbia Asia Hospital', 'Apex Multi Special...",Located in the popular residential address of ...,[],NaN,NaN

In [37]:
df.shape

(3942, 21)

In [38]:
a=df['sector'].value_counts()[df['sector'].value_counts()>=3]

In [39]:
a.index

Index(['sector 48', 'sector 102', 'sector 85', 'sector 92', 'sector 69',
       'sector 65', 'sector 81', 'sector 90', 'sector 109', 'sector 79',
       ...
       'new sector 2', 'sector 80', 'sector 10', 'sector 30', 'sector 37',
       'sector 27', 'sector 88b', 'sector 17b', 'sector 17a', 'sector 73'],
      dtype='object', name='sector', length=111)

In [40]:
df=df[df['sector'].isin(a.index)]

In [41]:
df['sector'].value_counts()

sector
sector 48                     234
sector 102                    115
sector 85                     110
sector 92                     104
sector 69                      94
sector 65                      92
sector 81                      91
sector 90                      90
sector 109                     88
sector 79                      80
sector 104                     79
sector 33                      74
sector 83                      70
sector 43                      69
sector 37d                     68
sector 86                      67
sector 95                      66
sector 2                       65
sector 89                      65
sector 50                      64
sector 107                     60
sector 56                      59
sector 108                     58
sector 70a                     54
sector 70                      53
sector 37c                     53
sector 4                       53
sector 49                      52
sector 26                      51
sector 84                      51
sector 67                      48
sector 106                     46
sector 28                      46
sector 103                     45
sector 7                       44
sector 113                     43
sector 66                      42
sector 25                      42
sector 12                      42
sector 82                      42
sector 61                      42
sector 1                       40
sector 54                      33
sector 68                      32
sector 99a                     32
sector 72                      29
sector 77                      29
sector 3                       28
sector 71                      27
sector 59                      26
sector 24                      26
sector 57                      25
sector 11                      25
sector 112                     24
sector 88a                     23
sector 105                     23
sector 14                      23
sector 111                     22
sector 110                     22
sector 67a                     22
sector 22                      20
sector 82a                     20
sector 47                      20
sector 9                       19
sector 78                      19
sector 63a                     18
sector 74                      18
sector 91                      17
sector 62                      17
sector 99                      16
sector 60                      15
sector 63                      15
sector 76                      14
sector 55                      14
sector 53                      14
sector 23                      14
sector 52                      14
sector 46                      13
sector 36a                     13
sector 38                      13
sector 6                       13
sector 93                      12
sector 31                      12
sector 39                      12
sector 41                      12
sector 36                      11
sector 3 phase 3 extension     11
sector 9a                      11
sector 8                       10
sector 13                      10
sector -1                      10
sector 5                       10
sector 51                       9
sector 3 phase 2                9
sector 45                       8
sector 40                       8
sector 10a                      8
sector 17                       8
sector 15                       7
sector 58                       7
sector 21                       6
sector 10                       5
new sector 2                    5
sector 30                       5
sector 80                       5
sector 37                       4
sector 27                       3
sector 73                       3
sector 17b                      3
sector 88b                      3
sector 17a                      3
Name: count, dtype: int64

In [42]:
df.shape

(3888, 21)

In [43]:
df['sector']=df['sector'].str.lower().str.extract(r'(sector\s*-?\d+)')

In [44]:
df['sector'].value_counts()

sector
sector 48     234
sector 37     125
sector 102    115
sector 85     110
sector 70     107
sector 92     104
sector 69      94
sector 65      92
sector 81      91
sector 90      90
sector 109     88
sector 79      80
sector 104     79
sector 33      74
sector 67      70
sector 83      70
sector 2       70
sector 43      69
sector 86      67
sector 95      66
sector 89      65
sector 50      64
sector 82      62
sector 107     60
sector 56      59
sector 108     58
sector 4       53
sector 49      52
sector 84      51
sector 26      51
sector 3       48
sector 99      48
sector 106     46
sector 28      46
sector 103     45
sector 7       44
sector 113     43
sector 12      42
sector 61      42
sector 66      42
sector 25      42
sector 1       40
sector 63      33
sector 54      33
sector 68      32
sector 9       30
sector 72      29
sector 77      29
sector 71      27
sector 24      26
sector 59      26
sector 88      26
sector 57      25
sector 11      25
sector 36      24
sector 112     24
sector 14      23
sector 105     23
sector 111     22
sector 110     22
sector 22      20
sector 47      20
sector 78      19
sector 74      18
sector 91      17
sector 62      17
sector 60      15
sector 53      14
sector 17      14
sector 55      14
sector 52      14
sector 76      14
sector 23      14
sector 6       13
sector 38      13
sector 10      13
sector 46      13
sector 93      12
sector 41      12
sector 31      12
sector 39      12
sector 8       10
sector 5       10
sector 13      10
sector -1      10
sector 51       9
sector 45       8
sector 40       8
sector 15       7
sector 58       7
sector 21       6
sector 80       5
sector 30       5
sector 27       3
sector 73       3
Name: count, dtype: int64

In [45]:
df=df[~df['sector'].str.contains('sector -1')]

In [46]:
df.shape

(3878, 21)

In [47]:
df[df['sector'] == 'new']

Empty DataFrame
Columns: [property_name, property_type, society, sector, price, price_per_sqft, area, areaWithType, bedRoom, bathroom, balcony, additionalRoom, address, floorNum, facing, agePossession, nearbyLocations, description, furnishDetails, features, rating]
Index: []

In [48]:
df.duplicated().sum()

np.int64(0)

In [49]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,4 BHK Flat in Sector 37D Gurgaon,flat,bptp terra,sector 37,1.67,7622.0,2191.0,Super Built up area 2191(203.55 sq.m.)Built Up...,4,4,3,not available,"1104, Sector 37D Gurgaon, Gurgaon, Haryana",11.0,West,1 to 5 Year Old,"['Airia Mall', 'Dwarka Expressway', 'Golf Cour...",Bptp terra is one of the most popular destinat...,"['7 Fan', '18 Light', '5 AC', '1 Chimney', '1 ...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area4.5 out of 5', 'Construction4.5 ou..."
1,5 Bedroom House for sale in New Colony,house,rattan garden,sector 7,1.30,13499.0,963.0,Built Up area: 963 (89.47 sq.m.),5,3,2,not available,"New Colony, Sector 7, New Colony, Gurgaon, Har...",3.0,NaN,10+ Year Old,"['Chintapurni Mandir', 'Aryan Hospital', 'D.R....",Best in class property available at new colony...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
2,5 Bedroom House for sale in Sector 14 Gurgaon,house,independent,sector 14,4.15,18444.0,2250.0,Plot area 250(209.03 sq.m.),5,4,2,not available,"Sector 14 Gurgaon, Gurgaon, Haryana",2.0,North-West,10+ Year Old,"['Sheetla Mata Mandir', 'Hsbc bank ATM', 'Hdfc...",250 sqyds independent house for sale in sector...,"['5 Wardrobe', '8 Fan', '1 Exhaust Fan', '4 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
3,3 BHK Flat in Sector 92 Gurgaon,flat,apartment,sector 92,0.75,4687.0,1600.2,Carpet area: 1600 (148.64 sq.m.),3,4,3,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",2.0,East,5 to 10 Year Old,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...","Within 2-3 kms schools, malls, hospital are av...","['5 Fan', '7 Light', 'No AC', 'No Bed', 'No Ch...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment5 out of 5', 'Safety3 out of 5', ..."
4,5 Bedroom House for sale in Laxman Vihar,house,independent,sector 4,50.00,10482.0,47701.0,Built Up area: 53 (44.31 sq.m.),5,3,0,not available,"Laxman Vihar, Sector 3a, Laxman Vihar, Gurgaon...",1.0,NaN,undefined,NaN,5bhk residential house for resale in laxman vi...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."

In [53]:
df.drop(columns=['property_name', 'address', 'description', 'rating'],inplace=True)

In [54]:
df.shape

(3878, 17)

In [56]:
df.sample(5)

,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,floorNum,facing,agePossession,nearbyLocations,furnishDetails,features
3791,flat,ss almeria,sector 84,1.48,7400.0,2000.0,Super Built up area 2000(185.81 sq.m.)Carpet a...,3,3,2,"Servant Room,Store Room",1.0,South-West,0 to 1 Year Old,"['Sapphire 83 Mall', 'Dwarka Expressway', 'NH ...","['3 Wardrobe', '5 Fan', '3 Geyser', '1 Stove',...","['Security / Fire Alarm', 'Private Garden / Te..."
3797,flat,central park flower valley,sector 33,2.20,10476.0,2100.0,Super Built up area 2100(195.1 sq.m.),3,3,3,Servant Room,12.0,North-East,0 to 1 Year Old,"['Airia Mall', 'NH 248A', 'NE 4, Haryana', 'GD...","['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Security / F..."
3759,flat,gls arawali homes,sector 48,0.35,7000.0,500.0,Super Built up area 567(52.68 sq.m.)Built Up a...,2,2,2,not available,5.0,NaN,1 to 5 Year Old,"['Huda City Centre', 'Golf Course Road', 'Delh...",[],"['Security / Fire Alarm', 'Lift(s)', 'Maintena..."
39,flat,raheja the vedaanta floors,sector 108,0.70,4521.0,1548.3,Carpet area: 1548 (143.81 sq.m.),2,2,3,not available,1.0,NaN,5 to 10 Year Old,"['Sec21 Dwarka Metro Station', 'The Shikshiyan...","['1 Wardrobe', '1 Water Purifier', '1 Fan', '1...",NaN
3550,flat,emaar gurgaon greens,sector 102,1.38,13495.0,1022.6,Super Built up area 1650(153.29 sq.m.)Carpet a...,3,3,3,Servant Room,6.0,North-East,1 to 5 Year Old,"['JMS Marine Square Mall', 'Dwarka Expressway'...","['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '2 Ge...","['Security / Fire Alarm', 'Feng Shui / Vaastu ..."

In [57]:
df.duplicated().sum()

np.int64(124)

In [59]:
df.isna().sum()

property_type         0
society               1
sector                0
price                 1
price_per_sqft        1
area                  1
areaWithType          0
bedRoom               0
bathroom              0
balcony               0
additionalRoom        0
floorNum              2
facing             1141
agePossession         1
nearbyLocations     192
furnishDetails     1009
features            681
dtype: int64

In [60]:
df.to_csv('gurgaon_properties_cleaned_v1.csv',index=False)