In [60]:
import numpy as np 
import pandas as pd

In [61]:
df=pd.read_csv('gurgaon_properties_merge2.csv')

In [62]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [63]:
df.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,1 BHK Flat in Sector 92 Gurgaon,flat,gls avenue,0.21,6953.0,302.00,Carpet area: 302 (28.06 sq.m.),1,1,1,not available,"Sector 92 Gurgaon, Gurgaon, Haryana",0.0,South-East,1 to 5 Year Old,"['Yaduvanshi Shiksha Niketan Sector- 92', 'Aar...",Check out this 1 bhk apartment for sale in gls...,NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,4 BHK Flat in Gwal Pahari,flat,paras quartier,5.90,11028.0,5350.00,Built Up area: 5350 (497.03 sq.m.),4,4,3+,not available,"Paras Quartier, Valley View Estate, Gwal Pahar...",0.0,NaN,5 to 10 Year Old,"['Sector 55-56 Metro Station', 'South point Ma...","New apartment, lush green aravalli valley 270 ...","['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,NaN
2,3 BHK Flat in Sector 1 Imt Manesar,flat,hsiidc sidco aravali,0.90,3477.0,2588.40,Super Built up area 2588(240.43 sq.m.)Built Up...,3,3,3+,Servant Room,"Sector 1 Imt Manesar, Gurgaon, Haryana",8.0,East,5 to 10 Year Old,"['Pooja Clinic', 'Dr. Sahil Clinic', 'Prakash ...",Arawali sipco sec-1 imt manesar good property ...,"['6 Fan', '6 Light', 'No AC', 'No Bed', 'No Ch...","['Lift(s)', 'Maintenance Staff', 'Park', 'Pipe...","['Environment5 out of 5', 'Lifestyle4.5 out of..."
3,5 Bedroom House for sale in Sector 15 Gurgaon,house,sector 15 part 2 rwa,10.00,22222.0,4520.84,Plot area 502(419.74 sq.m.),5,5,2,not available,"Sector 15 Gurgaon, Gurgaon, Haryana",2.0,East,10+ Year Old,"['Hanuman Mandir', 'State bank of india ATM', ...","Gated community and near market,school and hig...",[],"['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4.5 out of 5', 'Lifestyle4 out of..."
4,2 BHK Flat in Sohna,flat,eldeco accolade,0.72,4975.0,1447.20,Super Built up area 1457(135.36 sq.m.)Carpet a...,2,2,3+,Study Room,"0001, Sohna, Gurgaon, Haryana",12.0,East,1 to 5 Year Old,"['Global City Centre', 'Sohna Road', 'Damdama ...","Eldeco accolade in sohna, gurgaon is a ready-T...",NaN,"['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction4.5 out ..."

In [64]:
df.shape

(3942, 20)

In [65]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3942 entries, 0 to 3941
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3942 non-null   object
 1   property_type    3942 non-null   object
 2   society          3941 non-null   object
 3   price            3941 non-null   float64
 4   price_per_sqft   3941 non-null   float64
 5   area             3941 non-null   float64
 6   areaWithType     3942 non-null   object
 7   bedRoom          3942 non-null   int64
 8   bathroom         3942 non-null   int64
 9   balcony          3942 non-null   object
 10  additionalRoom   3942 non-null   object
 11  address          3931 non-null   object
 12  floorNum         3940 non-null   float64
 13  facing           2771 non-null   object
 14  agePossession    3941 non-null   object
 15  nearbyLocations  3736 non-null   object
 16  description      3942 non-null   object
 17  furnishDetails   2915 non-null   object
 18  features         3237 non-null   object
 19  rating           3493 non-null   object
dtypes: float64(4), int64(2), object(14)
memory usage: 616.1+ KB

In [66]:
df.duplicated().sum()

np.int64(0)

In [67]:
df.isnull().sum()

property_name         0
property_type         0
society               1
price                 1
price_per_sqft        1
area                  1
areaWithType          0
bedRoom               0
bathroom              0
balcony               0
additionalRoom        0
address              11
floorNum              2
facing             1171
agePossession         1
nearbyLocations     206
description           0
furnishDetails     1027
features            705
rating              449
dtype: int64

In [68]:
df.insert(loc=3,column='sector',value=df['property_name'].str.split('in').str.get(1).str.replace('Gurgaon','').str.strip())

In [69]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,1 BHK Flat in Sector 92 Gurgaon,flat,gls avenue,Sector 92,0.21,6953.0,302.00,Carpet area: 302 (28.06 sq.m.),1,1,1,not available,"Sector 92 Gurgaon, Gurgaon, Haryana",0.0,South-East,1 to 5 Year Old,"['Yaduvanshi Shiksha Niketan Sector- 92', 'Aar...",Check out this 1 bhk apartment for sale in gls...,NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,4 BHK Flat in Gwal Pahari,flat,paras quartier,Gwal Pahari,5.90,11028.0,5350.00,Built Up area: 5350 (497.03 sq.m.),4,4,3+,not available,"Paras Quartier, Valley View Estate, Gwal Pahar...",0.0,NaN,5 to 10 Year Old,"['Sector 55-56 Metro Station', 'South point Ma...","New apartment, lush green aravalli valley 270 ...","['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,NaN
2,3 BHK Flat in Sector 1 Imt Manesar,flat,hsiidc sidco aravali,Sector 1 Imt Manesar,0.90,3477.0,2588.40,Super Built up area 2588(240.43 sq.m.)Built Up...,3,3,3+,Servant Room,"Sector 1 Imt Manesar, Gurgaon, Haryana",8.0,East,5 to 10 Year Old,"['Pooja Clinic', 'Dr. Sahil Clinic', 'Prakash ...",Arawali sipco sec-1 imt manesar good property ...,"['6 Fan', '6 Light', 'No AC', 'No Bed', 'No Ch...","['Lift(s)', 'Maintenance Staff', 'Park', 'Pipe...","['Environment5 out of 5', 'Lifestyle4.5 out of..."
3,5 Bedroom House for sale in Sector 15 Gurgaon,house,sector 15 part 2 rwa,Sector 15,10.00,22222.0,4520.84,Plot area 502(419.74 sq.m.),5,5,2,not available,"Sector 15 Gurgaon, Gurgaon, Haryana",2.0,East,10+ Year Old,"['Hanuman Mandir', 'State bank of india ATM', ...","Gated community and near market,school and hig...",[],"['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4.5 out of 5', 'Lifestyle4 out of..."
4,2 BHK Flat in Sohna,flat,eldeco accolade,Sohna,0.72,4975.0,1447.20,Super Built up area 1457(135.36 sq.m.)Carpet a...,2,2,3+,Study Room,"0001, Sohna, Gurgaon, Haryana",12.0,East,1 to 5 Year Old,"['Global City Centre', 'Sohna Road', 'Damdama ...","Eldeco accolade in sohna, gurgaon is a ready-T...",NaN,"['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction4.5 out ..."

In [70]:
df['sector'].value_counts()

sector
Sohna                                                        163
Sector 102                                                   113
Sector 85                                                    110
Sector 92                                                    104
Sector 69                                                     94
Sector 90                                                     90
Sector 65                                                     90
Sector 81                                                     90
Sector 109                                                    88
Sector 79                                                     80
Sector 83                                                     69
Sector 37D                                                    68
Sector 86                                                     67
Sector 104                                                    66
Sector 107                                                    60
Sector 108                                                    58
Sector 95                                                     57
Sector 56                                                     57
Sector 89                                                     56
Sector 48                                                     56
Sector 70A                                                    54
Sector 70                                                     53
Sector 37C                                                    53
Nirvana Country                                               52
Sector 84                                                     51
Sector-33 Sohna                                               51
Palam Vihar                                                   50
Sector 67                                                     48
Sector 103                                                    45
DLF Phase 1                                                   43
Sector 113                                                    43
Sector 82                                                     42
Sector 66                                                     42
Sector 61                                                     42
DLF Phase 2                                                   41
Sector 106                                                    38
Sector 49                                                     36
Sector 99A                                                    32
Sushant Lok Phase 1                                           31
Sector 68                                                     30
Sector 77                                                     29
Sector 72                                                     29
Sector 54                                                     27
Sector 71                                                     27
Laxman Vihar                                                  26
DLF Phase 4                                                   25
Sector 112                                                    24
Sector 88A                                                    23
Sector 111                                                    22
Sector 67A                                                    22
DLF Phase 3                                                   21
Sector 22                                                     20
Sector 33                                                     20
Sector 82A                                                    20
Sector 78                                                     19
Sector 63A                                                    18
Sector 74                                                     18
Sector 91                                                     17
Sector 62                                                     17
Sushant Lok Phase 3                                           16
Sector 110                                                    16
Sector 99                                                     16
Sector 14                                                     15
Sector 63                                                     15
Sector 60                                                     15
Sector 52                                                     14
Rajendra Park                                                 14
Sector 53                                                     14
DLF Phase 5                                                   14
Gwal Pahari                                                   14
Sector 3                                                      14
Sector 1 Imt Manesar                                          14
Sector 76                                                     14
Laxman Vihar Phase 2                                          13
Sector 46                                                     13
Sector 36A                                                    13
Uppals Southend                                               12
Sector 93                                                     12
Sector 31                                                     12
Sector 50                                                     12
Sector 38                                                     12
Sohna Road                                                    12
Sector 39                                                     12
Ashok Vihar Phase 3 Extension                                 11
Sector 9A                                                     11
Sector 47                                                     11
Sector 1A IMT Manesar                                         10
Sector 7                                                      10
Ashok Vihar Phase 2                                            9
South City 1                                                   9
Sector 95A                                                     9
Sector 4                                                       9
Sector 55                                                      9
Malibu Town                                                    8
Sector 10A                                                     8
Sector 57                                                      8
Palam Vihar Extension                                          8
Sector 59                                                      8
Sector 89 A                                                    8
Sector 40                                                      8
Dwarka Expressway                                              8
Sector 43                                                      8
C Block Sushant Lok Phase 1                                    8
Mehrauli  Road                                                 8
New Colony                                                     7
Sector 26                                                      7
Mianwali Colony                                                7
Sector 36 Sohna                                                7
Surat Nagar 1                                                  7
sector 58                                                      7
Sector 51                                                      7
Sector 1                                                       6
Jyoti Park                                                     6
Ashok Vihar                                                    6
Sector 5                                                       6
Jacobpura                                                      6
Sector 11                                                      6
Rajiv Nagar                                                    6
Sector 23A                                                     5
Sector 30                                                      5
Chakkarpur                                                     5
Subhash Nagar                                                  5
Greenwood City                                                 5
Sector 105                                                     5
Sector 2                                                       5
New Palam Vihar                                                5
Sector 9                                                       5
Manesar                                                        5
Ansal Plaza                                                    5
Sector 80                                                      5
Saraswati Vihar                                                5
Dayanand Colony                                                5
Sector 28                                                      5
Sushant Lok Phase 2                                            5
Arjun Nagar                                                    5
Surya Vihar                                                    4
Valley View Estate                                             4
Sector 12A                                                     4
Bhim Nagar                                                     4
Vishnu Garden                                                  4
Shivpuri                                                       4
Devilal Colony                                                 4
Bhondsi                                                        4
Shivaji Nagar                                                  4
Adarsh Nagar                                                   4
Sector 6                                                       4
Krishna Colony                                                 4
Sector 36                                                      4
Sector 3A                                                      4
Ravi Nagar                                                     4
Sector 17                                                      4
Madanpuri                                                      4
Sector 12                                                      4
IMT Manesar                                                    4
Garhi Harsaru                                                  4
Baldev Nagar                                                   4
Dharam Colony                                                  4
New                                                            4
Suncity                                                        4
Sector 27                                                      3
A Block Sushant Lok Phase 1                                    3
B Block Sushant Lok Phase 1                                    3
Sector 17A                                                     3
Sector 15                                                      3
Maruti Kunj                                                    3
Gandhi Nagar                                                   3
Sector 73                                                      3
Patel Nagar                                                    3
Sector 110 A                                                   3
Sector 17B                                                     3
Sector 88B                                                     3
Sector 23                                                      3
MG Road                                                        3
Prem Nagar                                                     3
Sector 45                                                      3
Laxmi Garden                                                   3
Sector 8                                                       3
Sector-11 sohna                                                2
Sispal Vihar                                                   2
Lajpat Nagar                                                   2
Daulatabad                                                     2
Sector 15 Part 1                                               2
West Rajiv Nagar                                               2
Sector 15 Part 2                                               2
, Delhi NCR                                                    2
Shanti Nagar                                                   2
New Basti                                                      2
Rosewood                                                       2
Mayfield Garden                                                2
Bhawani Enclave                                                2
Nars                                                           2
Mohan Nagar                                                    2
Golf Course Road                                               2
New Palam Vihar Phase 1                                        2
Surat Nagar Phase 2                                            2
Farukhnagar                                                    2
Samaspur                                                       2
Block A Surya Vihar                                            2
Rajiv Chowk                                                    2
Sector 32                                                      2
Faridabad Road                                                 2
Shankar Vihar                                                  2
Pratap Nagar                                                   2
Sector 21                                                      2
Sohna  Road                                                    2
Sector 41                                                      2
Sector 24                                                      2
IFFCO Chowk                                                    2
Bissar                                                         2
Golf Course Ext Road                                           2
Surat Nagar                                                    2
Ambience Island                                                2
Hira Nagar                                                     2
Sector-2 Sohna                                                 2
Acharya Puri                                                   2
Sheetla Colony                                                 2
Shakti Nagar                                                   2
Manohar Nagar                                                  2
Sushant Lok                                                    2
New Palam Vihar Phase 2                                        2
laxmna vihar, phase 2                                          1
devi lal colony gali no 12 gurgaon nr omkar public school      1
Laxman Vihar, Railway Road,                                    1
Near Pataudi Chowk                                             1
Om Nagar                                                       1
Damdma                                                         1
HUDA Saraswati Vihar                                           1
Sector 17C                                                     1
Sector-7 Hous                                                  1
Rajiv Colony                                                   1
Civil L                                                        1
V Block DLF Phase 3                                            1
Sadar Bazar                                                    1
Heritage City                                                  1
Near Khandsa Road                                              1
South City                                                     1
Anand Garden, Sector-105                                       1
Sector 37B                                                     1
Block G Sector-57                                              1
Carterpuri Village                                             1
Shivji Park Colony                                             1
Sector 42                                                      1
saroop garden rajendra park                                    1
old delhi road, opp sector-14                                  1
Pataudi Road                                                   1
Cyber City                                                     1
ats marigold                                                   1
ravi nager basai road                                          1
near sector 1 market                                           1
URBAN ESTATE, SECTOR 5                                         1
Ashok Vihar Phase I                                            1
sector-5 sheetla colony                                        1
Ansal's Palam Vihar                                            1
Begampur Khatola                                               1
Ram Nagar                                                      1
Khandsa                                                        1
Kheri                                                          1
Sector 21A Faridabad                                           1
New Colony, Sector 7                                           1
Hno 13 Sagar enclave Sura                                      1
Sector-35 Sohna                                                1
Part 3 Sector 5                                                1
Dhankot                                                        1
Ashok Vihar Phase 3                                            1
near nand hospital                                             1
Sector 4 Urban Estate                                          1
Gopal Nagar, Garhi Ghasita, Sonipat                            1
B1 Block Sector 57                                             1
Kanahi                                                         1
Bhora Kalan                                                    1
New Jyoti Park                                                 1
BPTP                                                           1
Jacobpura Near Sadar Bazar                                     1
Saraswati Enclave                                              1
Vir Nagar                                                      1
Park View                                                      1
Bhimgarh Kheri Phase 3                                         1
Sector 37A                                                     1
Block H Ashok Vihar Phase III Extension                        1
Lucknow                                                        1
Sector 5 chowk                                                 1
Mahalaxmi Garden, Rajendra Place                               1
Alipur                                                         1
Sultanpur                                                      1
Jat Colony,Fazilpur/Taj Nagar Road                             1
Tekchand Nagar                                                 1
Hsiidc Plot Sector 1 Imt Manesar                               1
Sector 9B                                                      1
Sai Kunj                                                       1
Sec 3 Bhim Vihar Part 1 Bhimgher Kheri                         1
Sector-5 Sohna                                                 1
Mahavir pura                                                   1
Garauli Kalan                                                  1
Rattan Garden                                                  1
Near euro                                                      1
G block DLF City Phase 1                                       1
Sector 13                                                      1
Nirvana country Pocket H                                       1
Godrej Aria , sector 79 ,                                      1
Name: count, dtype: int64

In [71]:
df['sector']=df['sector'].str.lower()

In [72]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,1 BHK Flat in Sector 92 Gurgaon,flat,gls avenue,sector 92,0.21,6953.0,302.00,Carpet area: 302 (28.06 sq.m.),1,1,1,not available,"Sector 92 Gurgaon, Gurgaon, Haryana",0.0,South-East,1 to 5 Year Old,"['Yaduvanshi Shiksha Niketan Sector- 92', 'Aar...",Check out this 1 bhk apartment for sale in gls...,NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,4 BHK Flat in Gwal Pahari,flat,paras quartier,gwal pahari,5.90,11028.0,5350.00,Built Up area: 5350 (497.03 sq.m.),4,4,3+,not available,"Paras Quartier, Valley View Estate, Gwal Pahar...",0.0,NaN,5 to 10 Year Old,"['Sector 55-56 Metro Station', 'South point Ma...","New apartment, lush green aravalli valley 270 ...","['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,NaN
2,3 BHK Flat in Sector 1 Imt Manesar,flat,hsiidc sidco aravali,sector 1 imt manesar,0.90,3477.0,2588.40,Super Built up area 2588(240.43 sq.m.)Built Up...,3,3,3+,Servant Room,"Sector 1 Imt Manesar, Gurgaon, Haryana",8.0,East,5 to 10 Year Old,"['Pooja Clinic', 'Dr. Sahil Clinic', 'Prakash ...",Arawali sipco sec-1 imt manesar good property ...,"['6 Fan', '6 Light', 'No AC', 'No Bed', 'No Ch...","['Lift(s)', 'Maintenance Staff', 'Park', 'Pipe...","['Environment5 out of 5', 'Lifestyle4.5 out of..."
3,5 Bedroom House for sale in Sector 15 Gurgaon,house,sector 15 part 2 rwa,sector 15,10.00,22222.0,4520.84,Plot area 502(419.74 sq.m.),5,5,2,not available,"Sector 15 Gurgaon, Gurgaon, Haryana",2.0,East,10+ Year Old,"['Hanuman Mandir', 'State bank of india ATM', ...","Gated community and near market,school and hig...",[],"['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4.5 out of 5', 'Lifestyle4 out of..."
4,2 BHK Flat in Sohna,flat,eldeco accolade,sohna,0.72,4975.0,1447.20,Super Built up area 1457(135.36 sq.m.)Carpet a...,2,2,3+,Study Room,"0001, Sohna, Gurgaon, Haryana",12.0,East,1 to 5 Year Old,"['Global City Centre', 'Sohna Road', 'Damdama ...","Eldeco accolade in sohna, gurgaon is a ready-T...",NaN,"['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction4.5 out ..."

In [73]:
df['sector'].value_counts()

sector
sohna                                                        163
sector 102                                                   113
sector 85                                                    110
sector 92                                                    104
sector 69                                                     94
sector 90                                                     90
sector 65                                                     90
sector 81                                                     90
sector 109                                                    88
sector 79                                                     80
sector 83                                                     69
sector 37d                                                    68
sector 86                                                     67
sector 104                                                    66
sector 107                                                    60
sector 108                                                    58
sector 95                                                     57
sector 56                                                     57
sector 89                                                     56
sector 48                                                     56
sector 70a                                                    54
sector 70                                                     53
sector 37c                                                    53
nirvana country                                               52
sector 84                                                     51
sector-33 sohna                                               51
palam vihar                                                   50
sector 67                                                     48
sector 103                                                    45
dlf phase 1                                                   43
sector 113                                                    43
sector 82                                                     42
sector 66                                                     42
sector 61                                                     42
dlf phase 2                                                   41
sector 106                                                    38
sector 49                                                     36
sector 99a                                                    32
sushant lok phase 1                                           31
sector 68                                                     30
sector 77                                                     29
sector 72                                                     29
sector 54                                                     27
sector 71                                                     27
laxman vihar                                                  26
dlf phase 4                                                   25
sector 112                                                    24
sector 88a                                                    23
sector 111                                                    22
sector 67a                                                    22
dlf phase 3                                                   21
sector 22                                                     20
sector 33                                                     20
sector 82a                                                    20
sector 78                                                     19
sector 63a                                                    18
sector 74                                                     18
sector 91                                                     17
sector 62                                                     17
sushant lok phase 3                                           16
sector 110                                                    16
sector 99                                                     16
sector 14                                                     15
sector 63                                                     15
sector 60                                                     15
sector 52                                                     14
rajendra park                                                 14
sector 53                                                     14
dlf phase 5                                                   14
gwal pahari                                                   14
sector 3                                                      14
sector 1 imt manesar                                          14
sector 76                                                     14
laxman vihar phase 2                                          13
sector 46                                                     13
sector 36a                                                    13
uppals southend                                               12
sector 93                                                     12
sector 31                                                     12
sector 50                                                     12
sector 38                                                     12
sohna road                                                    12
sector 39                                                     12
ashok vihar phase 3 extension                                 11
sector 9a                                                     11
sector 47                                                     11
sector 1a imt manesar                                         10
sector 7                                                      10
ashok vihar phase 2                                            9
south city 1                                                   9
sector 95a                                                     9
sector 4                                                       9
sector 55                                                      9
malibu town                                                    8
sector 10a                                                     8
sector 57                                                      8
palam vihar extension                                          8
sector 59                                                      8
sector 89 a                                                    8
sector 40                                                      8
dwarka expressway                                              8
sector 43                                                      8
c block sushant lok phase 1                                    8
mehrauli  road                                                 8
new colony                                                     7
sector 26                                                      7
mianwali colony                                                7
sector 36 sohna                                                7
surat nagar 1                                                  7
sector 58                                                      7
sector 51                                                      7
sector 1                                                       6
jyoti park                                                     6
ashok vihar                                                    6
sector 5                                                       6
jacobpura                                                      6
sector 11                                                      6
rajiv nagar                                                    6
sector 23a                                                     5
sector 30                                                      5
chakkarpur                                                     5
subhash nagar                                                  5
greenwood city                                                 5
sector 105                                                     5
sector 2                                                       5
new palam vihar                                                5
sector 9                                                       5
manesar                                                        5
ansal plaza                                                    5
sector 80                                                      5
saraswati vihar                                                5
dayanand colony                                                5
sector 28                                                      5
sushant lok phase 2                                            5
arjun nagar                                                    5
surya vihar                                                    4
valley view estate                                             4
sector 12a                                                     4
bhim nagar                                                     4
vishnu garden                                                  4
shivpuri                                                       4
devilal colony                                                 4
bhondsi                                                        4
shivaji nagar                                                  4
adarsh nagar                                                   4
sector 6                                                       4
krishna colony                                                 4
sector 36                                                      4
sector 3a                                                      4
ravi nagar                                                     4
sector 17                                                      4
madanpuri                                                      4
sector 12                                                      4
imt manesar                                                    4
garhi harsaru                                                  4
baldev nagar                                                   4
dharam colony                                                  4
new                                                            4
suncity                                                        4
sector 27                                                      3
a block sushant lok phase 1                                    3
b block sushant lok phase 1                                    3
sector 17a                                                     3
sector 15                                                      3
maruti kunj                                                    3
gandhi nagar                                                   3
sector 73                                                      3
patel nagar                                                    3
sector 110 a                                                   3
sector 17b                                                     3
sector 88b                                                     3
sector 23                                                      3
mg road                                                        3
prem nagar                                                     3
sector 45                                                      3
laxmi garden                                                   3
sector 8                                                       3
sector-11 sohna                                                2
sispal vihar                                                   2
lajpat nagar                                                   2
daulatabad                                                     2
sector 15 part 1                                               2
west rajiv nagar                                               2
sector 15 part 2                                               2
, delhi ncr                                                    2
shanti nagar                                                   2
new basti                                                      2
rosewood                                                       2
mayfield garden                                                2
bhawani enclave                                                2
nars                                                           2
mohan nagar                                                    2
golf course road                                               2
new palam vihar phase 1                                        2
surat nagar phase 2                                            2
farukhnagar                                                    2
samaspur                                                       2
block a surya vihar                                            2
rajiv chowk                                                    2
sector 32                                                      2
faridabad road                                                 2
shankar vihar                                                  2
pratap nagar                                                   2
sector 21                                                      2
sohna  road                                                    2
sector 41                                                      2
sector 24                                                      2
iffco chowk                                                    2
bissar                                                         2
golf course ext road                                           2
surat nagar                                                    2
ambience island                                                2
hira nagar                                                     2
sector-2 sohna                                                 2
acharya puri                                                   2
sheetla colony                                                 2
shakti nagar                                                   2
manohar nagar                                                  2
sushant lok                                                    2
new palam vihar phase 2                                        2
laxmna vihar, phase 2                                          1
devi lal colony gali no 12 gurgaon nr omkar public school      1
laxman vihar, railway road,                                    1
near pataudi chowk                                             1
om nagar                                                       1
damdma                                                         1
huda saraswati vihar                                           1
sector 17c                                                     1
sector-7 hous                                                  1
rajiv colony                                                   1
civil l                                                        1
v block dlf phase 3                                            1
sadar bazar                                                    1
heritage city                                                  1
near khandsa road                                              1
south city                                                     1
anand garden, sector-105                                       1
sector 37b                                                     1
block g sector-57                                              1
carterpuri village                                             1
shivji park colony                                             1
sector 42                                                      1
saroop garden rajendra park                                    1
old delhi road, opp sector-14                                  1
pataudi road                                                   1
cyber city                                                     1
ats marigold                                                   1
ravi nager basai road                                          1
near sector 1 market                                           1
urban estate, sector 5                                         1
ashok vihar phase i                                            1
sector-5 sheetla colony                                        1
ansal's palam vihar                                            1
begampur khatola                                               1
ram nagar                                                      1
khandsa                                                        1
kheri                                                          1
sector 21a faridabad                                           1
new colony, sector 7                                           1
hno 13 sagar enclave sura                                      1
sector-35 sohna                                                1
part 3 sector 5                                                1
dhankot                                                        1
ashok vihar phase 3                                            1
near nand hospital                                             1
sector 4 urban estate                                          1
gopal nagar, garhi ghasita, sonipat                            1
b1 block sector 57                                             1
kanahi                                                         1
bhora kalan                                                    1
new jyoti park                                                 1
bptp                                                           1
jacobpura near sadar bazar                                     1
saraswati enclave                                              1
vir nagar                                                      1
park view                                                      1
bhimgarh kheri phase 3                                         1
sector 37a                                                     1
block h ashok vihar phase iii extension                        1
lucknow                                                        1
sector 5 chowk                                                 1
mahalaxmi garden, rajendra place                               1
alipur                                                         1
sultanpur                                                      1
jat colony,fazilpur/taj nagar road                             1
tekchand nagar                                                 1
hsiidc plot sector 1 imt manesar                               1
sector 9b                                                      1
sai kunj                                                       1
sec 3 bhim vihar part 1 bhimgher kheri                         1
sector-5 sohna                                                 1
mahavir pura                                                   1
garauli kalan                                                  1
rattan garden                                                  1
near euro                                                      1
g block dlf city phase 1                                       1
sector 13                                                      1
nirvana country pocket h                                       1
godrej aria , sector 79 ,                                      1
Name: count, dtype: int64

In [74]:
df['sector'] = df['sector'].str.replace('dharam colony','sector 12')
df['sector'] = df['sector'].str.replace('krishna colony','sector 7')
df['sector'] = df['sector'].str.replace('suncity','sector 54')
df['sector'] = df['sector'].str.replace('prem nagar','sector 13')
df['sector'] = df['sector'].str.replace('mg road','sector 28')
df['sector'] = df['sector'].str.replace('gandhi nagar','sector 28')
df['sector'] = df['sector'].str.replace('laxmi garden','sector 11')
df['sector'] = df['sector'].str.replace('shakti nagar','sector 11')

In [75]:
df['sector'] = df['sector'].str.replace('baldev nagar','sector 7')
df['sector'] = df['sector'].str.replace('shivpuri','sector 7')
df['sector'] = df['sector'].str.replace('garhi harsaru','sector 17')
df['sector'] = df['sector'].str.replace('imt manesar','manesar')
df['sector'] = df['sector'].str.replace('adarsh nagar','sector 12')
df['sector'] = df['sector'].str.replace('shivaji nagar','sector 11')
df['sector'] = df['sector'].str.replace('bhim nagar','sector 6')
df['sector'] = df['sector'].str.replace('madanpuri','sector 7')

In [76]:
df['sector'] = df['sector'].str.replace('saraswati vihar','sector 28')
df['sector'] = df['sector'].str.replace('arjun nagar','sector 8')
df['sector'] = df['sector'].str.replace('ravi nagar','sector 9')
df['sector'] = df['sector'].str.replace('vishnu garden','sector 105')
df['sector'] = df['sector'].str.replace('bhondsi','sector 11')
df['sector'] = df['sector'].str.replace('surya vihar','sector 21')
df['sector'] = df['sector'].str.replace('devilal colony','sector 9')
df['sector'] = df['sector'].str.replace('valley view estate','gwal pahari')

In [77]:
df['sector'] = df['sector'].str.replace('mehrauli  road','sector 14')
df['sector'] = df['sector'].str.replace('jyoti park','sector 7')
df['sector'] = df['sector'].str.replace('ansal plaza','sector 23')
df['sector'] = df['sector'].str.replace('dayanand colony','sector 6')
df['sector'] = df['sector'].str.replace('sushant lok phase 2','sector 55')
df['sector'] = df['sector'].str.replace('chakkarpur','sector 28')
df['sector'] = df['sector'].str.replace('greenwood city','sector 45')
df['sector'] = df['sector'].str.replace('subhash nagar','sector 12')

In [78]:
df['sector'] = df['sector'].str.replace('sohna road road','sohna road')
df['sector'] = df['sector'].str.replace('malibu town','sector 47')
df['sector'] = df['sector'].str.replace('surat nagar 1','sector 104')
df['sector'] = df['sector'].str.replace('new colony','sector 7')
df['sector'] = df['sector'].str.replace('mianwali colony','sector 12')
df['sector'] = df['sector'].str.replace('jacobpura','sector 12')
df['sector'] = df['sector'].str.replace('rajiv nagar','sector 13')
df['sector'] = df['sector'].str.replace('ashok vihar','sector 3')

In [79]:
df['sector'] = df['sector'].str.replace('sushant lok phase 3','sector 57')
df['sector'] = df['sector'].str.replace('dlf phase 5','sector 43')
df['sector'] = df['sector'].str.replace('rajendra park','sector 105')
df['sector'] = df['sector'].str.replace('uppals southend','sector 49')
df['sector'] = df['sector'].str.replace('sohna','sohna road')
df['sector'] = df['sector'].str.replace('ashok vihar phase 3 extension','sector 5')
df['sector'] = df['sector'].str.replace('south city 1','sector 41')
df['sector'] = df['sector'].str.replace('ashok vihar phase 2','sector 5')
df['sector'] = df['sector'].str.replace('dlf phase 1','sector 26')
df['sector'] = df['sector'].str.replace('nirvana country','sector 50')
df['sector'] = df['sector'].str.replace('palam vihar','sector 2')
df['sector'] = df['sector'].str.replace('dlf phase 2','sector 25')
df['sector'] = df['sector'].str.replace('sushant lok phase 1','sector 43')
df['sector'] = df['sector'].str.replace('laxman vihar','sector 4')
df['sector'] = df['sector'].str.replace('dlf phase 4','sector 28')
df['sector'] = df['sector'].str.replace('dlf phase 3','sector 24')
df['sector'] = df['sector'].str.replace('sector 95a','sector 95')
df['sector'] = df['sector'].str.replace('sector 23a','sector 23')
df['sector'] = df['sector'].str.replace('sector 12a','sector 12')
df['sector'] = df['sector'].str.replace('sector 3a','sector 3')
df['sector'] = df['sector'].str.replace('sector 110 a','sector 110')
df['sector'] = df['sector'].str.replace('patel nagar','sector 15')
df['sector'] = df['sector'].str.replace('a block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('maruti kunj','sector 12')
df['sector'] = df['sector'].str.replace('b block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('sector-33 sohna road','sector 33')
df['sector'] = df['sector'].str.replace('sector 1 manesar','manesar')
df['sector'] = df['sector'].str.replace('sector 4 phase 2','sector 4')
df['sector'] = df['sector'].str.replace('sector 1a manesar','manesar')
df['sector'] = df['sector'].str.replace('c block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('sector 89 a','sector 89')
df['sector'] = df['sector'].str.replace('sector 2 extension','sector 2')
df['sector'] = df['sector'].str.replace('sector 36 sohna road','sector 36')
df['sector']=df['sector'].str.replace('hsiidc plot manesar','sector 1')

In [80]:
df[~df['sector'].str.contains('sector')]['sector'].shape

(342,)

In [81]:
df[df['sector'].str.contains('sector')]['sector'].shape

(3600,)

In [82]:
df[~df['sector'].str.contains('sector')]['sector']

1                                             gwal pahari
2                                                 manesar
4                                              sohna road
9                                             gwal pahari
44                                                manesar
50                                        sohna road road
51                                       sohna road  road
77                                             sohna road
112                                bhimgarh kheri phase 3
123                   gopal nagar, garhi ghasita, sonipat
130                                            sohna road
146                                               manesar
147                                               manesar
161                                          acharya puri
172                                            sohna road
182                                            sohna road
187                                            hira nagar
197                                               manesar
203                                     dwarka expressway
217                                             park view
222                                            sohna road
229                                            sohna road
242                                            sohna road
244                                            sohna road
257                                             vir nagar
283                                            sohna road
309                                            sohna road
310                                               manesar
313                                            sohna road
326                                            sohna road
329                                     saraswati enclave
333                                                  bptp
336                                        faridabad road
346                                       sohna road road
360                                         shankar vihar
368                                     dwarka expressway
378                                          pratap nagar
416                                            sohna road
451                                       sohna road road
453                                           bhora kalan
464                                     dwarka expressway
482                                            sohna road
484                                            sohna road
504                                                   new
505                                            sohna road
509                                            sohna road
538                                            sohna road
545                                           iffco chowk
554                                                bissar
587                                            sohna road
589                                  golf course ext road
606                                            sohna road
609                                               manesar
622                                               manesar
625                                            sohna road
627                                           surat nagar
635                                            sohna road
656                                       ambience island
676                                            sohna road
685                                           rajiv chowk
731                                                   new
746                                           sushant lok
750                                           gwal pahari
754                                        faridabad road
760                                            sohna road
778                                            sohna road
785                                            sohna road
799                                            sohna road
803                                            sohna road
823                                           gwal pahari
826                                               manesar
828                                            sohna road
846                                           gwal pahari
852                                            sohna road
865                                           gwal pahari
868                                            sohna road
916                                            sohna road
928                                            sohna road
936                                              samaspur
938                                         manohar nagar
939                                        sheetla colony
968                                            sohna road
970                                                 kheri
980                                            sohna road
1007                                           sohna road
1027                                          gwal pahari
1034                                           sohna road
1057                                              manesar
1071                                           sohna road
1090                                   near nand hospital
1111                                           sohna road
1149                                              dhankot
1151                                           sohna road
1191                                         lajpat nagar
1195                                           sohna road
1214                                              manesar
1265                                          gwal pahari
1302                                           sohna road
1311                                           sohna road
1337                            hno 13 sagar enclave sura
1339                                           sohna road
1343                                           sohna road
1354                                           sohna road
1393                                  surat nagar phase 2
1426                                           sohna road
1427                                              manesar
1434                                           sohna road
1457                                           sohna road
1463                                              manesar
1475                                           sohna road
1505                                        manohar nagar
1512                                         sispal vihar
1529                                              manesar
1530                                              lucknow
1548                                           sohna road
1577                                           sohna road
1587                                          , delhi ncr
1605                                           sohna road
1611                                           sohna road
1667                                           sohna road
1673                             g block dlf city phase 1
1696                                          farukhnagar
1708                                            near euro
1712                                          gwal pahari
1718                                           sohna road
1722                                        rattan garden
1735                                           sohna road
1746                                                 nars
1761                                      sohna road road
1767                                        garauli kalan
1768                                         mahavir pura
1793                                           sohna road
1813                                          mohan nagar
1833                                           sohna road
1846                                           sohna road
1872                                           sohna road
1896                                       sheetla colony
1899                                           sohna road
1900                                           sohna road
1920                                              manesar
1922                                           sohna road
1930                                            new basti
1937                                          gwal pahari
1939               sec 3 bhim vihar part 1 bhimgher kheri
1949                                          , delhi ncr
1956                                             sai kunj
1971                                      sohna road road
1982                                           sohna road
1987                                           sohna road
1989                                           sohna road
1994                                           sohna road
2012                                           sohna road
2021                                     golf course road
2036                                      bhawani enclave
2093                                              manesar
2103                                           sohna road
2113                                       tekchand nagar
2116                                             rosewood
2125                   jat colony,fazilpur/taj nagar road
2126                                            sultanpur
2131                                           sohna road
2157                                           sohna road
2162                                          gwal pahari
2164                                          farukhnagar
2194                                               alipur
2196                                           sohna road
2212                                           sohna road
2219                                           sohna road
2243                                              manesar
2246                                           sohna road
2259                                    dwarka expressway
2261                                           sohna road
2269                                           sohna road
2271                                           sohna road
2306                                               kanahi
2314                                           sohna road
2324                                            ram nagar
2325                                           sohna road
2336                                           sohna road
2337                                              manesar
2346                                              manesar
2354                                      sohna road road
2384                                           sohna road
2398                                              khandsa
2400                                           sohna road
2404                                           sohna road
2416                                           sohna road
2418                                           sohna road
2429                                           sohna road
2433                                                 nars
2481                                           south city
2482                                           daulatabad
2490                                           sohna road
2495                                      sohna road road
2496                                           sohna road
2501                                           sohna road
2503                                           sohna road
2509                                              civil l
2514                                           sohna road
2515                                           sohna road
2519                                           sohna road
2521                                         lajpat nagar
2530                                           sohna road
2538                                         shanti nagar
2544                                           sohna road
2552                                           sohna road
2581                                      mayfield garden
2584                                      sohna road road
2600                                           sohna road
2607                                             om nagar
2614                                           sohna road
2639                                           sohna road
2644                                           sohna road
2651                                           sohna road
2657                                           sohna road
2665                                      sohna road road
2671                                    dwarka expressway
2701                                           sohna road
2717                                           sohna road
2722                                           sohna road
2724                                           sohna road
2731                                     begampur khatola
2732                                           sohna road
2761                                              manesar
2771                                           sohna road
2775                                           sohna road
2784                                              manesar
2798                                          gwal pahari
2799                                              manesar
2835                                ravi nager basai road
2855                                           sohna road
2872                                           sohna road
2875                                              manesar
2894                                           sohna road
2895                                             rosewood
2898                                           daulatabad
2915                                           sohna road
2919                                           sohna road
2922                                         ats marigold
2925                                           sohna road
2926                                          surat nagar
2930                                         pataudi road
2976                                              manesar
2982                                           sohna road
2989                                           sohna road
2993                                           sohna road
3000                                              manesar
3006                                   shivji park colony
3015                                           sohna road
3022                                          iffco chowk
3042                                           sohna road
3047                                laxmna vihar, phase 2
3051                                           sohna road
3052                                           sohna road
3067                                           sohna road
3074                                      sohna road road
3084                                           sohna road
3088                                           sohna road
3102                                          sushant lok
3110                                           sohna road
3120                                         sispal vihar
3134                                           sohna road
3154                                           sohna road
3158                                           sohna road
3166                                              manesar
3167                                              manesar
3177                                           sohna road
3178                                           sohna road
3202                                           sohna road
3203                                                  new
3219                                           hira nagar
3223                                           sohna road
3230                                           sohna road
3251                                              manesar
3260                                              manesar
3265                                      sohna road road
3267                                          mohan nagar
3282                                        shankar vihar
3285                                              manesar
3297                                           sohna road
3298                                           sohna road
3312                                           sohna road
3324                                               bissar
3340                                              manesar
3343                                    near khandsa road
3376                                     sohna road  road
3379                                           sohna road
3383                                          gwal pahari
3389                                         rajiv colony
3400                                          gwal pahari
3429                                           sohna road
3433                                      bhawani enclave
3474                                            new basti
3477                                              manesar
3481                                  surat nagar phase 2
3499                                    dwarka expressway
3504                                           sohna road
3507                                           sohna road
3519                                           sohna road
3522                                         acharya puri
3541                                           sohna road
3557                                              manesar
3573                                          gwal pahari
3579                                           cyber city
3580                                 golf course ext road
3584                                           sohna road
3602                                           sohna road
3604                                   carterpuri village
3607                                         shanti nagar
3609                                      mayfield garden
3626                                          gwal pahari
3628    devi lal colony gali no 12 gurgaon nr omkar pu...
3629                                           sohna road
3630                                      ambience island
3632                                           sohna road
3635                                      sohna road road
3637                                         pratap nagar
3640                                           sohna road
3659                                           sohna road
3672                                     golf course road
3675                                           sohna road
3677                                           sohna road
3697                                          sadar bazar
3710                                           sohna road
3722                                        heritage city
3728                                          gwal pahari
3730                                    dwarka expressway
3746                                             samaspur
3750                                               damdma
3761                                           sohna road
3779                                    dwarka expressway
3816                                   near pataudi chowk
3826                                           sohna road
3832                                           sohna road
3835                                                  new
3842                                           sohna road
3847                                          rajiv chowk
3849                                           sohna road
3899                                           sohna road
3908                                           sohna road
3920                                           sohna road
3924                                          gwal pahari
Name: sector, dtype: object

In [83]:
import re

def normalize(text):
    text = str(text).lower()

    # remove duplicate words: "road road"
    text = re.sub(r'\b(\w+)\s+\1\b', r'\1', text)

    # remove punctuation
    text = re.sub(r'[^a-z0-9\s]', ' ', text)

    # remove extra spaces
    text = re.sub(r'\s+', ' ', text).strip()

    return text

df["sector"] = df["sector"].apply(normalize)

In [84]:
sector_map = {
    "sohna road": 48,
    "iffco chowk": 29,
    "manesar": 1,
    "nars": -1,
    "surat nagar": 104,
    "near pataudi chowk": 10,
    "mohan nagar": 5,
    "alipur": 110,
    "patel nagar": 15,
    "mahavir pura": 4,
    "dwarka expressway": 106,
    "faridabad road": 56,
    "hira nagar": 7,
    "rajiv colony": 33,
    "near khandsa road": 37,
    "gwal pahari": 59,
    "carterpuri village": 23,
    "shankar vihar": 110,
    "ravi nager basai road": 9,
    ", delhi ncr": -1,
    "garauli kalan": 68,
    "near nand hospital": 15,
    "samaspur": 37,
    "farukhnagar": 2,
    "tekchand nagar": 12,
    "bissar": 9,
    "bhawani enclave": 9,
    "g block dlf city phase 1": 26,
    "shanti nagar": 11,
    "begampur khatola": 38,
    "daulatabad": 104,
    "vir nagar": 11,
    "ats marigold": 89,
    "manohar nagar": 11,
    "ambience island": 24,
    "lucknow": -1,
    "bptp": 102,
    "new basti": 7,
    "civil l": 12,
    "saraswati enclave": 10,
    "heritage city": 25,
    "sispal vihar": 49,
    "bhora kalan": 81,
    "rajiv chowk": 33,
    "lajpat nagar": 12,
    "shivji park colony": 10,
    "pataudi road": 10,
    "park view": 48,
    "maruti kunj": 9,
    "bhimgarh kheri": 3,
    "acharya puri": 4,
    "damdma": 68,
    "ram nagar": 4,
    "south city": 41,
    "rattan garden": 7,
    "cyber city": 24,
    "om nagar": 11,
    "sheetla colony": 5,
    "sultanpur": 57,
    "khandsa": 37,
    "pratap nagar": 8,
    "sai kunj": 83,
    "kheri": 3,
    "sadar bazar": 12,
    "kanahi": 35,
    "dhankot": 102,
    "laxmna vihar phase 2": 4,
    "sushant lok": 43,
    "sonipat (garhi ghasita)": -1,
    "new": -1,
    "delhi ncr": -1,
    "devi lal colony gali no 12 gurgaon nr omkar public school": 9,
    "golf course ext road": 65,
    "surat nagar phase 2": 104,
    "gopal nagar garhi ghasita sonipat": -1,
    "hno 13 sagar enclave sura": 3,
    "mayfield garden": 51,
    "sec 3 bhim vihar part 1 bhimgher kheri": 3,
    "bhimgarh kheri phase 3": 3,
    "near euro": 47,
    "golf course road": 54,
    "jat colony fazilpur taj nagar road": 10,
    "rosewood": 49
}

In [85]:
def fill_sector(text):
    if pd.isna(text):
        return text
    text_l=text.lower().strip()
    if 'sector' in text_l:
        return text_l
    if text_l in sector_map.keys():
        return 'sector '+ str(sector_map[text])
    return text_l

In [86]:
mask=df[~df['sector'].str.contains('sector')]['sector'].apply(fill_sector)

In [87]:
df.loc[mask.index,'sector']=mask

In [88]:
mask.index

Index([   1,    2,    4,    9,   44,   50,   51,   77,  112,  123,
       ...
       3826, 3832, 3835, 3842, 3847, 3849, 3899, 3908, 3920, 3924],
      dtype='int64', length=342)

In [89]:
df[~df['sector'].str.contains('sector')]['sector'].shape

(0,)

In [90]:
df[~df['sector'].str.contains('sector')]['sector']

Series([], Name: sector, dtype: object)

In [91]:
df['sector']

0                                  sector 92
1                                  sector 59
2                                   sector 1
3                                  sector 15
4                                  sector 48
5                                  sector 25
6                                 sector 99a
7                                  sector 82
8                                  sector 11
9                                  sector 59
10                                 sector 69
11                                 sector 62
12                                sector 112
13                                 sector 65
14                                sector 82a
15                                 sector 65
16                                 sector 81
17                                 sector 85
18                                 sector 82
19                                 sector 70
20                                 sector 48
21                                  sector 7
22                                sector 82a
23                                 sector 95
24                                sector 88a
25                                 sector 92
26                                sector 37d
27                                 sector 81
28                                sector 37d
29                                 sector 36
30                                 sector 28
31                                 sector 92
32                                 sector 30
33                                sector 109
34                                 sector 89
35                                sector 102
36                                 sector 9a
37                                 sector 56
38                                 sector 28
39                                 sector 26
40                                 sector 79
41                                 sector 70
42                                 sector 62
43                                 sector 14
44                                  sector 1
45                                 sector 67
46                                sector 102
47                                 sector 85
48                                 sector 25
49                                 sector 39
50                                 sector 48
51                                 sector 48
52                                sector 108
53                                 sector 65
54                                 sector 72
55                                sector 37d
56                                 sector 84
57                                 sector 92
58                                sector 70a
59                                 sector 91
60                                 sector 24
61                                 sector 79
62                                sector 111
63                                 sector 22
64                                sector 67a
65                                 sector 79
66                                 sector 71
67                                 sector 54
68                                 sector 68
69                                 sector 76
70                                 sector 69
71                                sector 102
72                                 sector 65
73                                 sector 57
74                                sector 113
75                                 sector 45
76                                 sector 33
77                                 sector 48
78                                sector 109
79                                  sector 2
80                                 sector 25
81                                sector 37d
82                                 sector 33
83                                 sector 90
84                                 sector 90
85                                sector 104
86                                 sector 85
87                                sector 108
88                                 sector 12
89                                sector 88a
90                                sector 37c
91                                 sector 90
92                                 sector 86
93                                 sector 13
94                                sector 110
95                                 sector 86
96                                 sector 69
97                                 sector 65
98                                 sector 38
99                                 sector 22
100                                sector 83
101                                sector 69
102                                sector 36
103                                sector 66
104                                sector 50
105                                sector 61
106                                sector 65
107                                sector 53
108                               sector 109
109                                sector 67
110                                sector 95
111                                sector 63
112                                 sector 3
113                               sector 102
114                                sector 25
115                                sector 84
116                                sector 95
117                                sector 33
118                                sector 49
119                               sector 70a
120                                sector 89
121                                 sector 7
122                               sector 63a
123                                sector -1
124                               sector 113
125                                 sector 2
126                                sector 70
127                                sector 65
128                                sector 67
129                                sector 30
130                                sector 48
131                               sector 102
132                                sector 90
133                               sector 88a
134                                sector 95
135                               sector 109
136                               sector 10a
137                                sector 43
138                                sector 63
139                                sector 85
140                                sector 81
141                                sector 50
142                                sector 28
143               sector 3 phase 3 extension
144                                sector 61
145                                sector 92
146                                 sector 1
147                                 sector 1
148                                sector 93
149                                sector 13
150                                sector 43
151                                sector 78
152                                sector 70
153                                sector 63
154                                sector 77
155                                sector 54
156                               sector 107
157                                sector 83
158                                sector 85
159                               sector 67a
160                                sector 85
161                                 sector 4
162                                sector 43
163                               sector 10a
164                                sector 72
165                                 sector 2
166                                 sector 9
167                                sector 79
168                                sector 72
169                                sector 69
170                               sector 67a
171                                sector 57
172                                sector 48
173                                sector 92
174                               sector 102
175                                 sector 7
176                                sector 63
177                                sector 50
178                                sector 57
179                                sector 82
180                                sector 71
181                                sector 77
182                                sector 48
183                               sector 109
184                                sector 54
185                                sector 85
186                               sector 102
187                                 sector 7
188                                sector 95
189                                sector 65
190                                sector 67
191                                sector 82
192                                sector 68
193                                sector 67
194                                sector 85
195                               sector 113
196                               sector 105
197                                 sector 1
198                                sector 66
199                                sector 92
200                                sector 99
201                                sector 90
202                                sector 46
203                               sector 106
204                                 sector 2
205                                sector 62
206                                sector 22
207                                sector 89
208                                sector 72
209                                sector 25
210                                sector 90
211                                sector 26
212                               sector 109
213                                sector 56
214                                sector 9a
215                                sector 68
216                               sector 88a
217                                sector 48
218                                sector 99
219                                sector 81
220                                sector 72
221                                sector 43
222                                sector 48
223                                sector 39
224                                sector 41
225                               sector 70a
226                                sector 67
227                                 sector 2
228                               sector 36a
229                                sector 48
230                                sector 71
231                               sector 37d
232                                sector 83
233                                sector 89
234                                sector 28
235                                sector 46
236                               sector 107
237                                sector 90
238                               sector 70a
239                                sector 47
240                                sector 90
241                               sector 104
242                                sector 48
243                               sector 108
244                                sector 48
245                                sector 43
246                               sector 103
247                                 sector 4
248                                sector 48
249                                 sector 4
250                                sector 49
251                               sector 37c
252                                sector 46
253                                sector 84
254                                sector 82
255                                sector 74
256                                sector 84
257                                sector 11
258                                sector 84
259                                sector 82
260                                 sector 4
261                                sector 65
262                               sector 111
263                                sector 90
264                                sector 86
265                               sector 102
266                               sector 110
267                                 sector 7
268                                sector 74
269                                sector 71
270                                sector 55
271                                sector 78
272                                sector 70
273                               sector 102
274                                sector 32
275                               sector 109
276                                sector 86
277                                sector 81
278                                 sector 6
279                                sector 38
280                                sector 79
281                                sector 77
282                                sector 74
283                                sector 48
284                                sector 90
285                                sector 48
286                                sector 85
287                               sector 109
288                                sector 51
289                                sector 92
290                                sector 89
291                               sector 102
292                                sector 89
293                                sector 86
294                                sector 48
295                                sector 48
296                               sector 67a
297                                sector 73
298                                 sector 4
299                                sector 23
300                                sector 85
301                                sector 56
302                               sector 106
303                                sector 70
304                                sector 81
305                                sector 95
306                                sector 89
307                                sector 85
308                                sector 67
309                                sector 48
310                                 sector 1
311                                sector 52
312                                sector 83
313                                sector 48
314                               sector 37c
315                                sector 26
316                                sector 12
317                                sector 92
318                                sector 89
319                                sector 69
320                               sector 102
321                                 sector 4
322                                sector 82
323                                sector 86
324                                sector 61
325                               sector 109
326                                sector 48
327                                sector 59
328                               sector 37c
329                                sector 10
330                               sector 108
331                                 sector 2
332               sector 12 near sadar bazar
333                               sector 102
334                                sector 56
335                                sector 56
336                                sector 56
337                                sector 13
338                                sector 68
339                                sector 85
340                                sector 80
341                               sector 107
342                                sector 66
343                                sector 85
344                                sector 85
345                                 sector 3
346                                sector 48
347                                sector 89
348                               sector 102
349                               sector 113
350                               sector 113
351                                 sector 3
352                                sector 83
353                                sector 93
354                                sector 99
355                                sector 91
356                                sector 69
357                               sector 107
358                                sector 33
359                                sector 50
360                               sector 110
361                                sector 79
362                                sector 45
363                                sector 50
364                                sector 26
365                                sector 61
366                                sector 61
367                               sector 108
368                               sector 106
369                                sector 68
370                                sector 86
371                               sector 37d
372                                sector 26
373                                sector 79
374                                sector 95
375                               sector 107
376                                sector 71
377                                sector 40
378                                 sector 8
379                               sector 108
380                                sector 28
381                                sector 74
382                                sector 33
383                                sector 86
384                                sector 9a
385                               sector 102
386                               sector 103
387                                sector 89
388                               sector 106
389                                sector 33
390                                sector 65
391                                sector 81
392                                sector 50
393                               sector 88a
394                               sector 109
395                                sector 25
396                                sector 48
397                               sector 99a
398                                sector 81
399                                sector 71
400                                 sector 7
401                                sector 85
402                                sector 71
403                                sector 26
404                                sector 26
405                                sector 23
406                                sector 89
407                               sector 103
408                                sector 54
409                                sector 47
410                                sector 85
411                                sector 86
412                                 sector 2
413                                sector 21
414                               sector 17a
415                                sector 83
416                                sector 48
417                                sector 69
418                                sector 56
419                                sector 43
420                                sector 47
421                                sector 89
422                                sector 56
423                                sector 89
424                                sector 33
425                                sector 54
426                               sector 37c
427                             new sector 7
428                                sector 65
429                                sector 57
430                                sector 79
431                                sector 72
432                               sector 108
433                               sector 102
434                                sector 90
435                                sector 90
436                                sector 66
437                                sector 56
438                                sector 79
439                                sector 81
440                                 sector 7
441                                sector 69
442                                sector 53
443                                sector 33

In [92]:
df['sector'].value_counts()

sector
sector 48                               234
sector 102                              115
sector 85                               110
sector 92                               104
sector 69                                94
sector 65                                92
sector 81                                91
sector 90                                90
sector 109                               88
sector 79                                80
sector 104                               79
sector 33                                74
sector 83                                70
sector 43                                69
sector 37d                               68
sector 86                                67
sector 95                                66
sector 2                                 65
sector 89                                65
sector 50                                64
sector 107                               60
sector 56                                59
sector 108                               58
sector 70a                               54
sector 37c                               53
sector 4                                 53
sector 70                                53
sector 49                                52
sector 84                                51
sector 26                                51
sector 67                                48
sector 28                                46
sector 106                               46
sector 103                               45
sector 7                                 44
sector 113                               43
sector 82                                42
sector 12                                42
sector 66                                42
sector 25                                42
sector 61                                42
sector 1                                 40
sector 54                                33
sector 99a                               32
sector 68                                32
sector 77                                29
sector 72                                29
sector 3                                 28
sector 71                                27
sector 59                                26
sector 24                                26
sector 11                                25
sector 57                                25
sector 112                               24
sector 105                               23
sector 88a                               23
sector 14                                23
sector 111                               22
sector 110                               22
sector 67a                               22
sector 82a                               20
sector 47                                20
sector 22                                20
sector 78                                19
sector 9                                 19
sector 74                                18
sector 63a                               18
sector 62                                17
sector 91                                17
sector 99                                16
sector 63                                15
sector 60                                15
sector 55                                14
sector 23                                14
sector 76                                14
sector 52                                14
sector 53                                14
sector 36a                               13
sector 46                                13
sector 6                                 13
sector 38                                13
sector 93                                12
sector 41                                12
sector 31                                12
sector 39                                12
sector 36                                11
sector 9a                                11
sector 3 phase 3 extension               11
sector 5                                 10
sector 8                                 10
sector -1                                10
sector 13                                10
sector 51                                 9
sector 3 phase 2                          9
sector 45                                 8
sector 10a                                8
sector 40                                 8
sector 17                                 8
sector 58                                 7
sector 15                                 7
sector 21                                 6
new sector 2                              5
sector 30                                 5
sector 80                                 5
sector 10                                 5
sector 37                                 4
sector 17b                                3
sector 17a                                3
sector 27                                 3
sector 88b                                3
sector 73                                 3
block a sector 21                         2
sector 32                                 2
sector 15 part 1                          2
sector 11 sohna road                      2
new sector 2 phase 1                      2
sector 15 part 2                          2
west sector 13                            2
new sector 2 phase 2                      2
sector 29                                 2
sector 2 sohna road                       2
sector 17c                                1
urban estate sector 5                     1
sector 7 hous                             1
ansal s sector 2                          1
sector 5 sheetla colony                   1
sector 3 phase i                          1
sector 37b                                1
old delhi road opp sector 14              1
near sector 1 market                      1
saroop garden sector 105                  1
v block sector 24                         1
sector 42                                 1
block g sector 57                         1
sector 4 railway road                     1
huda sector 28                            1
anand garden sector 105                   1
new sector 7                              1
sector 21a faridabad                      1
sector 35 sohna road                      1
b1 block sector 57                        1
sector 7 sector 7                         1
sector 12 near sadar bazar                1
sector 4 urban estate                     1
sector 3 phase 3                          1
part 3 sector 5                           1
sector 37a                                1
sector 35                                 1
block h sector 3 phase iii extension      1
sector 5 chowk                            1
sector 50 pocket h                        1
sector 5 sohna road                       1
sector 9b                                 1
mahasector 11 rajendra place              1
godrej aria sector 79                     1
Name: count, dtype: int64

In [93]:
df['sector'].isna().sum()

np.int64(0)

In [94]:
#find a way to fill them
df[df['sector'].str.contains('-1')]

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
123,"4 Bedroom House for sale in Gopal Nagar, Garhi...",house,independent,sector -1,1.00,11111.0,904.17,Plot area 100(83.61 sq.m.),4,3,3+,others,"162/28, Gopal Nagar, Garhi Ghasita, Near Malik...",4.0,North-East,1 to 5 Year Old,"['Hanuman Mandir', 'State bank of india ATM', ...","A. New building, \nB. Basement+duplex showroom...","['1 Water Purifier', '1 Exhaust Fan', '1 Chimn...",NaN,NaN
504,4 BHK Flat in New Gurgaon,flat,sare homes,sector -1,0.85,4786.0,1776.00,Super Built up area 1776(165 sq.m.),4,4,3,not available,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,5 to 10 Year Old,"['Columbia Asia Hospital', 'Apex Multi Special...",Located in the popular residential address of ...,[],NaN,NaN
731,2 BHK Flat in New Gurgaon,flat,takshila heights sector c,sector -1,0.67,5583.0,1200.10,Super Built up area 1200(111.48 sq.m.),2,2,2,not available,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,1 to 5 Year Old,"['Shri Balaji Hospital and Trauma Center', 'S....",Check out this 2 bhk apartment for sale in tak...,[],"['Lift(s)', 'Swimming Pool', 'Visitor Parking'...",NaN
1530,7 Bedroom House for sale in Lucknow,house,dlf garden city floors,sector -1,4.00,17817.0,2249.66,Plot area 2245(208.57 sq.m.),7,7,3+,not available,"Lucknow, Gurgaon, Haryana",4.0,NaN,0 to 1 Year Old,"['Sapphire 83 Mall', 'Dwarka Expressway', 'NH-...",I have a house/villa available for sale in dlf...,[],"['Feng Shui / Vaastu Compliant', 'Private Gard...",NaN
1587,"5 Bedroom House for sale in Gurgaon, Delhi NCR",house,independent,sector -1,0.50,3704.0,1345.49,Built Up area: 1350 (125.42 sq.m.),5,2,0,not available,"Gurgaon, Delhi NCR, Gurgaon, Haryana",2.0,NaN,undefined,NaN,5bhk residential house for resale in at gurgao...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,NaN
1746,2 Bedroom House for sale in Narsinghpur,house,independent,sector -1,0.53,63554.0,86.11,Plot area 83(7.71 sq.m.)Built Up area: 84 sq.f...,2,1,1,store room,"Narsinghpur, Gurgaon, Haryana",1.0,East,0 to 1 Year Old,"['S.R.S. Hospital and Critical Care Unit', 'Ko...",Independent house available for sale in sector...,"['1 Wardrobe', '3 Fan', '1 Exhaust Fan', '10 L...","['Feng Shui / Vaastu Compliant', 'Private Gard...",NaN
1949,"9 Bedroom House for sale in Gurgaon, Delhi NCR",house,independent,sector -1,1.50,16667.0,904.17,Carpet area: 900 (83.61 sq.m.),9,3,3+,not available,"Gurgaon, Delhi NCR, Gurgaon, Haryana",3.0,NaN,undefined,NaN,9bhk residential house for resale in at gurgao...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,NaN
2433,2 Bedroom House for sale in Narsinghpur,house,sector 37,sector -1,0.55,7290.0,753.47,Plot area 84(70.23 sq.m.)Built Up area: 83 sq....,2,1,1,store room,"House No. 4, Narsinghpur, Gurgaon, Haryana",1.0,East,0 to 1 Year Old,"['S.R.S. Hospital and Critical Care Unit', 'Ko...",Independent house available for sale in narsin...,"['1 Wardrobe', '10 Light', '1 Modular Kitchen'...","['Feng Shui / Vaastu Compliant', 'Private Gard...",NaN
3203,2 BHK Flat in New Gurgaon,flat,green court,sector -1,0.38,5507.0,690.00,Carpet area: 690 (64.1 sq.m.),2,2,1,not available,"New Gurgaon, Gurgaon, Haryana",7.0,NaN,Under Construction,"['Ing bank ATM', 'Dcb bank ATM', 'Indus ind ba...",We are the proud owners of this 2 bhk apartmen...,[],"['Intercom Facility', 'Lift(s)', 'Maintenance ...",NaN
3835,4 BHK Flat in New Gurgaon,flat,dlf,sector -1,4.00,11428.0,3500.20,Carpet area: 3500 (325.16 sq.m.),4,4,2,"Study Room,Servant Room","New Gurgaon, Gurgaon, Haryana",4.0,NaN,Jun-27,"['Shri Balaji Hospital and Trauma Center', 'S....",This lovely 4 bhk apartment/flat in new gurgao...,"['6 Wardrobe', '1 Fridge', '8 Fan', '1 Exhaust...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...",NaN

In [95]:
df.shape

(3942, 21)

In [96]:
a=df['sector'].value_counts()[df['sector'].value_counts()>=3]

In [97]:
a.index

Index(['sector 48', 'sector 102', 'sector 85', 'sector 92', 'sector 69',
       'sector 65', 'sector 81', 'sector 90', 'sector 109', 'sector 79',
       ...
       'new sector 2', 'sector 30', 'sector 80', 'sector 10', 'sector 37',
       'sector 17b', 'sector 17a', 'sector 27', 'sector 88b', 'sector 73'],
      dtype='object', name='sector', length=111)

In [98]:
df=df[df['sector'].isin(a.index)]

In [99]:
df['sector'].value_counts()

sector
sector 48                     234
sector 102                    115
sector 85                     110
sector 92                     104
sector 69                      94
sector 65                      92
sector 81                      91
sector 90                      90
sector 109                     88
sector 79                      80
sector 104                     79
sector 33                      74
sector 83                      70
sector 43                      69
sector 37d                     68
sector 86                      67
sector 95                      66
sector 89                      65
sector 2                       65
sector 50                      64
sector 107                     60
sector 56                      59
sector 108                     58
sector 70a                     54
sector 4                       53
sector 37c                     53
sector 70                      53
sector 49                      52
sector 26                      51
sector 84                      51
sector 67                      48
sector 28                      46
sector 106                     46
sector 103                     45
sector 7                       44
sector 113                     43
sector 66                      42
sector 82                      42
sector 12                      42
sector 61                      42
sector 25                      42
sector 1                       40
sector 54                      33
sector 68                      32
sector 99a                     32
sector 72                      29
sector 77                      29
sector 3                       28
sector 71                      27
sector 24                      26
sector 59                      26
sector 57                      25
sector 11                      25
sector 112                     24
sector 88a                     23
sector 105                     23
sector 14                      23
sector 110                     22
sector 67a                     22
sector 111                     22
sector 22                      20
sector 82a                     20
sector 47                      20
sector 9                       19
sector 78                      19
sector 74                      18
sector 63a                     18
sector 62                      17
sector 91                      17
sector 99                      16
sector 63                      15
sector 60                      15
sector 55                      14
sector 23                      14
sector 52                      14
sector 53                      14
sector 76                      14
sector 6                       13
sector 36a                     13
sector 46                      13
sector 38                      13
sector 39                      12
sector 93                      12
sector 31                      12
sector 41                      12
sector 36                      11
sector 9a                      11
sector 3 phase 3 extension     11
sector 13                      10
sector 8                       10
sector -1                      10
sector 5                       10
sector 51                       9
sector 3 phase 2                9
sector 40                       8
sector 17                       8
sector 45                       8
sector 10a                      8
sector 58                       7
sector 15                       7
sector 21                       6
new sector 2                    5
sector 30                       5
sector 80                       5
sector 10                       5
sector 37                       4
sector 17a                      3
sector 88b                      3
sector 17b                      3
sector 73                       3
sector 27                       3
Name: count, dtype: int64

In [100]:
df.shape

(3888, 21)

In [101]:
df['sector']=df['sector'].str.lower().str.extract(r'(sector\s*-?\d+)')

In [102]:
df['sector'].value_counts()

sector
sector 48     234
sector 37     125
sector 102    115
sector 85     110
sector 70     107
sector 92     104
sector 69      94
sector 65      92
sector 81      91
sector 90      90
sector 109     88
sector 79      80
sector 104     79
sector 33      74
sector 83      70
sector 67      70
sector 2       70
sector 43      69
sector 86      67
sector 95      66
sector 89      65
sector 50      64
sector 82      62
sector 107     60
sector 56      59
sector 108     58
sector 4       53
sector 49      52
sector 26      51
sector 84      51
sector 99      48
sector 3       48
sector 28      46
sector 106     46
sector 103     45
sector 7       44
sector 113     43
sector 12      42
sector 66      42
sector 61      42
sector 25      42
sector 1       40
sector 54      33
sector 63      33
sector 68      32
sector 9       30
sector 77      29
sector 72      29
sector 71      27
sector 24      26
sector 59      26
sector 88      26
sector 57      25
sector 11      25
sector 112     24
sector 36      24
sector 14      23
sector 105     23
sector 110     22
sector 111     22
sector 47      20
sector 22      20
sector 78      19
sector 74      18
sector 62      17
sector 91      17
sector 60      15
sector 52      14
sector 23      14
sector 55      14
sector 53      14
sector 76      14
sector 17      14
sector 10      13
sector 6       13
sector 46      13
sector 38      13
sector 41      12
sector 39      12
sector 93      12
sector 31      12
sector -1      10
sector 5       10
sector 8       10
sector 13      10
sector 51       9
sector 45       8
sector 40       8
sector 58       7
sector 15       7
sector 21       6
sector 30       5
sector 80       5
sector 73       3
sector 27       3
Name: count, dtype: int64

In [103]:
df=df[~df['sector'].str.contains('sector -1')]

In [104]:
df.shape

(3878, 21)

In [105]:
df[df['sector'] == 'new']

Empty DataFrame
Columns: [property_name, property_type, society, sector, price, price_per_sqft, area, areaWithType, bedRoom, bathroom, balcony, additionalRoom, address, floorNum, facing, agePossession, nearbyLocations, description, furnishDetails, features, rating]
Index: []

In [106]:
df.duplicated().sum()

np.int64(0)

In [107]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,1 BHK Flat in Sector 92 Gurgaon,flat,gls avenue,sector 92,0.21,6953.0,302.00,Carpet area: 302 (28.06 sq.m.),1,1,1,not available,"Sector 92 Gurgaon, Gurgaon, Haryana",0.0,South-East,1 to 5 Year Old,"['Yaduvanshi Shiksha Niketan Sector- 92', 'Aar...",Check out this 1 bhk apartment for sale in gls...,NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,4 BHK Flat in Gwal Pahari,flat,paras quartier,sector 59,5.90,11028.0,5350.00,Built Up area: 5350 (497.03 sq.m.),4,4,3+,not available,"Paras Quartier, Valley View Estate, Gwal Pahar...",0.0,NaN,5 to 10 Year Old,"['Sector 55-56 Metro Station', 'South point Ma...","New apartment, lush green aravalli valley 270 ...","['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,NaN
2,3 BHK Flat in Sector 1 Imt Manesar,flat,hsiidc sidco aravali,sector 1,0.90,3477.0,2588.40,Super Built up area 2588(240.43 sq.m.)Built Up...,3,3,3+,Servant Room,"Sector 1 Imt Manesar, Gurgaon, Haryana",8.0,East,5 to 10 Year Old,"['Pooja Clinic', 'Dr. Sahil Clinic', 'Prakash ...",Arawali sipco sec-1 imt manesar good property ...,"['6 Fan', '6 Light', 'No AC', 'No Bed', 'No Ch...","['Lift(s)', 'Maintenance Staff', 'Park', 'Pipe...","['Environment5 out of 5', 'Lifestyle4.5 out of..."
3,5 Bedroom House for sale in Sector 15 Gurgaon,house,sector 15 part 2 rwa,sector 15,10.00,22222.0,4520.84,Plot area 502(419.74 sq.m.),5,5,2,not available,"Sector 15 Gurgaon, Gurgaon, Haryana",2.0,East,10+ Year Old,"['Hanuman Mandir', 'State bank of india ATM', ...","Gated community and near market,school and hig...",[],"['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4.5 out of 5', 'Lifestyle4 out of..."
4,2 BHK Flat in Sohna,flat,eldeco accolade,sector 48,0.72,4975.0,1447.20,Super Built up area 1457(135.36 sq.m.)Carpet a...,2,2,3+,Study Room,"0001, Sohna, Gurgaon, Haryana",12.0,East,1 to 5 Year Old,"['Global City Centre', 'Sohna Road', 'Damdama ...","Eldeco accolade in sohna, gurgaon is a ready-T...",NaN,"['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction4.5 out ..."

In [108]:
df.drop(columns=['property_name', 'address', 'description', 'rating'],inplace=True)

In [109]:
df.shape

(3878, 17)

In [110]:
df.sample(5)

,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,floorNum,facing,agePossession,nearbyLocations,furnishDetails,features
3561,flat,mapsko casa bella,sector 82,1.30,6378.0,2038.30,Super Built up area 1960(182.09 sq.m.),4,4,3+,Servant Room,1.0,North,1 to 5 Year Old,"['Vatika City Centre Mall', 'Pataudi Road', 'B...",NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ..."
1296,flat,ats tourmaline,sector 109,1.75,8139.0,2150.10,Super Built up area 2150(199.74 sq.m.),3,4,3+,"Servant Room,Others",2.0,North,1 to 5 Year Old,"['Dwarka Sector 21 Metro Station', 'NeoSquare ...",NaN,"['Feng Shui / Vaastu Compliant', 'Security / F..."
1714,flat,bptp terra,sector 37,1.77,8078.0,2191.10,Super Built up area 2191(203.55 sq.m.)Carpet a...,4,3,3,"Pooja Room,Study Room,Servant Room,Others",15.0,North,1 to 5 Year Old,"['Airia Mall', 'Dwarka Expressway', 'Golf Cour...","['1 Wardrobe', '1 Exhaust Fan', '1 Modular Kit...","['Feng Shui / Vaastu Compliant', 'Security / F..."
2049,house,not applicable,sector 4,0.80,54794.0,150.69,Plot area 146(13.56 sq.m.),5,4,3,not available,3.0,NaN,By 2024,"['Chintapurni Mandir', 'State bank ATM', 'Prat...",[],NaN
27,flat,signature global synera,sector 81,0.45,7525.0,598.00,Carpet area: 598 (55.56 sq.m.),2,2,2,Store Room,6.0,North-East,1 to 5 Year Old,"['Sapphire 83 Mall', 'Delhi Jaipur Expressway'...","['3 Wardrobe', '3 Fan', '1 Exhaust Fan', '2 Ge...","['Power Back-up', 'Security / Fire Alarm', 'Li..."

In [111]:
df.duplicated().sum()

np.int64(124)

In [112]:
df.isna().sum()

property_type         0
society               1
sector                0
price                 1
price_per_sqft        1
area                  1
areaWithType          0
bedRoom               0
bathroom              0
balcony               0
additionalRoom        0
floorNum              2
facing             1141
agePossession         1
nearbyLocations     192
furnishDetails     1009
features            681
dtype: int64

In [113]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3878 entries, 0 to 3941
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_type    3878 non-null   object
 1   society          3877 non-null   object
 2   sector           3878 non-null   object
 3   price            3877 non-null   float64
 4   price_per_sqft   3877 non-null   float64
 5   area             3877 non-null   float64
 6   areaWithType     3878 non-null   object
 7   bedRoom          3878 non-null   int64
 8   bathroom         3878 non-null   int64
 9   balcony          3878 non-null   object
 10  additionalRoom   3878 non-null   object
 11  floorNum         3876 non-null   float64
 12  facing           2737 non-null   object
 13  agePossession    3877 non-null   object
 14  nearbyLocations  3686 non-null   object
 15  furnishDetails   2869 non-null   object
 16  features         3197 non-null   object
dtypes: float64(4), int64(2), object(11)
memory usage: 545.3+ KB

In [114]:
df[df['property_type']=='house']['area'].describe()

count      910.000000
mean      2474.674692
std       4223.754945
min         53.820000
25%        949.912500
50%       1840.630000
75%       3153.820000
max      82795.920000
Name: area, dtype: float64

In [115]:
df[df['property_type']=='flat']['area'].describe()

count      2967.000000
mean       2796.441523
std       25268.799884
min          72.000000
25%        1250.000000
50%        1660.200000
75%        2125.150000
max      875000.000000
Name: area, dtype: float64

In [116]:
df.to_csv('gurgaon_properties_cleaned2_v1.csv',index=False)