In [46]:
import pandas as pd 
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import json

In [47]:
df=pd.read_csv('appartments.csv')
df.head()

,PropertyName,PropertySubName,NearbyLocations,LocationAdvantages,Link,PriceDetails,TopFacilities
0,Smartworld One DXP,"2, 3, 4 BHK Apartment in Sector 113, Gurgaon","['Bajghera Road', 'Palam Vihar Halt', 'DPSG Palam Vihar', 'Park Hospital', 'Gurgaon Railway Station']","{'Bajghera Road': '800 Meter', 'Palam Vihar Halt': '2.5 KM', 'DPSG Palam Vihar': '3.1 KM', 'Park Hospital': '3.1 KM', 'Gurgaon Railway Station': '4.9 KM', 'The NorthCap University': '5.4 KM', 'Dwarka Expy': '1.2 KM', 'Hyatt Place Gurgaon Udyog Vihar': '7.7 KM', 'Dwarka Sector 21, Metro Station': '7.2 KM', 'Pacific D21 Mall': '7.4 KM', 'Indira Gandhi International Airport': '14.7 KM', 'Hamoni Golf Camp': '6.2 KM', 'Fun N Food Waterpark': '8.8 KM', 'Accenture DDC5': '9 KM'}",https://www.99acres.com/smartworld-one-dxp-sector-113-gurgaon-npxid-r400415,"{'2 BHK': {'building_type': 'Apartment', 'area_type': 'Carpet Area', 'area': '1,370 sq.ft.', 'price-range': '₹ 2 - 2.4 Cr'}, '3 BHK': {'building_type': 'Apartment', 'area_type': 'Carpet Area', 'area': '1,850 - 2,050 sq.ft.', 'price-range': '₹ 2.25 - 3.59 Cr'}, '4 BHK': {'building_type': 'Apartment', 'area_type': 'Carpet Area', 'area': '2,600 sq.ft.', 'price-range': '₹ 3.24 - 4.56 Cr'}}","['Swimming Pool', 'Salon', 'Restaurant', 'Spa', 'Cafeteria', 'Sun Deck', '24x7 Security', 'Club House', 'Gated Community']"
1,M3M Crown,"3, 4 BHK Apartment in Sector 111, Gurgaon","['DPSG Palam Vihar Gurugram', 'The NorthCap University', 'Park Hospital, Palam Vihar', 'Pacific D21 Mall', 'Palam Vihar Halt Railway Station']","{'DPSG Palam Vihar Gurugram': '1.4 Km', 'The NorthCap University': '4.4 Km', 'Park Hospital, Palam Vihar': '1.4 Km', 'Pacific D21 Mall': '8.2 Km', 'Palam Vihar Halt Railway Station': '1.2 Km', 'Dwarka Sector 21 Metro Station': '8.1 Km', 'Dwarka Expressway': '450 m', 'Fun N Food Water Park': '8.1 Km', 'Indira Gandhi International Airport': '14.1 Km', 'Tau DeviLal Sports Complex': '11.2 Km', 'Hamoni Golf Camp': '5 Km', 'Hyatt Place': '6.1 Km', 'Altrade Business Centre': '11.2 Km'}",https://www.99acres.com/m3m-crown-sector-111-gurgaon-npxid-r404068,"{'3 BHK': {'building_type': 'Apartment', 'area_type': 'Super Built-up Area', 'area': '1,605 - 2,170 sq.ft.', 'price-range': '₹ 2.2 - 3.03 Cr'}, '4 BHK': {'building_type': 'Apartment', 'area_type': 'Super Built-up Area', 'area': '2,248 - 2,670 sq.ft.', 'price-range': '₹ 3.08 - 3.73 Cr'}}","['Bowling Alley', 'Mini Theatre', 'Manicured Garden', 'Swimming Pool', 'Flower Garden', 'Reading Lounge', 'Golf Course', 'Barbecue', 'Sauna']"
2,Adani Brahma Samsara Vilasa,"Land, 3, 4 BHK Independent Floor in Sector 63, Gurgaon","['AIPL Business Club Sector 62', 'Heritage Xperiential Learning School', 'CK Birla Hospital', 'Paras Trinity Mall Sector 63', 'Rapid Metro Station Sector 56']","{'AIPL Business Club Sector 62': '2.7 Km', 'Heritage Xperiential Learning School': '2 Km', 'CK Birla Hospital': '2.5 Km', 'Paras Trinity Mall Sector 63': '3.5 Km', 'Rapid Metro Station Sector 56': '3.8 Km', 'De Adventure Park': '6.8 Km', 'Golf Course Ext Rd': '99 Meter', 'DoubleTree by Hilton Hotel Gurgaon': '3.6 Km', 'KIIT College of Engineering Sohna Road': '8.4 Km', 'Mehrauli-Gurgaon Road': '11.8 Km', 'Indira Gandhi International Airport': '21.1 Km', 'Nirvana Rd': '160 Meter', 'TERI Golf Course': '8.7 Km'}",https://www.99acres.com/adani-brahma-samsara-vilasa-sector-63-gurgaon-npxid-r327995,"{'3 BHK': {'building_type': 'Independent Floor', 'area_type': 'Super Built-up Area', 'area': '1,800 - 3,150 sq.ft.', 'price-range': '₹ 2.43 - 15.75 Cr'}, '4 BHK': {'building_type': 'Independent Floor', 'area_type': 'Super Built-up Area', 'area': '2,750 - 4,500 sq.ft.', 'price-range': '₹ 3.36 - 22.5 Cr'}, 'Land': {'building_type': '', 'area_type': 'Plot Area', 'area': '500 - 4,329 sq.ft.', 'price-range': '₹ 2.05 - 41.13 Cr'}}","['Terrace Garden', 'Gazebo', 'Fountain', 'Amphitheatre', 'Party Lawn', 'Basketball Court', 'Badminton Court', 'Yoga/Meditation Area', 'Indoor Games']"
3,Sobha City,"2, 3, 4 BHK Apartment in Sector 108, Gurgaon","['The Shikshiyan School', 'WTC Plaza', 'Luxus Haritma Resort', 'BSF Golf Course', 'Dwarka Expressway']","{'The Shikshiyan School': '2.9 KM', 'WTC Plaza': '4 KM', 'Luxus Haritma Resort': '4.2 KM', 'BSF Golf Course': '4.7 KM', 'Dwarka Expressway': '5.1 Km', 'Rions Hospital': '5.6 Km', 'Gurgaon': '5.9 KM', 'The NorthCap University': '9.2 KM', 'Dwarka Sector 21': '9.9 KM', 'Nehru Stadium': '10.7 KM', 'Fun N Food WaterPark': '12.1 KM', 'IGI Airport': '19.3 Km', 'Vasant Kunj': '20.8 KM'}",https://www.99acres.com/sobha-city-sector-108-gurgaon-npxid-r256111,"{'2 BHK': {'building_type': 'Apartment', 'area_type': 'Super Built-up Area', 'area': '1,381 - 1,692 sq.ft.', 'price-range': '₹ 1.55 - 3.21 Cr'}, '3 BHK': {'building_type': 'Apartment', 'area_type': 'Super Built-up Area', 'area': '1,711 - 2,343 sq.ft.', 'price-range': '₹ 1.76 - 4.79 Cr'}, '4 BHK': {'building_type': 'Apartment', 'area_type': 'Super Built-up Area', 'area': '2,423 - 2,963 sq.ft.', 'price-range': '₹ 2.5 - 6.06 Cr'}}","['Swimming Pool', 'Volley Ball Court', 'Aerobics Centre', 'Card Room', 'Barbecue', 'Sauna', 'Steam Room', 'Creche/Day care', 'Skating Rink']"
4,Signature Global City 93,"2, 3 BHK Independent Floor in Sector 93 Gurgaon","['Pranavananda Int. School', 'DLF Site central office', 'Holiday Inn Gurugram Sector 90', 'Krishna Hospital', 'Royal Institute Of Science']","{'Pranavananda Int. School': '450 m', 'DLF Site central office': '1.2 Km', 'Holiday Inn Gurugram Sector 90': '2 Km', 'Krishna Hospital': '2.3 Km', 'Royal Institute Of Science': '2.4 Km', 'Sapphire 83 Mall': '6.3 Km', 'NH48': '6.9 Km', 'Garhi Harsaru Junction': '7.2 Km', 'Manesar Golf Course': '7.3 Km', 'AapnoGhar': '9.6 Km', 'IGI Airport': '31 Km'}",https://www.99acres.com/signature-global-city-93-sector-93-gurgaon-npxid-r404456,"{'2 BHK': {'building_type': 'Independent Floor', 'area_type': 'Carpet Area', 'area': '981 - 1,118 sq.ft.', 'price-range': '₹ 93.01 L - 1.06 Cr'}, '3 BHK': {'building_type': 'Independent Floor', 'area_type': 'Carpet Area', 'area': '1,235 - 1,530 sq.ft.', 'price-range': '₹ 1.12 - 1.45 Cr'}}","['Mini Theatre', 'Doctor on Call', 'Concierge Service', 'Swimming Pool', 'Bar/Chill-Out Lounge', 'Laundry', 'Flower Garden', 'Reflexology Park', 'Salon']"

In [48]:
df.drop(index=22,inplace=True)

In [49]:
df.iloc[[22,23,21,34]]

,PropertyName,PropertySubName,NearbyLocations,LocationAdvantages,Link,PriceDetails,TopFacilities
23,M3M Capital,"2, 3, 4 BHK Apartment in Sector 113, Gurgaon","['Dwarka Expy', 'Shivani public school', 'Baghera University', 'Kutumbh Hospital', 'Bijwasan Railway Station']","{'Dwarka Expy': '10 m', 'Shivani public school': '1.8 Km', 'Baghera University': '2.7 Km', 'Kutumbh Hospital': '1 Km', 'Bijwasan Railway Station': '4.5 Km', 'Global Foyer Mall': '4.2 Km', 'Phase 2 Metro Station': '11.5 Km', 'IGI Airport': '16.5 Km'}",https://www.99acres.com/m3m-capital-sector-113-gurgaon-npxid-r385121,"{'2 BHK': {'building_type': 'Apartment', 'area_type': 'Carpet Area', 'area': '1,300 - 1,330 sq.ft.', 'price-range': '₹ 1.3 - 1.56 Cr'}, '3 BHK': {'building_type': 'Apartment', 'area_type': 'Carpet Area', 'area': '1,650 - 1,700 sq.ft.', 'price-range': '₹ 1.65 - 2.06 Cr'}, '4 BHK': {'building_type': 'Apartment', 'area_type': 'Carpet Area', 'area': '2,055 - 2,249 sq.ft.', 'price-range': '₹ 3.29 - 3.69 Cr'}}","['Swimming Pool', 'Lounge', 'Bar/Chill-Out Lounge', 'ATM', 'Aerobics Centre', 'Restaurant', 'Sauna', 'Spa', 'Skating Rink']"
24,Godrej Meridien,"1, 2, 3, 4 BHK Apartment in Sector 106, Gurgaon","['Dwarka Expressway', 'Euro International School, Sector- 109', 'Gurgaon Railway Station', 'Gurgaon Dreamz Mall', 'Metro Hospital, Palam Vihar']","{'Dwarka Expressway': '1.8 Km', 'Euro International School, Sector- 109': '2.1 Km', 'Gurgaon Railway Station': '1.6 Km', 'Gurgaon Dreamz Mall': '3.8 Km', 'Metro Hospital, Palam Vihar': '4.8 Km', 'Delhi Ajmer Expressway': '9 Km', 'Infinity Business Park': '8.7 Km', 'The NorthCap University': '7.1 Km', 'Huda metro station': '10.6 km'}",https://www.99acres.com/godrej-meridien-sector-106-gurgaon-npxid-r306651,"{'1 BHK': {'building_type': 'Apartment', 'area_type': 'Carpet Area', 'area': '1,510 sq.ft.', 'price-range': '₹ 1.98 - 2.38 Cr'}, '2 BHK': {'building_type': 'Apartment', 'area_type': 'Carpet Area', 'area': '817.3 - 1,732 sq.ft.', 'price-range': '₹ 1.29 - 3.6 Cr'}, '3 BHK': {'building_type': 'Apartment', 'area_type': 'Carpet Area', 'area': '1,025.05 - 2,050 sq.ft.', 'price-range': '₹ 1.62 - 5.72 Cr'}, '4 BHK': {'building_type': 'Apartment', 'area_type': 'Carpet Area', 'area': '1,657.1 - 2,750 sq.ft.', 'price-range': '₹ 2.61 - 7.67 Cr'}}","['Valet Parking', 'Mini Theatre', 'Concierge Service', 'Swimming Pool', 'Bar/Chill-Out Lounge', 'Medical Centre', 'Flower Garden', 'Reflexology Park', 'School']"
21,Krisumi Waterfall Residences,"1, 2, 3, 4 BHK Apartment, 1 RK Studio Apartment in Sector 36A, Gurgaon","['Dwarka Expy', 'Delhi Public School, Sector 84', 'Elan Miracle Mall', 'Aarvy Hospital', 'Holiday Inn Gurugram Sector 90']","{'Dwarka Expy': '6 KM', 'Delhi Public School, Sector 84': '3.1 KM', 'Elan Miracle Mall': '6 KM', 'Aarvy Hospital': '8.8 KM', 'Holiday Inn Gurugram Sector 90': '9.1 KM', 'DPG Degree College': '7.6 KM', 'Garhi Harsaru Junction': '11.7 KM', 'Tau DeviLal Sports Complex': '9.7 KM', 'DLF Corporate Greens': '10.3 KM', 'Indira Gandhi International Airport': '25.3 KM', 'NH 48': '3.1 KM'}",https://www.99acres.com/krisumi-waterfall-residences-sector-36a-gurgaon-npxid-r331957,"{'1 BHK': {'building_type': 'Apartment', 'area_type': 'Carpet Area', 'area': '464.14 - 6,367.71 sq.ft.', 'price-range': 'Price on Request'}, '2 BHK': {'building_type': 'Apartment', 'area_type': 'Super Built-up Area', 'area': '1,448.41 - 1,479 sq.ft.', 'price-range': '₹ 1.9 - 9.06 Cr'}, '3 BHK': {'building_type': 'Apartment', 'area_type': 'Super Built-up Area', 'area': '1,946 - 4,429.5 sq.ft.', 'price-range': '₹ 2.45 - 27.12 Cr'}, '4 BHK': {'building_type': 'Apartment', 'area_type': 'Super Built-up Area', 'area': '4,429 - 6,353.03 sq.ft.', 'price-range': '₹ 10.53 - 38.9 Cr'}, '1 RK': {'building_type': 'Studio Apartment', 'area_type': 'Carpet Area', 'area': '460.09 - 588 sq.ft.', 'price-range': '₹ 1.41 - 3.6 Cr'}}","['Concierge Service', 'Swimming Pool', 'Bar/Chill-Out Lounge', 'Salon', 'Restaurant', 'Terrace Garden', 'Pergola', 'Jacuzzi', 'Piped Gas']"
35,Eldeco Acclaim,"2, 3 BHK Apartment in Sohna, Gurgaon","['G D Goenka University', 'Fly India Adventure Resort', 'GD Goenka World School', 'Vardaan Hospital', 'IMT Office Sohna']","{'G D Goenka University': '1 Km', 'Fly India Adventure Resort': '1.2 Km', 'GD Goenka World School': '1.7 Km', 'Vardaan Hospital': '1.7 Km', 'IMT Office Sohna': '8 Km', 'Sohna Road': '10 Km', 'Airia Mall': '18.4 Km'}",https://www.99acres.com/eldeco-acclaim-sohna-gurgaon-npxid-r369999,"{'2 BHK': {'building_type': 'Apartment', 'area_type': 'Carpet Area', 'area': '730 - 849 sq.ft.', 'price-range': '₹ 91 L - 1.06 Cr'}, '3 BHK': {'building_type': 'Apartment', 'area_type': 'Carpet Area', 'area': '1,062 - 1,276 sq.ft.', 'price-range': '₹ 1.32 - 1.59 Cr'}}","['Swimming Pool', 'Restaurant', 'Piped Gas', 'Squash Court', 'Gazebo', 'Property Staff', 'Billiards', 'Sun Deck', 'Lawn Tennis Court']"

In [50]:
df['TopFacilities'].unique()

array(["['Swimming Pool', 'Salon', 'Restaurant', 'Spa', 'Cafeteria', 'Sun Deck', '24x7 Security', 'Club House', 'Gated Community']",
       "['Bowling Alley', 'Mini Theatre', 'Manicured Garden', 'Swimming Pool', 'Flower Garden', 'Reading Lounge', 'Golf Course', 'Barbecue', 'Sauna']",
       "['Terrace Garden', 'Gazebo', 'Fountain', 'Amphitheatre', 'Party Lawn', 'Basketball Court', 'Badminton Court', 'Yoga/Meditation Area', 'Indoor Games']",
       "['Swimming Pool', 'Volley Ball Court', 'Aerobics Centre', 'Card Room', 'Barbecue', 'Sauna', 'Steam Room', 'Creche/Day care', 'Skating Rink']",
       "['Mini Theatre', 'Doctor on Call', 'Concierge Service', 'Swimming Pool', 'Bar/Chill-Out Lounge', 'Laundry', 'Flower Garden', 'Reflexology Park', 'Salon']",
       "['Reflexology Park', 'Card Room', 'High Speed Elevators', 'Sauna', 'Jacuzzi', 'Spa', 'Entrance Lobby', 'Yoga/Meditation Area', 'Club House']",
       "['Swimming Pool', 'Football', 'Flower Garden', 'Reading Lounge', 'School', 'Pergola', 'Skating Rink', 'Grocery Shop', 'Squash Court']",
       "['Swimming Pool', 'Aerobics Centre', 'Shopping Centre', 'Video Door Security', 'Amphitheatre', 'Yoga/Meditation Area', 'CCTV Camera Security', 'Jogging Track', '24x7 Security']",
       "['Swimming Pool', 'Reflexology Park', 'Terrace Garden', 'Waiting Lounge', 'Jacuzzi', 'Skating Rink', 'Cricket Pitch', 'Sun Deck', 'Amphitheatre']",
       "['Mini Theatre', 'Swimming Pool', 'Salon', 'Card Room', 'Restaurant', 'Spa', 'Creche/Day care', 'Banquet Hall', 'Lawn Tennis Court']",
       "['Swimming Pool', 'Reflexology Park', 'Gazebo', 'Banquet Hall', 'Cricket Pitch', 'Sun Deck', 'Multipurpose Court', 'Amphitheatre', 'Toddler Pool']",
       '[\'Swimming Pool\', \'Community Hall\', \'Yoga/Meditation Area\', \'24x7 Security\', \'Club House\', \'Gated Community\', \'Gymnasium\', \'Landscape Garden\', "Children\'s Play Area"]',
       "['Mini Theatre', 'Swimming Pool', 'Lounge', 'Reflexology Park', 'Restaurant', 'Terrace Garden', 'Sauna', 'Spa', 'Gazebo']",
       "['Swimming Pool', 'Flower Garden', 'Jacuzzi', 'Wi-Fi Connectivity', 'Amphitheatre', 'Power Back up Lift', 'Vastu Compliant', 'Basketball Court', 'Badminton Court']",
       "['Swimming Pool', 'School', 'Entrance Lobby', 'CCTV Camera Security', 'Club House', 'Gated Community', 'Landscape Garden', 'Lift(s)', 'Car Parking']",
       "['Swimming Pool', 'Card Room', 'Restaurant', 'Spa', 'Squash Court', 'Gazebo', 'Banquet Hall', 'Lawn Tennis Court', 'Amphitheatre']",
       "['Salon', 'Spa', 'Cricket Pitch', 'Lawn Tennis Court', 'Amphitheatre', 'Basketball Court', 'Badminton Court', 'Entrance Lobby', 'Yoga/Meditation Area']",
       '[\'Earthquake Resistant\', \'Vastu Compliant\', \'Entrance Lobby\', \'24/7 Power Backup\', \'24/7 Water Supply\', \'Landscape Garden\', "Children\'s Play Area", \'Lift(s)\', \'Car Parking\']',
       '[\'Lounge\', \'Barbecue\', \'Creche/Day care\', \'Yoga/Meditation Area\', \'Club House\', \'Gymnasium\', \'Landscape Garden\', "Children\'s Play Area", \'Lift(s)\']',
       "['Valet Parking', 'Foosball', 'Concierge Service', 'Infinity Pool', 'Swimming Pool', 'Bar/Chill-Out Lounge', 'Business Lounge', 'Laundry', 'Cigar Lounge']",
       "['Mini Theatre', 'Swimming Pool', 'Bar/Chill-Out Lounge', 'Business Lounge', 'Cigar Lounge', 'Golf Course', 'School', 'Card Room', 'Restaurant']",
       "['Concierge Service', 'Swimming Pool', 'Bar/Chill-Out Lounge', 'Salon', 'Restaurant', 'Terrace Garden', 'Pergola', 'Jacuzzi', 'Piped Gas']",
       "['Swimming Pool', 'Lounge', 'Bar/Chill-Out Lounge', 'ATM', 'Aerobics Centre', 'Restaurant', 'Sauna', 'Spa', 'Skating Rink']",
       "['Valet Parking', 'Mini Theatre', 'Concierge Service', 'Swimming Pool', 'Bar/Chill-Out Lounge', 'Medical Centre', 'Flower Garden', 'Reflexology Park', 'School']",
       "['Mini Theatre', 'Natural Pond', 'Swimming Pool', 'Card Room', 'Sauna', 'Spa', 'Squash Court', 'Cricket Pitch', 'Sun Deck']",
       "['Mini Theatre', 'Swimming Pool', 'Football', 'Lounge', 'Business Lounge', 'Flower Garden', 'Reflexology Park', 'Conference room', 'Salon']",
       "['Swimming Pool', 'Reflexology Park', 'Jacuzzi', 'Skating Rink', 'Cricket Pitch', 'Multipurpose Court', 'Amphitheatre', 'Toddler Pool', 'Basketball Court']",
       "['Air Hockey', 'Acupressure Park', 'Foosball', 'Swimming Pool', 'Football', 'Reading Lounge', 'Golf Course', 'Volley Ball Court', 'ATM']",
       "['Swimming Pool', 'Lounge', 'Bar/Chill-Out Lounge', 'Solar Lighting', 'Aerobics Centre', 'Restaurant', 'Terrace Garden', 'Piped Gas', 'Theatre']",
       "['Swimming Pool', 'Bar/Chill-Out Lounge', 'Waiting Lounge', 'Fountain', 'Sun Deck', 'Toddler Pool', 'Community Hall', 'Yoga/Meditation Area', 'Rain Water Harvesting']",
       "['Bus Shelter', 'Swimming Pool', 'Lounge', 'Bar/Chill-Out Lounge', 'Reflexology Park', 'School', 'Aerobics Centre', 'Terrace Garden', 'High Speed Elevators']",
       "['Swimming Pool', 'Visitors Parking', 'Skating Rink', 'Cricket Pitch', 'Basketball Court', 'Sewage Treatment Plant', 'Jogging Track', 'Club House', 'Gated Community']",
       "['Reflexology Park', 'RO System', 'Restaurant', 'Theatre', 'Amphitheatre', 'Badminton Court', 'Entrance Lobby', 'Multipurpose Hall', 'Yoga/Meditation Area']",
       "['Valet Parking', 'Swimming Pool', 'Football', 'Business Lounge', 'Medical Centre', 'Flower Garden', 'School', 'Squash Court', 'Wi-Fi Connectivity']",
       "['Swimming Pool', 'Restaurant', 'Piped Gas', 'Squash Court', 'Gazebo', 'Property Staff', 'Billiards', 'Sun Deck', 'Lawn Tennis Court']",
       "['Swimming Pool', 'Flower Garden', 'Golf Course', 'Solar Lighting', 'Pergola', 'Property Staff', 'Cafeteria', 'Fountain', 'Lawn Tennis Court']",
       '[\'Swimming Pool\', \'Entrance Lobby\', \'Yoga/Meditation Area\', \'24/7 Power Backup\', \'Gated Community\', \'Gymnasium\', "Children\'s Play Area", \'Car Parking\']',
       "['Swimming Pool', 'Bar/Chill-Out Lounge', 'School', 'Spa', 'Grocery Shop', 'Squash Court', 'Shopping Centre', 'Power Back up Lift', 'CCTV Camera Security']",
       "['Swimming Pool', 'Golf Course', 'Salon', 'Restaurant', 'Spa', 'Water Softener Plant', 'Grocery Shop', 'Shopping Centre', 'Cricket Pitch']",
       "['Swimming Pool', 'High Speed Elevators', 'Waiting Lounge', 'Skating Rink', 'Grocery Shop', 'Wi-Fi Connectivity', 'Cafeteria', 'Fountain', 'Cricket Pitch']",
       "['Swimming Pool', 'Business Lounge', 'Golf Course', 'Barbecue', 'Restaurant', 'Pergola', 'Spa', 'Squash Court', 'Theatre']",
       "['Milk Booth', 'Swimming Pool', 'Bar/Chill-Out Lounge', 'Cigar Lounge', 'Changing Area', 'School', 'Aerobics Centre', 'Card Room', 'Restaurant']",
       "['Mini Theatre', 'Doctor on Call', 'Beach Volley Ball Court', 'Air Hockey', 'Automated Car Wash', 'Clinic', 'Foosball', 'Concierge Service', 'Car wash area']",
       "['Concierge Service', 'Swimming Pool', 'Changing Area', 'ATM', 'Sauna', 'Water Softener Plant', 'Skating Rink', 'Wi-Fi Connectivity', 'Property Staff']",
       "['Swimming Pool', 'Reflexology Park', 'Squash Court', 'Shopping Centre', 'Lawn Tennis Court', 'Power Back up Lift', 'Community Hall', 'Basketball Court', 'Entrance Lobby']",
       "['Swimming Pool', 'Shopping Centre', 'Sun Deck', 'Yoga/Meditation Area', 'Sewage Treatment Plant', 'Jogging Track', 'Rain Water Harvesting', 'Club House', '24/7 Power Backup']",
       "['Clinic', 'Swimming Pool', 'Medical Centre', 'School', 'Card Room', 'Restaurant', 'Squash Court', 'Theatre', 'Gazebo']",
       "['Mini Theatre', 'Air Hockey', 'Foosball', 'Natural Pond', 'Swimming Pool', 'Reading Lounge', 'Conference room', 'Solar Lighting', 'Card Room']",
       "['Automated Car Wash', 'Swimming Pool', 'Laundry', 'Reading Lounge', 'Card Room', 'Restaurant', 'Piped Gas', 'Property Staff', 'Cafeteria']",
       "['Swimming Pool', 'Bar/Chill-Out Lounge', 'Terrace Garden', 'Piped Gas', 'Cafeteria', 'Table Tennis', 'Badminton Court', 'Jogging Track', 'Club House']",
       "['Solar Lighting', 'Pergola', 'Skating Rink', 'Fountain', 'Shopping Centre', 'Cricket Pitch', 'Amphitheatre', 'Sewage Treatment Plant', 'CCTV Camera Security']",
       "['Mini Theatre', 'Swimming Pool', 'Lounge', 'Bar/Chill-Out Lounge', 'Medical Centre', 'Conference room', 'Salon', 'Aerobics Centre', 'Visitors Parking']",
       "['Concierge Service', 'Swimming Pool', 'Golf Course', 'Visitors Parking', 'Restaurant', 'Waiting Lounge', 'Sauna', 'Spa', 'Water Softener Plant']",
       "['Football', 'Skating Rink', 'Cricket Pitch', 'Amphitheatre', 'Basketball Court', 'Badminton Court', 'Yoga/Meditation Area', 'Gymnasium', 'Landscape Garden']",
       "['Natural Pond', 'Swimming Pool', 'Terrace Garden', 'Pergola', 'Sauna', 'Spa', 'Fountain', 'Sun Deck', 'Video Door Security']",
       "['Swimming Pool', 'Bar/Chill-Out Lounge', 'Flower Garden', 'Reading Lounge', 'Salon', 'Card Room', 'Solar Water Heating', 'Restaurant', 'Spa']",
       "['Mini Theatre', 'Swimming Pool', 'Football', 'Bar/Chill-Out Lounge', 'Business Lounge', 'Salon', 'Restaurant', 'Spa', 'Water Softener Plant']",
       "['Concierge Service', 'Swimming Pool', 'Restaurant', 'Spa', 'Skating Rink', 'Squash Court', 'Theatre', 'Pool Table', 'Property Staff']",
       "['Swimming Pool', 'Laundry', 'School', 'Solar Lighting', 'Terrace Garden', 'Creche/Day care', 'Grocery Shop', 'Shopping Centre', 'Video Door Security']",
       "['Foosball', 'Concierge Service', 'Infinity Pool', 'Swimming Pool', 'Bar/Chill-Out Lounge', 'Business Lounge', 'Reading Lounge', 'Salon', 'Card Room']",
       "['Beach Volley Ball Court', 'Automated Car Wash', 'Swimming Pool', 'Laundry', 'Flower Garden', 'Reflexology Park', 'Golf Course', 'Volley Ball Court', 'Salon']",
       "['Swimming Pool', 'Lounge', 'Aerobics Centre', 'Terrace Garden', 'Piped Gas', 'Squash Court', 'Gazebo', 'Wi-Fi Connectivity', 'Sun Deck']",
       '[\'Grocery Shop\', \'Community Hall\', \'Sewage Treatment Plant\', \'Rain Water Harvesting\', \'Gated Community\', \'Gymnasium\', \'Landscape Garden\', "Children\'s Play Area", \'Internal Street Lights\']',
       '[\'Swimming Pool\', \'Fountain\', \'Sun Deck\', \'Amphitheatre\', \'Yoga/Meditation Area\', \'Club House\', \'Gated Community\', \'Landscape Garden\', "Children\'s Play Area"]',
       '[\'Shopping Centre\', \'Community Hall\', \'Sewage Treatment Plant\', \'24x7 Security\', \'Club House\', "Children\'s Play Area", \'Internal Street Lights\', \'Fire Fighting Systems\']',
       "['Swimming Pool', 'Waiting Lounge', 'Creche/Day care', 'Sun Deck', 'Lawn Tennis Court', 'Toddler Pool', 'Basketball Court', 'Badminton Court', 'Entrance Lobby']",
       "['Swimming Pool', 'Gazebo', 'Amphitheatre', 'Basketball Court', 'Badminton Court', 'Multipurpose Hall', 'Yoga/Meditation Area', 'Jogging Track', 'Gymnasium']",
       "['Bowling Alley', 'Mini Theatre', 'Concierge Service', 'Swimming Pool', 'Lounge', 'Bar/Chill-Out Lounge', 'Cigar Lounge', 'Changing Area', 'Salon']",
       '[\'Community Hall\', \'Sewage Treatment Plant\', \'Rain Water Harvesting\', \'Club House\', \'24/7 Power Backup\', \'Gated Community\', \'24/7 Water Supply\', "Children\'s Play Area", \'Garbage Disposal\']',
       "['Foosball', 'Infinity Pool', 'Swimming Pool', 'Football', 'Jacuzzi', 'Cricket Pitch', 'Sun Deck', 'Lawn Tennis Court', 'Amphitheatre']",
       "['Swimming Pool', 'Theater Home', 'School', 'Solar Lighting', 'Restaurant', 'Terrace Garden', 'Jacuzzi', 'Piped Gas', 'Squash Court']",
       "['Swimming Pool', 'Theater Home', 'Bar/Chill-Out Lounge', 'Cigar Lounge', 'Reading Lounge', 'Reflexology Park', 'Golf Course', 'Changing Area', 'School']",
       "['Community Hall', 'Club House', 'Landscape Garden']",
       "['Swimming Pool', 'Theatre', 'Wi-Fi Connectivity', 'Cafeteria', 'Billiards', 'Lawn Tennis Court', 'Video Door Security', 'Multipurpose Court', 'Amphitheatre']",
       "['Swimming Pool', 'Football', 'Bar/Chill-Out Lounge', 'Flower Garden', 'Reading Lounge', 'Golf Course', 'Conference room', 'School', 'Salon']",
       "['Swimming Pool', 'Bar/Chill-Out Lounge', 'School', 'Restaurant', 'Spa', 'Squash Court', 'Theatre', 'Cafeteria', 'Fountain']",
       "['Swimming Pool', 'Changing Area', 'School', 'Card Room', 'Restaurant', 'Sauna', 'Jacuzzi', 'Piped Gas', 'Steam Room']",
       "['Mini Theatre', 'Swimming Pool', 'Theater Home', 'Business Lounge', 'Laundry', 'Changing Area', 'School', 'Salon', 'RO System']",
       "['Swimming Pool', 'Reading Lounge', 'Reflexology Park', 'Golf Course', 'Aerobics Centre', 'Sauna', 'Jacuzzi', 'Steam Room', 'Creche/Day care']",
       "['Swimming Pool', 'Golf Course', 'Changing Area', 'School', 'Restaurant', 'High Speed Elevators', 'Piped Gas', 'Steam Room', 'Squash Court']",
       "['Automated Car Wash', 'Concierge Service', 'Swimming Pool', 'Football', 'Bar/Chill-Out Lounge', 'Reading Lounge', 'Golf Course', 'Volley Ball Court', 'Salon']",
       "['Swimming Pool', 'Changing Area', 'School', 'Salon', 'ATM', 'Aerobics Centre', 'Card Room', 'Solar Water Heating', 'Waiting Lounge']",
       "['Milk Booth', 'Manicured Garden', 'Swimming Pool', 'Football', 'Flower Garden', 'School', 'Restaurant', 'Pergola', 'Skating Rink']",
       "['Clinic', 'Swimming Pool', 'School', 'Piped Gas', 'Creche/Day care', 'Theatre', 'Shopping Centre', 'Lawn Tennis Court', 'Jogging Track']",
       "['Swimming Pool', 'Skating Rink', 'Grocery Shop', 'Gazebo', 'Cricket Pitch', 'Lawn Tennis Court', 'Amphitheatre', 'Basketball Court', 'Badminton Court']",
       "['Mini Theatre', 'Swimming Pool', 'Theater Home', 'Football', 'Bar/Chill-Out Lounge', 'Flower Garden', 'Reading Lounge', 'Golf Course', 'Changing Area']",
       "['Swimming Pool', 'Aerobics Centre', 'Barbecue', 'Restaurant', 'Pergola', 'Spa', 'Pool Table', 'Cafeteria', 'Sun Deck']",
       "['Swimming Pool', 'Reflexology Park', 'Barbecue', 'Terrace Garden', 'Gazebo', 'Fountain', 'Sun Deck', 'Amphitheatre', 'Power Back up Lift']",
       "['Swimming Pool', 'Bar/Chill-Out Lounge', 'Reading Lounge', 'Reflexology Park', 'Card Room', 'Barbecue', 'Restaurant', 'Sauna', 'Spa']",
       "['Bowling Alley', 'Concierge Service', 'Swimming Pool', 'Lounge', 'Medical Centre', 'Laundry', 'Flower Garden', 'Reflexology Park', 'Golf Course']",
       "['Concierge Service', 'Swimming Pool', 'Lounge', 'Golf Course', 'Changing Area', 'Aerobics Centre', 'Restaurant', 'High Speed Elevators', 'Waiting Lounge']",
       "['Bowling Alley', 'Swimming Pool', 'Football', 'Restaurant', 'Waiting Lounge', 'Piped Gas', 'Water Softener Plant', 'Creche/Day care', 'Squash Court']",
       '[\'Yoga/Meditation Area\', \'Gated Community\', "Children\'s Play Area"]',
       "['Food Court', 'Swimming Pool', 'Reading Lounge', 'Aerobics Centre', 'Restaurant', 'Water Softener Plant', 'Property Staff', 'Banquet Hall', 'Library']",
       "['Swimming Pool', 'Water Softener Plant', 'Theatre', 'Shopping Centre', 'Video Door Security', 'Multipurpose Court', 'Vastu Compliant', 'Multipurpose Hall', 'Yoga/Meditation Area']",
       "['Manicured Garden', 'Bus Shelter', 'Clinic', 'Natural Pond', 'Car wash area', 'Swimming Pool', 'Bar/Chill-Out Lounge', 'Medical Centre', 'Reading Lounge']",
       "['Swimming Pool', 'Pergola', 'Piped Gas', 'Grocery Shop', 'Cafeteria', 'Fountain', 'Sun Deck', 'Lawn Tennis Court', 'Multipurpose Court']",
       "['Swimming Pool', 'School', 'Aerobics Centre', 'Restaurant', 'Pergola', 'Waiting Lounge', 'Sauna', 'Steam Room', 'Squash Court']",
       "['Swimming Pool', 'Flower Garden', 'School', 'Solar Lighting', 'Card Room', 'Solar Water Heating', 'Restaurant', 'Terrace Garden', 'Piped Gas']",
       "['Swimming Pool', 'Golf Course', 'ATM', 'Restaurant', 'Waiting Lounge', 'Cafeteria', 'Shopping Centre', 'Video Door Security', 'Multipurpose Court']",
       "['School', 'High Speed Elevators', 'Creche/Day care', 'Shopping Centre', 'Cricket Pitch', 'Amphitheatre', 'Earthquake Resistant', 'Power Back up Lift', 'Party Lawn']",
       "['Infinity Pool', 'Swimming Pool', 'Salon', 'Aerobics Centre', 'Card Room', 'Restaurant', 'Terrace Garden', 'Pergola', 'Sauna']",
       "['Doctor on Call', 'Bus Shelter', 'Food Court', 'Swimming Pool', 'Football', 'Bar/Chill-Out Lounge', 'Business Lounge', 'Medical Centre', 'Flower Garden']",
       "['Swimming Pool', 'ATM', 'Creche/Day care', 'Grocery Shop', 'Property Staff', 'Billiards', 'Lawn Tennis Court', 'Video Door Security', 'Multipurpose Court']",
       "['Swimming Pool', 'Restaurant', 'High Speed Elevators', 'Piped Gas', 'Property Staff', 'Cafeteria', 'Fountain', 'Sun Deck', 'Lawn Tennis Court']",
       "['Manicured Garden', 'Swimming Pool', 'Grocery Shop', 'Gazebo', 'Fountain', 'Cricket Pitch', 'Basketball Court', 'Yoga/Meditation Area', 'CCTV Camera Security']",
       "['Clinic', 'Swimming Pool', 'Theater Home', 'School', 'Aerobics Centre', 'Card Room', 'Restaurant', 'Pergola', 'High Speed Elevators']",
       "['Swimming Pool', 'School', 'Spa', 'Squash Court', 'Property Staff', 'Library', 'Cricket Pitch', 'Lawn Tennis Court', 'Multipurpose Court']",
       '[\'Yoga/Meditation Area\', \'Sewage Treatment Plant\', \'CCTV Camera Security\', \'Jogging Track\', \'24x7 Security\', \'Gymnasium\', \'24/7 Water Supply\', \'Landscape Garden\', "Children\'s Play Area"]',
       "['Swimming Pool', 'School', 'Wi-Fi Connectivity', 'Property Staff', 'Amphitheatre', 'Yoga/Meditation Area', 'Rain Water Harvesting', 'Club House', '24/7 Power Backup']",
       "['Doctor on Call', 'Swimming Pool', 'Golf Course', 'Restaurant', 'Sauna', 'Jacuzzi', 'Spa', 'Grocery Shop', 'Gazebo']",
       "['Bus Shelter', 'Swimming Pool', 'Lounge', 'Golf Course', 'Changing Area', 'Gazebo', 'Cafeteria', 'Fountain', 'Video Door Security']",
       "['Valet Parking', 'Swimming Pool', 'Football', 'Laundry', 'Flower Garden', 'School', 'ATM', 'Card Room', 'Jacuzzi']",
       "['Swimming Pool', 'Football', 'Bar/Chill-Out Lounge', 'Salon', 'Terrace Garden', 'High Speed Elevators', 'Spa', 'Cafeteria', 'Sun Deck']",
       "['Swimming Pool', 'School', 'Pergola', 'Wi-Fi Connectivity', 'Property Staff', 'Cafeteria', 'Shopping Centre', 'Library', 'Sun Deck']",
       "['Swimming Pool', 'Salon', 'Banquet Hall', 'Lawn Tennis Court', 'Amphitheatre', 'Jogging Track', '24x7 Security', 'Club House', '24/7 Power Backup']",
       "['Swimming Pool', 'Golf Course', 'Card Room', 'Piped Gas', 'Squash Court', 'Billiards', 'Video Door Security', 'Basketball Court', 'Entrance Lobby']",
       "['Swimming Pool', 'Football', 'Bar/Chill-Out Lounge', 'Reading Lounge', 'Golf Course', 'Restaurant', 'Terrace Garden', 'Spa', 'Skating Rink']",
       "['Mini Theatre', 'Automated Car Wash', 'Swimming Pool', 'Business Lounge', 'Salon', 'Card Room', 'Waiting Lounge', 'Sauna', 'Steam Room']",
       "['Natural Pond', 'Swimming Pool', 'Skating Rink', 'Gazebo', 'Cafeteria', 'Billiards', 'Fountain', 'Shopping Centre', 'Cricket Pitch']",
       "['Automated Car Wash', 'Acupressure Park', 'Swimming Pool', 'Golf Course', 'Salon', 'Card Room', 'Restaurant', 'High Speed Elevators', 'Waiting Lounge']",
       "['Bus Shelter', 'Swimming Pool', 'School', 'Card Room', 'Pergola', 'High Speed Elevators', 'Sauna', 'Steam Room', 'Water Softener Plant']",
       "['Swimming Pool', 'Football', 'Bar/Chill-Out Lounge', 'Laundry', 'Reading Lounge', 'Golf Course', 'Conference room', 'Card Room', 'Restaurant']",
       "['Swimming Pool', 'School', 'Sauna', 'Steam Room', 'Billiards', 'Fountain', 'Shopping Centre', 'Lawn Tennis Court', 'Earthquake Resistant']",
       "['Valet Parking', 'Food Court', 'Swimming Pool', 'Business Lounge', 'School', 'Restaurant', 'Pergola', 'Grocery Shop', 'Squash Court']",
       "['Mini Theatre', 'Infinity Pool', 'Lounge', 'Restaurant', 'High Speed Elevators', 'Sauna', 'Jacuzzi', 'Spa', 'Water Softener Plant']",
       "['Bus Shelter', 'Infinity Pool', 'Swimming Pool', 'Bar/Chill-Out Lounge', 'Reflexology Park', 'Aerobics Centre', 'Restaurant', 'Terrace Garden', 'High Speed Elevators']",

In [51]:
import re
def extract_list(s):
    return re.findall(r"'(.*?)'", s)

df['TopFacilities'] = df['TopFacilities'].apply(extract_list)

In [52]:
pd.set_option('display.max_colwidth',None)
df['PropertySubName']

0                2, 3, 4 BHK Apartment in Sector 113, Gurgaon
1                   3, 4 BHK Apartment in Sector 111, Gurgaon
2      Land, 3, 4 BHK Independent Floor in Sector 63, Gurgaon
3                2, 3, 4 BHK Apartment in Sector 108, Gurgaon
4             2, 3 BHK Independent Floor in Sector 93 Gurgaon
                                ...
242             2, 3, 4 BHK Apartment in DLF Phase 5, Gurgaon
243                  1, 2 BHK Apartment in Sector 86, Gurgaon
244           2, 3, 4, 5 BHK Apartment in Sector 103, Gurgaon
245                 2, 3 BHK Apartment in Sector 37D, Gurgaon
246                  2, 3 BHK Apartment in Sector 84, Gurgaon
Name: PropertySubName, Length: 246, dtype: object

In [53]:
df['NearbyLocations']

0                                                               ['Bajghera Road', 'Palam Vihar Halt', 'DPSG Palam Vihar', 'Park Hospital', 'Gurgaon Railway Station']
1                      ['DPSG Palam Vihar Gurugram', 'The NorthCap University', 'Park Hospital, Palam Vihar', 'Pacific D21 Mall', 'Palam Vihar Halt Railway Station']
2      ['AIPL Business Club Sector 62', 'Heritage Xperiential Learning School', 'CK Birla Hospital', 'Paras Trinity Mall Sector 63', 'Rapid Metro Station Sector 56']
3                                                              ['The Shikshiyan School', 'WTC Plaza', 'Luxus Haritma Resort', 'BSF Golf Course', 'Dwarka Expressway']
4                         ['Pranavananda Int. School', 'DLF Site central office', 'Holiday Inn Gurugram Sector 90', 'Krishna Hospital', 'Royal Institute Of Science']
                                                                                    ...
242                                       ['Sector 42-43 Metro Station', 'Paras Hospital', 'Ardee Mall', 'Zooper India Trampoline Park', 'DLF Golf and Country Club']
243     ['Aarvy Healthcare Super Speciality', "St. Xavier's High School", 'Minda Industries  Corporate Office', 'Sapphire 83 Mall', 'Rampura Flyover, Naurangpur Rd']
244                                ['Dwarka Expressway', 'S N International School', 'InfinityS Badminton Academy', 'Gurgaon Railway Station', 'Gurgaon Dreamz Mall']
245                                                            ['Suncity School', 'Gurugram Road', 'Dwarka Expressway', 'Sunrise University', 'Delhi Jaipur Highway']
246                                                  ['Sector 84 Road', 'Delhi Public School, Sector 84', 'Dwarka Expy', 'Sapphire 83 Mall', 'Hyatt Regency Gurgaon']
Name: NearbyLocations, Length: 246, dtype: object

In [54]:
df['LocationAdvantages']

0                                                                                             {'Bajghera Road': '800 Meter', 'Palam Vihar Halt': '2.5 KM', 'DPSG Palam Vihar': '3.1 KM', 'Park Hospital': '3.1 KM', 'Gurgaon Railway Station': '4.9 KM', 'The NorthCap University': '5.4 KM', 'Dwarka Expy': '1.2 KM', 'Hyatt Place Gurgaon Udyog Vihar': '7.7 KM', 'Dwarka Sector 21, Metro Station': '7.2 KM', 'Pacific D21 Mall': '7.4 KM', 'Indira Gandhi International Airport': '14.7 KM', 'Hamoni Golf Camp': '6.2 KM', 'Fun N Food Waterpark': '8.8 KM', 'Accenture DDC5': '9 KM'}
1                                                                                      {'DPSG Palam Vihar Gurugram': '1.4 Km', 'The NorthCap University': '4.4 Km', 'Park Hospital, Palam Vihar': '1.4 Km', 'Pacific D21 Mall': '8.2 Km', 'Palam Vihar Halt Railway Station': '1.2 Km', 'Dwarka Sector 21 Metro Station': '8.1 Km', 'Dwarka Expressway': '450 m', 'Fun N Food Water Park': '8.1 Km', 'Indira Gandhi International Airport': '14.1 Km', 'Tau DeviLal Sports Complex': '11.2 Km', 'Hamoni Golf Camp': '5 Km', 'Hyatt Place': '6.1 Km', 'Altrade Business Centre': '11.2 Km'}
2                                                       {'AIPL Business Club Sector 62': '2.7 Km', 'Heritage Xperiential Learning School': '2 Km', 'CK Birla Hospital': '2.5 Km', 'Paras Trinity Mall Sector 63': '3.5 Km', 'Rapid Metro Station Sector 56': '3.8 Km', 'De Adventure Park': '6.8 Km', 'Golf Course Ext Rd': '99 Meter', 'DoubleTree by Hilton Hotel Gurgaon': '3.6 Km', 'KIIT College of Engineering Sohna Road': '8.4 Km', 'Mehrauli-Gurgaon Road': '11.8 Km', 'Indira Gandhi International Airport': '21.1 Km', 'Nirvana Rd': '160 Meter', 'TERI Golf Course': '8.7 Km'}
3                                                                                                                                                                                           {'The Shikshiyan School': '2.9 KM', 'WTC Plaza': '4 KM', 'Luxus Haritma Resort': '4.2 KM', 'BSF Golf Course': '4.7 KM', 'Dwarka Expressway': '5.1 Km', 'Rions Hospital': '5.6 Km', 'Gurgaon': '5.9 KM', 'The NorthCap University': '9.2 KM', 'Dwarka Sector 21': '9.9 KM', 'Nehru Stadium': '10.7  KM', 'Fun N Food WaterPark': '12.1 KM', 'IGI Airport': '19.3 Km', 'Vasant Kunj': '20.8 KM'}
4                                                                                                                                                                                                                           {'Pranavananda Int. School': '450 m', 'DLF Site central office': '1.2 Km', 'Holiday Inn Gurugram Sector 90': '2 Km', 'Krishna Hospital': '2.3 Km', 'Royal Institute Of Science': '2.4 Km', 'Sapphire 83 Mall': '6.3 Km', 'NH48': '6.9 Km', 'Garhi Harsaru Junction': '7.2 Km', 'Manesar Golf Course': '7.3 Km', 'AapnoGhar': '9.6 Km', 'IGI Airport': '31 Km'}
                                                                                                                                                                                                                                                                                              ...
242                                                                                                        {'Sector 42-43 Metro Station': '1.8 Km', 'Paras Hospital': '2 Km', 'Ardee Mall': '2.6 Km', 'Zooper India Trampoline Park': '3.1 Km', 'DLF Golf and Country Club': '3.7 Km', 'The Shri Ram School Aravali': '3.9 Km', 'Taj City Centre Gurugram': '4 Km', 'Appu Ghar Water Park': '4.7 Km', 'PVR Drive in Theatre': '7.4 Km', 'Golf Course Ext Rd': '7.6 Km', 'Duke Horse Riding Club': '8 Km', 'Surajgarh Gurgaon': '9.2 Km', 'Indira Gandhi International Airport': '15.2 Km'}
243                                                                                                                                                                                          {'Aarvy Healthcare Super Speciality': '1.8 KM', "St. Xavier's High School": '2 KM', 'Minda Industries  Corporate Office': '3.1 KM', 'Sapphire 83 Mall': '3.2 KM', 'Rampura Flyover, Naurangpur Rd': '3.7 KM', 'Nakhrola Stadium': '3.8 KM', 'Manesar toll plaza - Kherki Daula': '6.1 KM', 'Imt Manesar, Gurugram': '7.7 KM', 'Holiday Inn': '3 km', 'Indira Gandhi Intl Airport': '29.4 Km'}
244    {'Dwarka Expressway': '1.2 Km', 'S N International School': '1.2 Km', 'InfinityS Badminton Academy': '3.1 Km', 'Gurgaon Railway Station': '3.3 Km', 'Gurgaon Dreamz Mall': '4.6 Km', 'Metro Hospital, Palam Vihar': '6.4 Km', 'Delhi Jaipur Expressway': '7.7 Km', 'HUDA Market, Sector 14': '7.9 Km', 'F9 Go Karting Gurgaon': '8.4 Km', 'The NorthCap University': '8.8 Km', 'infinity Business Park': '9.4 Km', 'Hero Honda Chowk': '9.4 Km', 'SkyJumper Trampoline Park Gurgaon': '10.1 Km', 'Huda Metro Station': '11.6 Km', 'Indira Gandhi International Airport': '21.7 Km'}
245                                                                                                                                                                                                                                                                                                  {'Suncity School': '0.2 Km', 'Gurugram Road': '1 Km', 'Dwarka Expressway': '1.5 Km', 'Sunrise University': '4 Km', 'Delhi Jaipur Highway': '5 Km', 'Sethi Hospital': '5.5 Km', 'Gurgaon Dreamz Mall': '7 Km', 'Gurgaon Railway Station': '7 Km', 'Infinity Business Park': '10.5 Km'}
246                                                                                                                                                 {'Sector 84 Road': '600 Meter', 'Delhi Public School, Sector 84': '1.3 KM', 'Dwarka Expy': '2 Km', 'Sapphire 83 Mall': '2.7 Km', 'Hyatt Regency Gurgaon': '3.9 KM', 'Aarvy Hospital': '3.9 KM', 'AapnoGhar': '6 KM', 'Garhi Harsaru Junction': '7.3 KM', 'DPG Degree College': '10.4 KM', 'Skyview Corporate Park': '12.4 KM', 'Indira Gandhi Intl Airport': '28.1 KM', 'Manesar Golf Course': '8.4 KM', 'Nakhrola Stadium': '5.2 KM'}
Name: LocationAdvantages, Length: 246, dtype: object

In [55]:
df['PriceDetails']

0                                                                                                                                                     {'2 BHK': {'building_type': 'Apartment', 'area_type': 'Carpet Area', 'area': '1,370 sq.ft.', 'price-range': '₹ 2 - 2.4 Cr'}, '3 BHK': {'building_type': 'Apartment', 'area_type': 'Carpet Area', 'area': '1,850 - 2,050 sq.ft.', 'price-range': '₹ 2.25 - 3.59 Cr'}, '4 BHK': {'building_type': 'Apartment', 'area_type': 'Carpet Area', 'area': '2,600 sq.ft.', 'price-range': '₹ 3.24 - 4.56 Cr'}}
1                                                                                                                                                                                                                                                          {'3 BHK': {'building_type': 'Apartment', 'area_type': 'Super Built-up Area', 'area': '1,605 - 2,170 sq.ft.', 'price-range': '₹ 2.2 - 3.03 Cr'}, '4 BHK': {'building_type': 'Apartment', 'area_type': 'Super Built-up Area', 'area': '2,248 - 2,670 sq.ft.', 'price-range': '₹ 3.08 - 3.73 Cr'}}
2                                                                                                             {'3 BHK': {'building_type': 'Independent Floor', 'area_type': 'Super Built-up Area', 'area': '1,800 - 3,150 sq.ft.', 'price-range': '₹ 2.43 - 15.75 Cr'}, '4 BHK': {'building_type': 'Independent Floor', 'area_type': 'Super Built-up Area', 'area': '2,750 - 4,500 sq.ft.', 'price-range': '₹ 3.36 - 22.5 Cr'}, 'Land': {'building_type': '', 'area_type': 'Plot Area', 'area': '500 - 4,329 sq.ft.', 'price-range': '₹ 2.05 - 41.13 Cr'}}
3                                                                                                          {'2 BHK': {'building_type': 'Apartment', 'area_type': 'Super Built-up Area', 'area': '1,381 - 1,692 sq.ft.', 'price-range': '₹ 1.55 - 3.21 Cr'}, '3 BHK': {'building_type': 'Apartment', 'area_type': 'Super Built-up Area', 'area': '1,711 - 2,343 sq.ft.', 'price-range': '₹ 1.76 - 4.79 Cr'}, '4 BHK': {'building_type': 'Apartment', 'area_type': 'Super Built-up Area', 'area': '2,423 - 2,963 sq.ft.', 'price-range': '₹ 2.5 - 6.06 Cr'}}
4                                                                                                                                                                                                                                                        {'2 BHK': {'building_type': 'Independent Floor', 'area_type': 'Carpet Area', 'area': '981 - 1,118 sq.ft.', 'price-range': '₹ 93.01 L - 1.06 Cr'}, '3 BHK': {'building_type': 'Independent Floor', 'area_type': 'Carpet Area', 'area': '1,235 - 1,530 sq.ft.', 'price-range': '₹ 1.12 - 1.45 Cr'}}
                                                                                                                                                                                                                                                                              ...
242                                                                                                                                                      {'2 BHK': {'building_type': 'Apartment', 'area_type': 'Super Built-up Area', 'area': '964 sq.ft.', 'price-range': '₹ 1.35 Cr'}, '3 BHK': {'building_type': 'Apartment', 'area_type': 'Super Built-up Area', 'area': '1,127 sq.ft.', 'price-range': '₹ 1.55 Cr'}, '4 BHK': {'building_type': 'Apartment', 'area_type': 'Super Built-up Area', 'area': '1,562 sq.ft.', 'price-range': '₹ 2.15 Cr'}}
243                                                                                                                                                                                                                                                                              {'1 BHK': {'building_type': 'Apartment', 'area_type': 'Carpet Area', 'area': '335 - 398 sq.ft.', 'price-range': '₹ 23.45 - 27.86 L'}, '2 BHK': {'building_type': 'Apartment', 'area_type': 'Carpet Area', 'area': '500 - 625 sq.ft.', 'price-range': 'Price on Request'}}
244    {'2 BHK': {'building_type': 'Apartment', 'area_type': 'Super Built-up Area', 'area': '1,450 sq.ft.', 'price-range': '₹ 80 L'}, '3 BHK': {'building_type': 'Apartment', 'area_type': 'Super Built-up Area', 'area': '1,991 sq.ft.', 'price-range': '₹ 1 Cr'}, '4 BHK': {'building_type': 'Apartment', 'area_type': 'Super Built-up Area', 'area': '2,639 - 4,711 sq.ft.', 'price-range': '₹ 1.2 - 2.14 Cr'}, '5 BHK': {'building_type': 'Apartment', 'area_type': 'Super Built-up Area', 'area': '4,731 sq.ft.', 'price-range': 'Price on Request'}}
245                                                                                                                                                                                                                                                       {'2 BHK': {'building_type': 'Apartment', 'area_type': 'Super Built-up Area', 'area': '1,000 - 1,079 sq.ft.', 'price-range': 'Price on Request'}, '3 BHK': {'building_type': 'Apartment', 'area_type': 'Super Built-up Area', 'area': '1,225 - 1,865 sq.ft.', 'price-range': 'Price on Request'}}
246                                                                                                                                                                                                                                                        {'2 BHK': {'building_type': 'Apartment', 'area_type': 'Super Built-up Area', 'area': '1,320 - 1,425 sq.ft.', 'price-range': 'Price on Request'}, '3 BHK': {'building_type': 'Apartment', 'area_type': 'Super Built-up Area', 'area': '1,750 - 1,890 sq.ft.', 'price-range': '₹ 1.1 - 1.19 Cr'}}
Name: PriceDetails, Length: 246, dtype: object

In [56]:
df['FacilitiesStr']=df['TopFacilities'].apply(" ".join)

In [57]:
df['TopFacilities'][0]

['Swimming Pool',
 'Salon',
 'Restaurant',
 'Spa',
 'Cafeteria',
 'Sun Deck',
 '24x7 Security',
 'Club House',
 'Gated Community']

In [58]:
tfidf_vectorizer=TfidfVectorizer(stop_words='english',ngram_range=(1,2))

In [59]:
tfidf_matrix=tfidf_vectorizer.fit_transform(df['FacilitiesStr'])

In [60]:
tfidf_matrix.toarray()[0]

array([0.        , 0.        , 0.        , 0.18809342, 0.18809342,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.16873099, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.27811185, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.17445059, 0.17445059,
       0.15589841, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.16355699, 0.29372893, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.18084455, 0.18084455,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.17445059, 0.        , 0.24773259, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.06440364,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.2659983 , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.12932284, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.21010446, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.16522746,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.25610081, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.15177345,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.21412748, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.14918792,
       0.29372893, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.16355699, 0.16355699, 0.        ,
       0.        , 0.        , 0.06493586, 0.06493586, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        ])

In [61]:
cosine_sim1=cosine_similarity(tfidf_matrix,tfidf_matrix)

In [62]:
list(enumerate(cosine_sim1[24]))

[(0, np.float64(0.10737203185630836)),
 (1, np.float64(0.09988347503176563)),
 (2, np.float64(0.013204845679428978)),
 (3, np.float64(0.10222839481447835)),
 (4, np.float64(0.08331852851019068)),
 (5, np.float64(0.08734074924422512)),
 (6, np.float64(0.06626700484979536)),
 (7, np.float64(0.009003786322744383)),
 (8, np.float64(0.20521615574040783)),
 (9, np.float64(0.16791694858343884)),
 (10, np.float64(0.2092065086430902)),
 (11, np.float64(0.010895043067047583)),
 (12, np.float64(0.19490105096585403)),
 (13, np.float64(0.023239646071709266)),
 (14, np.float64(0.010132892640916555)),
 (15, np.float64(0.2698703142849541)),
 (16, np.float64(0.1134652595930599)),
 (17, np.float64(0.0)),
 (18, np.float64(0.0)),
 (19, np.float64(0.013153995373600711)),
 (20, np.float64(0.1442599253725625)),
 (21, np.float64(0.011896400015719063)),
 (22, np.float64(0.11112841943110885)),
 (23, np.float64(0.08061955572528696)),
 (24, np.float64(1.0000000000000002)),
 (25, np.float64(0.10156076201171532)),
 (26, np.float64(0.10359528336016299)),
 (27, np.float64(0.016075344584182305)),
 (28, np.float64(0.03081556012045712)),
 (29, np.float64(0.07473828063161152)),
 (30, np.float64(0.010611942263169201)),
 (31, np.float64(0.08370974067260949)),
 (32, np.float64(0.02419481664553222)),
 (33, np.float64(0.057603439207786655)),
 (34, np.float64(0.14257212374280026)),
 (35, np.float64(0.01812586909277865)),
 (36, np.float64(0.010753317398536133)),
 (37, np.float64(0.07718766840315158)),
 (38, np.float64(0.11087411534998161)),
 (39, np.float64(0.08056488061236408)),
 (40, np.float64(0.16642652694348564)),
 (41, np.float64(0.06290228695945081)),
 (42, np.float64(0.05483837137080623)),
 (43, np.float64(0.030450280293664922)),
 (44, np.float64(0.06905324831323514)),
 (45, np.float64(0.0685466901039095)),
 (46, np.float64(0.14822510756366786)),
 (47, np.float64(0.3007188627922356)),
 (48, np.float64(0.06347889132377914)),
 (49, np.float64(0.017269760299603597)),
 (50, np.float64(0.06939893731733052)),
 (51, np.float64(0.09666511966996957)),
 (52, np.float64(0.09772977678772726)),
 (53, np.float64(0.08907974949144046)),
 (54, np.float64(0.36180132151388794)),
 (55, np.float64(0.08522327123960387)),
 (56, np.float64(0.1124286716039634)),
 (57, np.float64(0.1073886954470101)),
 (58, np.float64(0.01015237066342388)),
 (59, np.float64(0.06822482518347842)),
 (60, np.float64(0.019108886706045228)),
 (61, np.float64(0.1269109137791823)),
 (62, np.float64(0.0)),
 (63, np.float64(0.0846954637058257)),
 (64, np.float64(0.0)),
 (65, np.float64(0.09482085523022908)),
 (66, np.float64(0.02502980934020262)),
 (67, np.float64(0.0768582751113696)),
 (68, np.float64(0.0)),
 (69, np.float64(0.226580200915205)),
 (70, np.float64(0.058727105406788174)),
 (71, np.float64(0.009962430084623136)),
 (72, np.float64(0.0)),
 (73, np.float64(0.04364493356225888)),
 (74, np.float64(0.027382155803609785)),
 (75, np.float64(0.17972033384741407)),
 (76, np.float64(0.1124270639349987)),
 (77, np.float64(0.08394469132033472)),
 (78, np.float64(0.04766841534757884)),
 (79, np.float64(0.07525109648801148)),
 (80, np.float64(0.016577109172089672)),
 (81, np.float64(0.06409408302517758)),
 (82, np.float64(0.010888759727518071)),
 (83, np.float64(0.03739202225597624)),
 (84, np.float64(0.11229790895466714)),
 (85, np.float64(0.08059750725980913)),
 (86, np.float64(0.10775072959113852)),
 (87, np.float64(0.08261188420659028)),
 (88, np.float64(0.16519491020813953)),
 (89, np.float64(0.010611052945272141)),
 (90, np.float64(0.010922892532608112)),
 (91, np.float64(0.05414643673342009)),
 (92, np.float64(0.0)),
 (93, np.float64(0.01675558948663847)),
 (94, np.float64(0.031157369328511077)),
 (95, np.float64(0.1343683274106298)),
 (96, np.float64(0.09949953357503)),
 (97, np.float64(0.11061159857472197)),
 (98, np.float64(0.060018304941302614)),
 (99, np.float64(0.01811947798133761)),
 (100, np.float64(0.06595906695483542)),
 (101, np.float64(0.1033485565436168)),
 (102, np.float64(0.01743021985471953)),
 (103, np.float64(0.02413084979667933)),
 (104, np.float64(0.0901282133771623)),
 (105, np.float64(0.08763672425770717)),
 (106, np.float64(0.06531708295934033)),
 (107, np.float64(0.22521033707173443)),
 (108, np.float64(0.0)),
 (109, np.float64(0.009751821600583752)),
 (110, np.float64(0.06020832834132512)),
 (111, np.float64(0.010793699333709692)),
 (112, np.float64(0.06774358994993451)),
 (113, np.float64(0.10205410777512323)),
 (114, np.float64(0.08234254679466013)),
 (115, np.float64(0.01738717484430846)),
 (116, np.float64(0.11028621613962783)),
 (117, np.float64(0.03257211226128835)),
 (118, np.float64(0.16248592956794056)),
 (119, np.float64(0.2996830743164912)),
 (120, np.float64(0.05712817785773203)),
 (121, np.float64(0.09576295240750021)),
 (122, np.float64(0.08274113422918236)),
 (123, np.float64(0.05992655929359625)),
 (124, np.float64(0.06829302124929867)),
 (125, np.float64(0.11623121852885115)),
 (126, np.float64(0.013638532800403249)),
 (127, np.float64(0.13833561106538664)),
 (128, np.float64(0.060609840072856705)),
 (129, np.float64(0.00902259228041417)),
 (130, np.float64(0.026228414725565856)),
 (131, np.float64(0.051551680290672114)),
 (132, np.float64(0.08813130574112955)),
 (133, np.float64(0.010848235900179245)),
 (134, np.float64(0.0)),
 (135, np.float64(0.10122019189019137)),
 (136, np.float64(0.0887037166702273)),
 (137, np.float64(0.08310607858654838)),
 (138, np.float64(0.027100278820865527)),
 (139, np.float64(0.17742062868521083)),
 (140, np.float64(0.08543787057434926)),
 (141, np.float64(0.023190752447148154)),
 (142, np.float64(0.06806934134748174)),
 (143, np.float64(0.11513462780257887)),
 (144, np.float64(0.030267591560140354)),
 (145, np.float64(0.06740080693535278)),
 (146, np.float64(0.21983359473574815)),
 (147, np.float64(0.01820467941083504)),
 (148, np.float64(0.31851679313936515)),
 (149, np.float64(0.056162620460373056)),
 (150, np.float64(0.1722770611550296)),
 (151, np.float64(0.03189276105011533)),
 (152, np.float64(0.0871287804451884)),
 (153, np.float64(0.0092138870672001)),
 (154, np.float64(0.026158613877330546)),
 (155, np.float64(0.0)),
 (156, np.float64(0.029978296241930748)),
 (157, np.float64(0.06433216952962732)),
 (158, np.float64(0.08216129358554622)),
 (159, np.float64(0.014637505169704763)),
 (160, np.float64(0.0713971739628487)),
 (161, np.float64(0.009625041060271892)),
 (162, np.float64(0.0963738676479875)),
 (163, np.float64(0.09619726895186563)),
 (164, np.float64(0.3368930191716782)),
 (165, np.float64(0.07697427603318031)),
 (166, np.float64(0.08048340980994262)),
 (167, np.float64(0.019717555202865396)),
 (168, np.float64(0.0)),
 (169, np.float64(0.08429775433734318)),
 (170, np.float64(0.12429929296023652)),
 (171, np.float64(0.19964614268333797)),
 (172, np.float64(0.07182292919497749)),
 (173, np.float64(0.013910672440252124)),
 (174, np.float64(0.006908701330547404)),
 (175, np.float64(0.20355616146955774)),
 (176, np.float64(0.3878230277189635)),
 (177, np.float64(0.0799282095435659)),
 (178, np.float64(0.07840833996821639)),
 (179, np.float64(0.0)),
 (180, np.float64(0.006621673690430332)),
 (181, np.float64(0.017160958828440955)),
 (182, np.float64(0.013539509475850763)),
 (183, np.float64(0.07390187345116489)),
 (184, np.float64(0.009304149728704995)),
 (185, np.float64(0.0)),
 (186, np.float64(0.20016236358806136)),
 (187, np.float64(0.06693933174173927)),
 (188, np.float64(0.08185774193935744)),
 (189, np.float64(0.10746250716608591)),
 (190, np.float64(0.08648722780594406)),
 (191, np.float64(0.006170619239885896)),
 (192, np.float64(0.16481823331275214)),
 (193, np.float64(0.012956902043696773)),
 (194, np.float64(0.058684748666968684)),
 (195, np.float64(0.17302723806735223)),
 (196, np.float64(0.22898850351904299)),
 (197, np.float64(0.08401156434245488)),
 (198, np.float64(0.0)),
 (199, np.float64(0.11753432296110858)),
 (200, np.float64(0.013602619793061287)),
 (201, np.float64(0.02487202472537403)),
 (202, np.float64(0.047774773971441975)),
 (203, np.float64(0.006647453103648213)),
 (204, np.float64(0.0)),
 (205, np.float64(0.03449753901872318)),
 (206, np.float64(0.01701629864448389)),
 (207, np.float64(0.008797098573960509)),
 (208, np.float64(0.07208517554780637)),
 (209, np.float64(0.028667752993266325)),
 (210, np.float64(0.07027058352069837)),
 (211, np.float64(0.06470064502562187)),
 (212, np.float64(0.0)),
 (213, np.float64(0.09378119084590147)),
 (214, np.float64(0.01378226763135754)),
 (215, np.float64(0.1775585098389336)),
 (216, np.float64(0.07827213461424165)),
 (217, np.float64(0.0607443716539251)),
 (218, np.float64(0.019011265536904683)),
 (219, np.float64(0.12943605401706568)),
 (220, np.float64(0.028612787240585982)),
 (221, np.float64(0.016737951094431464)),
 (222, np.float64(0.09111051156217712)),
 (223, np.float64(0.010616022809123098)),
 (224, np.float64(0.0853081660848317)),
 (225, np.float64(0.17342522062428894)),
 (226, np.float64(0.16184171190293134)),
 (227, np.float64(0.016164623824251302)),
 (228, np.float64(0.015857067378471673)),
 (229, np.float64(0.021691157685966113)),
 (230, np.float64(0.04000012769475679)),
 (231, np.float64(0.016629952827300995)),
 (232, np.float64(0.07914110875073545)),
 (233, np.float64(0.060693796436476155)),
 (234, np.float64(0.06157449003267431)),
 (235, np.float64(0.09457057413162273)),
 (236, np.float64(0.0179348472655951)),
 (237, np.float64(0.08421345632980137)),
 (238, np.float64(0.06451514621379292)),
 (239, np.float64(0.020924787232396474)),
 (240, np.float64(0.006132644582362644)),
 (241, np.float64(0.017427991194427436)),
 (242, np.float64(0.0)),
 (243, np.float64(0.01848831794678152)),
 (244, np.float64(0.19298576429949532)),
 (245, np.float64(0.061391139355629384))]

In [63]:
cosine_sim1_df=pd.DataFrame(cosine_sim1, columns=df['PropertyName'],index=df['PropertyName'])
cosine_sim1_df

PropertyName,Smartworld One DXP,M3M Crown,Adani Brahma Samsara Vilasa,Sobha City,Signature Global City 93,Whiteland The Aspen,Bestech Altura,Elan The Presidential,Signature Global City 92,Emaar Digihomes,...,BPTP Freedom Park Life,DLF New Town Heights,La Lagune,M3M My Den,Suncity Avenue 102,DLF Princeton Estate,Pyramid Urban Homes 2,Satya The Hermitage,BPTP Spacio,SS The Coralwood
PropertyName,,,,,,,,,,,,,,,,,,,,,
Smartworld One DXP,1.000000,0.010952,0.000000,0.010842,0.036806,0.096062,0.012989,0.116941,0.085819,0.183837,...,0.244367,0.031058,0.027104,0.014879,0.088294,0.035359,0.195214,0.011833,0.086564,0.011073
M3M Crown,0.010952,1.000000,0.019821,0.129633,0.158885,0.019310,0.217009,0.008401,0.041269,0.079922,...,0.009992,0.029455,0.028471,0.087647,0.018411,0.009710,0.022334,0.119042,0.015555,0.009639
Adani Brahma Samsara Vilasa,0.000000,0.019821,1.000000,0.012197,0.010507,0.096746,0.026366,0.104500,0.076589,0.028916,...,0.012914,0.058368,0.014021,0.012589,0.019777,0.057540,0.010695,0.070205,0.038203,0.019628
Sobha City,0.010842,0.129633,0.012197,1.000000,0.010006,0.077337,0.087381,0.063386,0.071482,0.201466,...,0.026931,0.041919,0.166114,0.019328,0.102744,0.036241,0.010671,0.118297,0.086832,0.158070
Signature Global City 93,0.036806,0.158885,0.010507,0.010006,1.000000,0.073581,0.095212,0.008907,0.112510,0.108638,...,0.010594,0.010125,0.130918,0.290571,0.009760,0.065219,0.011839,0.030697,0.016492,0.010219
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
DLF Princeton Estate,0.035359,0.009710,0.057540,0.036241,0.065219,0.000000,0.084823,0.075751,0.010312,0.058219,...,0.075639,0.094322,0.031935,0.051291,0.059493,1.000000,0.060328,0.034949,0.074768,0.086259
Pyramid Urban Homes 2,0.195214,0.022334,0.010695,0.010671,0.011839,0.000000,0.013244,0.152982,0.011859,0.023372,...,0.298773,0.018870,0.011453,0.000000,0.534055,0.060328,1.000000,0.000000,0.000000,0.010898
Satya The Hermitage,0.011833,0.119042,0.070205,0.118297,0.030697,0.000000,0.177992,0.027998,0.120629,0.093933,...,0.018081,0.165572,0.050583,0.185111,0.006183,0.034949,0.000000,1.000000,0.098257,0.032559
BPTP Spacio,0.086564,0.015555,0.038203,0.086832,0.016492,0.045031,0.033451,0.013708,0.080022,0.149621,...,0.074054,0.261542,0.065760,0.038292,0.067489,0.074768,0.000000,0.098257,1.000000,0.062576
SS The Coralwood,0.011073,0.009639,0.019628,0.158070,0.010219,0.046300,0.091479,0.064735,0.010236,0.062434,...,0.060200,0.085137,0.155263,0.013095,0.000000,0.086259,0.010898,0.032559,0.062576,1.000000

In [64]:
cosine_sim1.shape

(246, 246)

In [65]:
df[['PropertyName','PriceDetails']]['PropertyName']

0               Smartworld One DXP
1                        M3M Crown
2      Adani Brahma Samsara Vilasa
3                       Sobha City
4         Signature Global City 93
                  ...
242           DLF Princeton Estate
243          Pyramid Urban Homes 2
244            Satya The Hermitage
245                    BPTP Spacio
246               SS The Coralwood
Name: PropertyName, Length: 246, dtype: object

In [66]:
def recommend_properties(property_name,cosine_sim=cosine_sim1):
    idx=df.index[df['PropertyName']==property_name].tolist()[0]
    sim_score=list(enumerate(cosine_sim1[idx]))
    sim_score=sorted(sim_score,key=lambda x :x[1],reverse=True)
    sim_score=sim_score[1:6]
    proper_indices=[i[0] for i in sim_score]
    recommendations_df=pd.DataFrame({'PropertyName':df['PropertyName'].iloc[proper_indices],
                                     'SimilarityScore':sim_score
                                    })
    return recommendations_df

In [67]:
recommend_properties("DLF The Arbour")

           PropertyName            SimilarityScore
64      Ace Palm Floors   (63, 0.4529382062441955)
217         Yashika 104  (216, 0.4199606322926784)
93       JMS The Nation   (92, 0.4166584649363288)
154       India Rashtra   (153, 0.398954234680194)
0    Smartworld One DXP   (0, 0.38885046199432893)

In [68]:
# Load the dataset
df_appartments = pd.read_csv('appartments.csv').drop(22)

# Function to parse and extract the required features from the PriceDetails column
def refined_parse_modified_v2(detail_str):
    try:
        details = json.loads(detail_str.replace("'", "\""))
    except:
        return {}

    extracted = {}
    for bhk, detail in details.items():
        # Extract building type
        extracted[f'building type_{bhk}'] = detail.get('building_type')

        # Parsing area details
        area = detail.get('area', '')
        area_parts = area.split('-')
        if len(area_parts) == 1:
            try:
                value = float(area_parts[0].replace(',', '').replace(' sq.ft.', '').strip())
                extracted[f'area low {bhk}'] = value
                extracted[f'area high {bhk}'] = value
            except:
                extracted[f'area low {bhk}'] = None
                extracted[f'area high {bhk}'] = None
        elif len(area_parts) == 2:
            try:
                extracted[f'area low {bhk}'] = float(area_parts[0].replace(',', '').replace(' sq.ft.', '').strip())
                extracted[f'area high {bhk}'] = float(area_parts[1].replace(',', '').replace(' sq.ft.', '').strip())
            except:
                extracted[f'area low {bhk}'] = None
                extracted[f'area high {bhk}'] = None

        # Parsing price details
        price_range = detail.get('price-range', '')
        price_parts = price_range.split('-')
        if len(price_parts) == 2:
            try:
                extracted[f'price low {bhk}'] = float(price_parts[0].replace('₹', '').replace(' Cr', '').replace(' L', '').strip())
                extracted[f'price high {bhk}'] = float(price_parts[1].replace('₹', '').replace(' Cr', '').replace(' L', '').strip())
                if 'L' in price_parts[0]:
                    extracted[f'price low {bhk}'] /= 100
                if 'L' in price_parts[1]:
                    extracted[f'price high {bhk}'] /= 100
            except:
                extracted[f'price low {bhk}'] = None
                extracted[f'price high {bhk}'] = None

    return extracted
# Apply the refined parsing and generate the new DataFrame structure
data_refined = []

for _, row in df_appartments.iterrows():
    features = refined_parse_modified_v2(row['PriceDetails'])
    
    # Construct a new row for the transformed dataframe
    new_row = {'PropertyName': row['PropertyName']}
    
    # Populate the new row with extracted features
    for config in ['1 BHK', '2 BHK', '3 BHK', '4 BHK', '5 BHK', '6 BHK', '1 RK', 'Land']:
        new_row[f'building type_{config}'] = features.get(f'building type_{config}')
        new_row[f'area low {config}'] = features.get(f'area low {config}')
        new_row[f'area high {config}'] = features.get(f'area high {config}')
        new_row[f'price low {config}'] = features.get(f'price low {config}')
        new_row[f'price high {config}'] = features.get(f'price high {config}')
    
    data_refined.append(new_row)

df_final_refined_v2 = pd.DataFrame(data_refined).set_index('PropertyName')

In [69]:
df_final_refined_v2['building type_Land']=df_final_refined_v2['building type_Land'].replace({'':'Land'})

In [70]:
df['PriceDetails'][10]

"{'2 BHK': {'building_type': 'Independent Floor', 'area_type': 'Carpet Area', 'area': '1,055 sq.ft.', 'price-range': '₹ 1.05 - 1.5 Cr'}, '3 BHK': {'building_type': 'Independent Floor', 'area_type': 'Carpet Area', 'area': '1,325 - 1,525 sq.ft.', 'price-range': '₹ 1.35 - 1.84 Cr'}}"

In [71]:
df_final_refined_v2

,building type_1 BHK,area low 1 BHK,area high 1 BHK,price low 1 BHK,price high 1 BHK,building type_2 BHK,area low 2 BHK,area high 2 BHK,price low 2 BHK,price high 2 BHK,...,building type_1 RK,area low 1 RK,area high 1 RK,price low 1 RK,price high 1 RK,building type_Land,area low Land,area high Land,price low Land,price high Land
PropertyName,,,,,,,,,,,,,,,,,,,,,
Smartworld One DXP,None,NaN,NaN,NaN,NaN,Apartment,1370.0,1370.0,2.0000,2.40,...,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
M3M Crown,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,...,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
Adani Brahma Samsara Vilasa,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,...,None,NaN,NaN,NaN,NaN,Land,500.0,4329.0,2.05,41.13
Sobha City,None,NaN,NaN,NaN,NaN,Apartment,1381.0,1692.0,1.5500,3.21,...,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
Signature Global City 93,None,NaN,NaN,NaN,NaN,Independent Floor,981.0,1118.0,0.9301,1.06,...,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
DLF Princeton Estate,None,NaN,NaN,NaN,NaN,Apartment,964.0,964.0,NaN,NaN,...,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
Pyramid Urban Homes 2,Apartment,335.0,398.0,23.45,0.2786,Apartment,500.0,625.0,NaN,NaN,...,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
Satya The Hermitage,None,NaN,NaN,NaN,NaN,Apartment,1450.0,1450.0,NaN,NaN,...,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
BPTP Spacio,None,NaN,NaN,NaN,NaN,Apartment,1000.0,1079.0,NaN,NaN,...,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
SS The Coralwood,None,NaN,NaN,NaN,NaN,Apartment,1320.0,1425.0,NaN,NaN,...,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN

In [72]:
categorical_columns=df_final_refined_v2.select_dtypes(include=['object']).columns.tolist()

In [73]:
categorical_columns

['building type_1 BHK',
 'building type_2 BHK',
 'building type_3 BHK',
 'building type_4 BHK',
 'building type_5 BHK',
 'building type_6 BHK',
 'building type_1 RK',
 'building type_Land']

In [74]:
ohe_df=pd.get_dummies(df_final_refined_v2,columns=categorical_columns,drop_first=True)

In [75]:
ohe_df.fillna(0,inplace=True)

In [76]:
ohe_df.astype(int)

,area low 1 BHK,area high 1 BHK,price low 1 BHK,price high 1 BHK,area low 2 BHK,area high 2 BHK,price low 2 BHK,price high 2 BHK,area low 3 BHK,area high 3 BHK,...,building type_2 BHK_Independent Floor,building type_2 BHK_Service Apartment,building type_3 BHK_Independent Floor,building type_3 BHK_Service Apartment,building type_3 BHK_Villa,building type_4 BHK_Independent Floor,building type_4 BHK_Villa,building type_5 BHK_Independent Floor,building type_5 BHK_Villa,building type_6 BHK_Villa
PropertyName,,,,,,,,,,,,,,,,,,,,,
Smartworld One DXP,0,0,0,0,1370,1370,2,2,1850,2050,...,0,0,0,0,0,0,0,0,0,0
M3M Crown,0,0,0,0,0,0,0,0,1605,2170,...,0,0,0,0,0,0,0,0,0,0
Adani Brahma Samsara Vilasa,0,0,0,0,0,0,0,0,1800,3150,...,0,0,1,0,0,1,0,0,0,0
Sobha City,0,0,0,0,1381,1692,1,3,1711,2343,...,0,0,0,0,0,0,0,0,0,0
Signature Global City 93,0,0,0,0,981,1118,0,1,1235,1530,...,1,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
DLF Princeton Estate,0,0,0,0,964,964,0,0,1127,1127,...,0,0,0,0,0,0,0,0,0,0
Pyramid Urban Homes 2,335,398,23,0,500,625,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Satya The Hermitage,0,0,0,0,1450,1450,0,0,1991,1991,...,0,0,0,0,0,0,0,0,0,0
BPTP Spacio,0,0,0,0,1000,1079,0,0,1225,1865,...,0,0,0,0,0,0,0,0,0,0
SS The Coralwood,0,0,0,0,1320,1425,0,0,1750,1890,...,0,0,0,0,0,0,0,0,0,0

In [77]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
ohe_df_normalized=pd.DataFrame(scaler.fit_transform(ohe_df),columns=ohe_df.columns,index=ohe_df.index)

In [78]:
ohe_df_normalized

,area low 1 BHK,area high 1 BHK,price low 1 BHK,price high 1 BHK,area low 2 BHK,area high 2 BHK,price low 2 BHK,price high 2 BHK,area low 3 BHK,area high 3 BHK,...,building type_2 BHK_Independent Floor,building type_2 BHK_Service Apartment,building type_3 BHK_Independent Floor,building type_3 BHK_Service Apartment,building type_3 BHK_Villa,building type_4 BHK_Independent Floor,building type_4 BHK_Villa,building type_5 BHK_Independent Floor,building type_5 BHK_Villa,building type_6 BHK_Villa
PropertyName,,,,,,,,,,,,,,,,,,,,,
Smartworld One DXP,-0.252266,-0.169584,-0.105197,-0.082332,1.223499,1.020101,-0.173712,1.158423,0.553787,0.370864,...,-0.289310,-0.063888,-0.372678,-0.063888,-0.171139,-0.254824,-0.236208,-0.111111,-0.216353,-0.063888
M3M Crown,-0.252266,-0.169584,-0.105197,-0.082332,-0.893541,-0.896660,-0.283546,-0.387986,0.293086,0.472749,...,-0.289310,-0.063888,-0.372678,-0.063888,-0.171139,-0.254824,-0.236208,-0.111111,-0.216353,-0.063888
Adani Brahma Samsara Vilasa,-0.252266,-0.169584,-0.105197,-0.082332,-0.893541,-0.896660,-0.283546,-0.387986,0.500583,1.304803,...,-0.289310,-0.063888,2.683282,-0.063888,-0.171139,3.924283,-0.236208,-0.111111,-0.216353,-0.063888
Sobha City,-0.252266,-0.169584,-0.105197,-0.082332,1.240497,1.470610,-0.198425,1.680336,0.405879,0.619632,...,-0.289310,-0.063888,-0.372678,-0.063888,-0.171139,-0.254824,-0.236208,-0.111111,-0.216353,-0.063888
Signature Global City 93,-0.252266,-0.169584,-0.105197,-0.082332,0.622383,0.667529,-0.232468,0.295011,-0.100626,-0.070634,...,3.456497,-0.063888,2.683282,-0.063888,-0.171139,-0.254824,-0.236208,-0.111111,-0.216353,-0.063888
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
DLF Princeton Estate,-0.252266,-0.169584,-0.105197,-0.082332,0.596113,0.452068,-0.283546,-0.387986,-0.215547,-0.412795,...,-0.289310,-0.063888,-0.372678,-0.063888,-0.171139,-0.254824,-0.236208,-0.111111,-0.216353,-0.063888
Pyramid Urban Homes 2,1.565039,0.704171,9.593528,0.224987,-0.120899,-0.022226,-0.283546,-0.387986,-1.414772,-1.369658,...,-0.289310,-0.063888,-0.372678,-0.063888,-0.171139,-0.254824,-0.236208,-0.111111,-0.216353,-0.063888
Satya The Hermitage,-0.252266,-0.169584,-0.105197,-0.082332,1.347122,1.132029,-0.283546,-0.387986,0.703823,0.320771,...,-0.289310,-0.063888,-0.372678,-0.063888,-0.171139,-0.254824,-0.236208,-0.111111,-0.216353,-0.063888
BPTP Spacio,-0.252266,-0.169584,-0.105197,-0.082332,0.651744,0.612964,-0.283546,-0.387986,-0.111267,0.213793,...,-0.289310,-0.063888,-0.372678,-0.063888,-0.171139,-0.254824,-0.236208,-0.111111,-0.216353,-0.063888
SS The Coralwood,-0.252266,-0.169584,-0.105197,-0.082332,1.146235,1.097051,-0.283546,-0.387986,0.447378,0.235019,...,-0.289310,-0.063888,-0.372678,-0.063888,-0.171139,-0.254824,-0.236208,-0.111111,-0.216353,-0.063888

In [79]:
cosine_sim2=cosine_similarity(ohe_df_normalized)

In [80]:
cosine_sim2

array([[ 1.        ,  0.13237477, -0.03199582, ...,  0.23938838,
         0.09359211,  0.3918892 ],
       [ 0.13237477,  1.        ,  0.08163866, ..., -0.28145036,
        -0.15433359, -0.13962499],
       [-0.03199582,  0.08163866,  1.        , ..., -0.23191291,
        -0.41377594, -0.32401234],
       ...,
       [ 0.23938838, -0.28145036, -0.23191291, ...,  1.        ,
         0.10863087,  0.18656375],
       [ 0.09359211, -0.15433359, -0.41377594, ...,  0.10863087,
         1.        ,  0.88701018],
       [ 0.3918892 , -0.13962499, -0.32401234, ...,  0.18656375,
         0.88701018,  1.        ]], shape=(246, 246))

In [81]:
ohe_df_normalized_cosine=ohe_df_normalized.reset_index()

In [82]:
cosine_sim2_df=pd.DataFrame(cosine_sim2,columns=ohe_df_normalized_cosine['PropertyName'],index=ohe_df_normalized_cosine['PropertyName'])

In [83]:
cosine_sim2_df

PropertyName,Smartworld One DXP,M3M Crown,Adani Brahma Samsara Vilasa,Sobha City,Signature Global City 93,Whiteland The Aspen,Bestech Altura,Elan The Presidential,Signature Global City 92,Emaar Digihomes,...,BPTP Freedom Park Life,DLF New Town Heights,La Lagune,M3M My Den,Suncity Avenue 102,DLF Princeton Estate,Pyramid Urban Homes 2,Satya The Hermitage,BPTP Spacio,SS The Coralwood
PropertyName,,,,,,,,,,,,,,,,,,,,,
Smartworld One DXP,1.000000,0.132375,-0.031996,0.959522,-0.002006,0.032784,0.048183,0.082966,0.035286,0.732227,...,0.096855,0.701354,-0.106754,-0.098298,-0.249860,0.152274,-0.140380,0.239388,0.093592,0.391889
M3M Crown,0.132375,1.000000,0.081639,0.010527,-0.254194,0.265614,0.924088,0.473911,-0.253349,-0.063114,...,-0.378182,-0.071287,0.309990,-0.189743,-0.129832,-0.095309,-0.105244,-0.281450,-0.154334,-0.139625
Adani Brahma Samsara Vilasa,-0.031996,0.081639,1.000000,0.019526,-0.038657,0.174413,-0.025953,0.256468,0.016806,-0.060169,...,-0.306832,-0.232345,-0.083709,-0.087618,-0.386780,-0.469637,-0.127608,-0.231913,-0.413776,-0.324012
Sobha City,0.959522,0.010527,0.019526,1.000000,0.020063,0.042506,-0.067560,0.061776,0.085339,0.759511,...,0.112606,0.632683,-0.124184,-0.081793,-0.248768,0.118896,-0.130311,0.244898,0.097376,0.352024
Signature Global City 93,-0.002006,-0.254194,-0.038657,0.020063,1.000000,-0.352655,-0.237180,-0.249699,0.984450,0.193456,...,0.075420,0.057726,-0.279006,-0.026312,0.141023,0.090045,0.006376,-0.144168,0.218714,0.243174
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
DLF Princeton Estate,0.152274,-0.095309,-0.469637,0.118896,0.090045,-0.502232,0.076864,-0.583366,0.047372,0.155832,...,0.317755,0.632953,-0.081698,-0.016350,0.726246,1.000000,0.129440,0.255321,0.831360,0.690132
Pyramid Urban Homes 2,-0.140380,-0.105244,-0.127608,-0.130311,0.006376,-0.197181,-0.097522,-0.153431,0.001755,-0.068673,...,-0.028156,-0.056768,-0.164818,0.078456,0.241251,0.129440,1.000000,-0.108402,0.131914,0.059404
Satya The Hermitage,0.239388,-0.281450,-0.231913,0.244898,-0.144168,0.424409,-0.162236,-0.097254,-0.173597,0.059850,...,0.714150,0.526183,0.579565,-0.072464,-0.189699,0.255321,-0.108402,1.000000,0.108631,0.186564
BPTP Spacio,0.093592,-0.154334,-0.413776,0.097376,0.218714,-0.618188,-0.009079,-0.480217,0.180696,0.395081,...,0.534106,0.518468,-0.177131,0.002833,0.685045,0.831360,0.131914,0.108631,1.000000,0.887010
SS The Coralwood,0.391889,-0.139625,-0.324012,0.352024,0.243174,-0.518219,-0.049587,-0.317501,0.212421,0.652451,...,0.592462,0.722140,-0.216718,-0.006667,0.432148,0.690132,0.059404,0.186564,0.887010,1.000000

In [84]:
list(enumerate(cosine_sim2[ohe_df_normalized.index.get_loc('SS The Coralwood')]))
# this give us full row of cosine similarity for:-
# SS The Coralwood	0.391889	-0.139625	-0.324012	0.352024	0.243174	-0.518219	-0.049587	-0.317501	0.212421	0.652451	...	0.592462	0.722140	-0.216718	-0.006667	0.432148	0.690132	0.059404	0.186564	0.887010	1.000000

[(0, np.float64(0.3918891986653249)),
 (1, np.float64(-0.1396249890491494)),
 (2, np.float64(-0.3240123388073464)),
 (3, np.float64(0.35202437237146833)),
 (4, np.float64(0.2431738383753818)),
 (5, np.float64(-0.5182185873211713)),
 (6, np.float64(-0.04958719123441865)),
 (7, np.float64(-0.3175005941134925)),
 (8, np.float64(0.2124209639475038)),
 (9, np.float64(0.6524505586735198)),
 (10, np.float64(0.23697001752237754)),
 (11, np.float64(-0.43120083430252126)),
 (12, np.float64(0.8755698957331169)),
 (13, np.float64(-0.005155988916384121)),
 (14, np.float64(-0.1301184823914193)),
 (15, np.float64(-0.2955972400815109)),
 (16, np.float64(0.4813653692445042)),
 (17, np.float64(0.08199300849275726)),
 (18, np.float64(0.340724307221512)),
 (19, np.float64(-0.23598701659392332)),
 (20, np.float64(-0.2932045932015663)),
 (21, np.float64(-0.17015036099999814)),
 (22, np.float64(0.5852998059957334)),
 (23, np.float64(-0.03778510201491445)),
 (24, np.float64(0.6934484636276639)),
 (25, np.float64(-0.25401856513726534)),
 (26, np.float64(0.2075810774074699)),
 (27, np.float64(0.9191721583541381)),
 (28, np.float64(0.11953259038259398)),
 (29, np.float64(0.588661859369833)),
 (30, np.float64(0.8143124130603978)),
 (31, np.float64(0.11460974344481915)),
 (32, np.float64(0.8575446636211209)),
 (33, np.float64(0.2217692651634406)),
 (34, np.float64(0.7778881850574161)),
 (35, np.float64(-0.2503637970798264)),
 (36, np.float64(-0.09690425795045471)),
 (37, np.float64(-0.31657336665599883)),
 (38, np.float64(-0.3434143612582743)),
 (39, np.float64(0.19228358870152268)),
 (40, np.float64(-0.3612057010577957)),
 (41, np.float64(-0.16914512496309878)),
 (42, np.float64(-0.22569852569661483)),
 (43, np.float64(-0.14530997261241158)),
 (44, np.float64(0.37500716738916196)),
 (45, np.float64(0.2683489282121453)),
 (46, np.float64(-0.24299185582175536)),
 (47, np.float64(-0.10991977405596828)),
 (48, np.float64(-0.21768173098884036)),
 (49, np.float64(-0.1856737440152097)),
 (50, np.float64(-0.05855940207513414)),
 (51, np.float64(0.8143730333447023)),
 (52, np.float64(-0.32639519680305457)),
 (53, np.float64(-0.13703537170830998)),
 (54, np.float64(-0.07020146952565366)),
 (55, np.float64(-0.03137483684972372)),
 (56, np.float64(-0.49400470140642855)),
 (57, np.float64(-0.4945953860222233)),
 (58, np.float64(-0.32233924359402033)),
 (59, np.float64(-0.3713831774917588)),
 (60, np.float64(-0.3405780474433727)),
 (61, np.float64(0.12375777658848959)),
 (62, np.float64(0.059395518355339384)),
 (63, np.float64(0.01573447240590669)),
 (64, np.float64(-0.03465970991167227)),
 (65, np.float64(0.393449327705819)),
 (66, np.float64(0.18175055602882104)),
 (67, np.float64(-0.5710418121180014)),
 (68, np.float64(0.041269875170826975)),
 (69, np.float64(-0.09898209444090088)),
 (70, np.float64(-0.28930668509270807)),
 (71, np.float64(0.017156245362025938)),
 (72, np.float64(-0.022559389198860472)),
 (73, np.float64(0.5022677554459571)),
 (74, np.float64(-0.03237084167207983)),
 (75, np.float64(-0.31719415597491146)),
 (76, np.float64(-0.546015083917268)),
 (77, np.float64(0.43276193628086607)),
 (78, np.float64(-0.20494716851697825)),
 (79, np.float64(0.33007508674851976)),
 (80, np.float64(0.49793017130716055)),
 (81, np.float64(-0.46565127329768674)),
 (82, np.float64(-0.14464460508431742)),
 (83, np.float64(-0.18646224636447178)),
 (84, np.float64(-0.014120497682445901)),
 (85, np.float64(-0.14413855211847393)),
 (86, np.float64(-0.49400261898329506)),
 (87, np.float64(-0.2702140171150831)),
 (88, np.float64(0.8655630620424829)),
 (89, np.float64(-0.11710292849395985)),
 (90, np.float64(0.6220561626029855)),
 (91, np.float64(0.6037067435594373)),
 (92, np.float64(0.01648945339422646)),
 (93, np.float64(0.2718349387219333)),
 (94, np.float64(0.37519509651683464)),
 (95, np.float64(-0.10401716393608823)),
 (96, np.float64(0.17800056463895159)),
 (97, np.float64(-0.08390494369127532)),
 (98, np.float64(0.3853521251108348)),
 (99, np.float64(-0.07195701725556819)),
 (100, np.float64(0.26916032163650394)),
 (101, np.float64(-0.27161687158530967)),
 (102, np.float64(-0.25152560216465486)),
 (103, np.float64(0.34324037557522036)),
 (104, np.float64(0.9421505825064774)),
 (105, np.float64(0.027199015175206034)),
 (106, np.float64(-0.22654206337113866)),
 (107, np.float64(0.9495818251157733)),
 (108, np.float64(0.014092547229037067)),
 (109, np.float64(-0.30707925792331936)),
 (110, np.float64(-0.009095959095400672)),
 (111, np.float64(-0.12935950423577144)),
 (112, np.float64(0.7307511058619605)),
 (113, np.float64(0.6083760078021335)),
 (114, np.float64(0.37148216819426894)),
 (115, np.float64(-0.16149420027101055)),
 (116, np.float64(-0.17082809380306027)),
 (117, np.float64(-0.3877239772526609)),
 (118, np.float64(0.42399708772595734)),
 (119, np.float64(0.7132844954239813)),
 (120, np.float64(-0.4528290336311397)),
 (121, np.float64(0.9523882584417823)),
 (122, np.float64(0.6877308968803907)),
 (123, np.float64(0.6679320594278129)),
 (124, np.float64(0.5344680606872616)),
 (125, np.float64(-0.05614355043573603)),
 (126, np.float64(0.7562917781795899)),
 (127, np.float64(0.49018100595436576)),
 (128, np.float64(-0.11400495245822784)),
 (129, np.float64(-0.29489085695719275)),
 (130, np.float64(0.5860743811280951)),
 (131, np.float64(0.3542646059214186)),
 (132, np.float64(0.018212640602734594)),
 (133, np.float64(0.29278566811666584)),
 (134, np.float64(-0.10685068925352359)),
 (135, np.float64(0.003405380967658978)),
 (136, np.float64(-0.42712016539868164)),
 (137, np.float64(0.8259706183146056)),
 (138, np.float64(-0.10586789198603803)),
 (139, np.float64(-0.2657023918596544)),
 (140, np.float64(0.2156362389488249)),
 (141, np.float64(-0.1715292008523824)),
 (142, np.float64(-0.19554462149729168)),
 (143, np.float64(-0.3503594281938017)),
 (144, np.float64(0.21018596964393374)),
 (145, np.float64(-0.03401913643510302)),
 (146, np.float64(0.016717430035559658)),
 (147, np.float64(0.014826845860412953)),
 (148, np.float64(0.017138009498374275)),
 (149, np.float64(-0.19408665209996467)),
 (150, np.float64(-0.5109133174912863)),
 (151, np.float64(0.10171582720850249)),
 (152, np.float64(0.03495579604068189)),
 (153, np.float64(-0.09168923026894941)),
 (154, np.float64(-0.3551732567746292)),
 (155, np.float64(-0.09818851041083537)),
 (156, np.float64(0.06207507968433129)),
 (157, np.float64(0.7097491337320132)),
 (158, np.float64(0.6698053682688272)),
 (159, np.float64(0.20209841565371653)),
 (160, np.float64(0.4006221167184)),
 (161, np.float64(0.06041365597411073)),
 (162, np.float64(-0.019789214077157422)),
 (163, np.float64(0.14079987868529)),
 (164, np.float64(0.41282072992428526)),
 (165, np.float64(-0.28132428549650895)),
 (166, np.float64(-0.3444950366469012)),
 (167, np.float64(0.6729644750323409)),
 (168, np.float64(-0.04696217234437369)),
 (169, np.float64(0.4261274826221841)),
 (170, np.float64(0.6132417670703431)),
 (171, np.float64(0.021437916643061272)),
 (172, np.float64(-0.005594447912563921)),
 (173, np.float64(0.9168754452083959)),
 (174, np.float64(0.02216032248136853)),
 (175, np.float64(0.09525249915578851)),
 (176, np.float64(0.0858169216422718)),
 (177, np.float64(0.01700429815834869)),
 (178, np.float64(0.37726664726785)),
 (179, np.float64(0.010271031819248095)),
 (180, np.float64(0.05029526540249836)),
 (181, np.float64(0.45220485917042597)),
 (182, np.float64(-0.377366568780797)),
 (183, np.float64(-0.024424803046172002)),
 (184, np.float64(0.6839445743886613)),
 (185, np.float64(-0.00671178461531787)),
 (186, np.float64(0.523226032660169)),
 (187, np.float64(0.6061634498163655)),
 (188, np.float64(0.013809527494244212)),
 (189, np.float64(-0.036131834914261696)),
 (190, np.float64(0.23291872393456492)),
 (191, np.float64(-0.0981152712924879)),
 (192, np.float64(0.6845582559288133)),
 (193, np.float64(0.061892503887910746)),
 (194, np.float64(0.24043256383409164)),
 (195, np.float64(-0.2719155648283666)),
 (196, np.float64(0.5785887736284513)),
 (197, np.float64(0.1585861943019603)),
 (198, np.float64(0.41065570411026253)),
 (199, np.float64(-0.12048881564103725)),
 (200, np.float64(-0.20486988261954545)),
 (201, np.float64(0.1753440239364756)),
 (202, np.float64(0.9786848809470038)),
 (203, np.float64(0.2269723503994667)),
 (204, np.float64(0.369895186803174)),
 (205, np.float64(0.2551677494163415)),
 (206, np.float64(-0.10730336979453255)),
 (207, np.float64(-0.0569831443292293)),
 (208, np.float64(0.00016567971873388156)),
 (209, np.float64(0.11021204929498231)),
 (210, np.float64(-0.18569989966612396)),
 (211, np.float64(-0.10184091608204181)),
 (212, np.float64(-0.24913022338162544)),
 (213, np.float64(-0.3756011090664855)),
 (214, np.float64(0.37059246674414953)),
 (215, np.float64(0.4015408254168157)),
 (216, np.float64(0.2558722318617234)),
 (217, np.float64(0.5323415668992663)),
 (218, np.float64(0.6505807820392938)),
 (219, np.float64(0.45991660474601864)),
 (220, np.float64(0.3913123005301407)),
 (221, np.float64(-0.1407845214898522)),
 (222, np.float64(-0.10885967437359953)),
 (223, np.float64(0.02141724463905706)),
 (224, np.float64(0.41708697139231365)),
 (225, np.float64(0.6944070602047687)),
 (226, np.float64(0.5320380765524522)),
 (227, np.float64(0.3152350928405606)),
 (228, np.float64(0.0129510669505759)),
 (229, np.float64(-0.3724800449367347)),
 (230, np.float64(-0.11487491685209938)),
 (231, np.float64(-0.20311322229433612)),
 (232, np.float64(0.9471000574062544)),
 (233, np.float64(0.4055492802378425)),
 (234, np.float64(0.4064248362710212)),
 (235, np.float64(-0.02540391929596622)),
 (236, np.float64(0.5924618372626735)),
 (237, np.float64(0.7221402522045215)),
 (238, np.float64(-0.21671803942505818)),
 (239, np.float64(-0.006666874160459871)),
 (240, np.float64(0.4321481294978262)),
 (241, np.float64(0.6901316667674787)),
 (242, np.float64(0.059403671282999095)),
 (243, np.float64(0.18656375348933846)),
 (244, np.float64(0.8870101820309104)),
 (245, np.float64(1.0000000000000002))]

In [85]:
def recommend_properties_with_scores(property_name,top_n=246):
    sim_score=list(enumerate(cosine_sim2[ohe_df_normalized.index.get_loc(property_name)]))
    sorted_score=sorted(sim_score,key=lambda x:x[1],reverse=True)
    top_indices=[i[0] for i in sorted_score[1:top_n+1]]
    top_scores=[i[1] for i in sorted_score[1:top_n+1]]
    top_properties=ohe_df_normalized.index[top_indices].tolist()
    recommendations_df = pd.DataFrame({
        'PropertyName': top_properties,
        'SimilarityScore': top_scores
    })
    return recommendations_df

In [86]:
recommend_properties_with_scores('M3M Golf Hills')

                PropertyName  SimilarityScore
0    AIPL The Peaceful Homes         0.955462
1         Smartworld One DXP         0.954670
2             Unitech Escape         0.953092
3                M3M Capital         0.951156
4                 BPTP Terra         0.943128
..                       ...              ...
240              Golden Park        -0.522391
241      Satya Merano Greens        -0.523660
242       ROF Normanton Park        -0.525129
243          BPTP Green Oaks        -0.525286
244           JMS The Nation        -0.526287

[245 rows x 2 columns]

In [87]:
df[['PropertyName','LocationAdvantages']]

,PropertyName,LocationAdvantages
0,Smartworld One DXP,"{'Bajghera Road': '800 Meter', 'Palam Vihar Halt': '2.5 KM', 'DPSG Palam Vihar': '3.1 KM', 'Park Hospital': '3.1 KM', 'Gurgaon Railway Station': '4.9 KM', 'The NorthCap University': '5.4 KM', 'Dwarka Expy': '1.2 KM', 'Hyatt Place Gurgaon Udyog Vihar': '7.7 KM', 'Dwarka Sector 21, Metro Station': '7.2 KM', 'Pacific D21 Mall': '7.4 KM', 'Indira Gandhi International Airport': '14.7 KM', 'Hamoni Golf Camp': '6.2 KM', 'Fun N Food Waterpark': '8.8 KM', 'Accenture DDC5': '9 KM'}"
1,M3M Crown,"{'DPSG Palam Vihar Gurugram': '1.4 Km', 'The NorthCap University': '4.4 Km', 'Park Hospital, Palam Vihar': '1.4 Km', 'Pacific D21 Mall': '8.2 Km', 'Palam Vihar Halt Railway Station': '1.2 Km', 'Dwarka Sector 21 Metro Station': '8.1 Km', 'Dwarka Expressway': '450 m', 'Fun N Food Water Park': '8.1 Km', 'Indira Gandhi International Airport': '14.1 Km', 'Tau DeviLal Sports Complex': '11.2 Km', 'Hamoni Golf Camp': '5 Km', 'Hyatt Place': '6.1 Km', 'Altrade Business Centre': '11.2 Km'}"
2,Adani Brahma Samsara Vilasa,"{'AIPL Business Club Sector 62': '2.7 Km', 'Heritage Xperiential Learning School': '2 Km', 'CK Birla Hospital': '2.5 Km', 'Paras Trinity Mall Sector 63': '3.5 Km', 'Rapid Metro Station Sector 56': '3.8 Km', 'De Adventure Park': '6.8 Km', 'Golf Course Ext Rd': '99 Meter', 'DoubleTree by Hilton Hotel Gurgaon': '3.6 Km', 'KIIT College of Engineering Sohna Road': '8.4 Km', 'Mehrauli-Gurgaon Road': '11.8 Km', 'Indira Gandhi International Airport': '21.1 Km', 'Nirvana Rd': '160 Meter', 'TERI Golf Course': '8.7 Km'}"
3,Sobha City,"{'The Shikshiyan School': '2.9 KM', 'WTC Plaza': '4 KM', 'Luxus Haritma Resort': '4.2 KM', 'BSF Golf Course': '4.7 KM', 'Dwarka Expressway': '5.1 Km', 'Rions Hospital': '5.6 Km', 'Gurgaon': '5.9 KM', 'The NorthCap University': '9.2 KM', 'Dwarka Sector 21': '9.9 KM', 'Nehru Stadium': '10.7 KM', 'Fun N Food WaterPark': '12.1 KM', 'IGI Airport': '19.3 Km', 'Vasant Kunj': '20.8 KM'}"
4,Signature Global City 93,"{'Pranavananda Int. School': '450 m', 'DLF Site central office': '1.2 Km', 'Holiday Inn Gurugram Sector 90': '2 Km', 'Krishna Hospital': '2.3 Km', 'Royal Institute Of Science': '2.4 Km', 'Sapphire 83 Mall': '6.3 Km', 'NH48': '6.9 Km', 'Garhi Harsaru Junction': '7.2 Km', 'Manesar Golf Course': '7.3 Km', 'AapnoGhar': '9.6 Km', 'IGI Airport': '31 Km'}"
...,...,...
242,DLF Princeton Estate,"{'Sector 42-43 Metro Station': '1.8 Km', 'Paras Hospital': '2 Km', 'Ardee Mall': '2.6 Km', 'Zooper India Trampoline Park': '3.1 Km', 'DLF Golf and Country Club': '3.7 Km', 'The Shri Ram School Aravali': '3.9 Km', 'Taj City Centre Gurugram': '4 Km', 'Appu Ghar Water Park': '4.7 Km', 'PVR Drive in Theatre': '7.4 Km', 'Golf Course Ext Rd': '7.6 Km', 'Duke Horse Riding Club': '8 Km', 'Surajgarh Gurgaon': '9.2 Km', 'Indira Gandhi International Airport': '15.2 Km'}"
243,Pyramid Urban Homes 2,"{'Aarvy Healthcare Super Speciality': '1.8 KM', ""St. Xavier's High School"": '2 KM', 'Minda Industries Corporate Office': '3.1 KM', 'Sapphire 83 Mall': '3.2 KM', 'Rampura Flyover, Naurangpur Rd': '3.7 KM', 'Nakhrola Stadium': '3.8 KM', 'Manesar toll plaza - Kherki Daula': '6.1 KM', 'Imt Manesar, Gurugram': '7.7 KM', 'Holiday Inn': '3 km', 'Indira Gandhi Intl Airport': '29.4 Km'}"
244,Satya The Hermitage,"{'Dwarka Expressway': '1.2 Km', 'S N International School': '1.2 Km', 'InfinityS Badminton Academy': '3.1 Km', 'Gurgaon Railway Station': '3.3 Km', 'Gurgaon Dreamz Mall': '4.6 Km', 'Metro Hospital, Palam Vihar': '6.4 Km', 'Delhi Jaipur Expressway': '7.7 Km', 'HUDA Market, Sector 14': '7.9 Km', 'F9 Go Karting Gurgaon': '8.4 Km', 'The NorthCap University': '8.8 Km', 'infinity Business Park': '9.4 Km', 'Hero Honda Chowk': '9.4 Km', 'SkyJumper Trampoline Park Gurgaon': '10.1 Km', 'Huda Metro Station': '11.6 Km', 'Indira Gandhi International Airport': '21.7 Km'}"
245,BPTP Spacio,"{'Suncity School': '0.2 Km', 'Gurugram Road': '1 Km', 'Dwarka Expressway': '1.5 Km', 'Sunrise University': '4 Km', 'Delhi Jaipur Highway': '5 Km', 'Sethi Hospital': '5.5 Km', 'Gurgaon Dreamz Mall': '7 Km', 'Gurgaon Railway Station': '7 Km', 'Infinity Business Park': '10.5 Km'}"
246,SS The Coralwood,"{'Sector 84 Road': '600 Meter', 'Delhi Public School, Sector 84': '1.3 KM', 'Dwarka Expy': '2 Km', 'Sapphire 83 Mall': '2.7 Km', 'Hyatt Regency Gurgaon': '3.9 KM', 'Aarvy Hospital': '3.9 KM', 'AapnoGhar': '6 KM', 'Garhi Harsaru Junction': '7.3 KM', 'DPG Degree College': '10.4 KM', 'Skyview Corporate Park': '12.4 KM', 'Indira Gandhi Intl Airport': '28.1 KM', 'Manesar Golf Course': '8.4 KM', 'Nakhrola Stadium': '5.2 KM'}"

In [88]:
location_mapping = {

    # ---------------- HIGHWAYS ----------------
    'nh 8': 'nh8',
    'nh8': 'nh8',
    'nh 08': 'nh8',
    'nh-8': 'nh8',
    'nh -8': 'nh8',
    'nh 8 delhi jaipur highway': 'nh8',
    'delhi jaipur expressway': 'nh8',

    'nh 48': 'nh48',
    'nh48': 'nh48',
    'nh 048': 'nh48',
    'nh-48': 'nh48',
    'nh -48': 'nh48',
    'national highway 48': 'nh48',
    'national highway  48': 'nh48',

    'nh 248a': 'nh248a',
    'nh248a': 'nh248a',
    'nh 248 a': 'nh248a',
    'nh-248a': 'nh248a',

    # ---------------- EXPRESSWAY ----------------
    'dwarka expy': 'dwarka expressway',
    'dwarka expressway': 'dwarka expressway',
    'dwarka expy, sector 109': 'dwarka expressway',

    # ---------------- METRO ----------------
    'dwarka sector 21 metro station': 'dwarka sector 21 metro',
    'dwarka sector 21': 'dwarka sector 21 metro',
    'dwarka sector 21, metro station': 'dwarka sector 21 metro',

    'sector 55-56 metro station': 'sector 55 56 metro',
    'sector 55 56 metro station': 'sector 55 56 metro',
    'sector 55-56 metro': 'sector 55 56 metro',
    'rapid metro station sector 56': 'sector 55 56 metro',

    # ---------------- AIRPORT ----------------
    'indira gandhi international airport': 'igi airport',
    'indira gandhi intl airport': 'igi airport',
    'indira gandhi int airport': 'igi airport',
    'igi airport': 'igi airport',
    'igi airport delhi': 'igi airport',

    # ---------------- RAILWAY ----------------
    'gurugram railway station': 'gurgaon railway station',
    'gurgaon railway station': 'gurgaon railway station',
    'palam vihar halt railway station': 'palam vihar halt',

    # ---------------- HOSPITALS ----------------
    'medanta the medicity': 'medanta hospital',
    'medicity': 'medanta hospital',
    'medanta hospital': 'medanta hospital',

    'artimis hospital': 'artemis hospital',
    'artemis hospital': 'artemis hospital',

    'park hospital': 'park hospital',
    'park hospital palam vihar': 'park hospital',

    # ---------------- SCHOOLS ----------------
    'delhi public school': 'dps',
    'dps': 'dps',

    'dpsg palam vihar gurugram': 'dpsg palam vihar',
    'dpsg palam vihar': 'dpsg palam vihar',

    # ---------------- MALLS ----------------
    'sapphire 83 mall': 'sapphire mall',
    'sapphire mall': 'sapphire mall',

    'pacific d21 mall': 'pacific mall',

    # ---------------- COMMON PLACES ----------------
    'igi airport terminal': 'igi airport',
    'fun n food waterpark': 'fun n food waterpark',
    'fun n food water park': 'fun n food waterpark',

    'golf course extension road': 'golf course ext road',
    'golf course ext rd': 'golf course ext road',

    'sohna road': 'sohna road',
    'badshahpur sohna rd hwy': 'sohna road',
}

In [89]:
import ast
def standardize_keys(loc_str):
    data = ast.literal_eval(loc_str)
    new_dict = {}

    for key, value in data.items():
        clean_key = key.lower().strip()
        replaced = False

        for k in location_mapping:
            if k in clean_key:   # partial match
                new_key = location_mapping[k]
                replaced = True
                break
        
        if not replaced:
            new_key = key

        new_dict[new_key] = value

    return new_dict
df['LocationAdvantages']=df['LocationAdvantages'].apply(standardize_keys)

In [90]:
df[['PropertyName','LocationAdvantages']]

,PropertyName,LocationAdvantages
0,Smartworld One DXP,"{'Bajghera Road': '800 Meter', 'Palam Vihar Halt': '2.5 KM', 'dps': '3.1 KM', 'park hospital': '3.1 KM', 'gurgaon railway station': '4.9 KM', 'The NorthCap University': '5.4 KM', 'dwarka expressway': '1.2 KM', 'Hyatt Place Gurgaon Udyog Vihar': '7.7 KM', 'dwarka sector 21 metro': '7.2 KM', 'pacific mall': '7.4 KM', 'igi airport': '14.7 KM', 'Hamoni Golf Camp': '6.2 KM', 'fun n food waterpark': '8.8 KM', 'Accenture DDC5': '9 KM'}"
1,M3M Crown,"{'dps': '1.4 Km', 'The NorthCap University': '4.4 Km', 'park hospital': '1.4 Km', 'pacific mall': '8.2 Km', 'palam vihar halt': '1.2 Km', 'dwarka sector 21 metro': '8.1 Km', 'dwarka expressway': '450 m', 'fun n food waterpark': '8.1 Km', 'igi airport': '14.1 Km', 'Tau DeviLal Sports Complex': '11.2 Km', 'Hamoni Golf Camp': '5 Km', 'Hyatt Place': '6.1 Km', 'Altrade Business Centre': '11.2 Km'}"
2,Adani Brahma Samsara Vilasa,"{'AIPL Business Club Sector 62': '2.7 Km', 'Heritage Xperiential Learning School': '2 Km', 'CK Birla Hospital': '2.5 Km', 'Paras Trinity Mall Sector 63': '3.5 Km', 'sector 55 56 metro': '3.8 Km', 'De Adventure Park': '6.8 Km', 'golf course ext road': '99 Meter', 'DoubleTree by Hilton Hotel Gurgaon': '3.6 Km', 'sohna road': '8.4 Km', 'Mehrauli-Gurgaon Road': '11.8 Km', 'igi airport': '21.1 Km', 'Nirvana Rd': '160 Meter', 'TERI Golf Course': '8.7 Km'}"
3,Sobha City,"{'The Shikshiyan School': '2.9 KM', 'WTC Plaza': '4 KM', 'Luxus Haritma Resort': '4.2 KM', 'BSF Golf Course': '4.7 KM', 'dwarka expressway': '5.1 Km', 'Rions Hospital': '5.6 Km', 'Gurgaon': '5.9 KM', 'The NorthCap University': '9.2 KM', 'dwarka sector 21 metro': '9.9 KM', 'Nehru Stadium': '10.7 KM', 'fun n food waterpark': '12.1 KM', 'igi airport': '19.3 Km', 'Vasant Kunj': '20.8 KM'}"
4,Signature Global City 93,"{'Pranavananda Int. School': '450 m', 'DLF Site central office': '1.2 Km', 'Holiday Inn Gurugram Sector 90': '2 Km', 'Krishna Hospital': '2.3 Km', 'Royal Institute Of Science': '2.4 Km', 'sapphire mall': '6.3 Km', 'nh48': '6.9 Km', 'Garhi Harsaru Junction': '7.2 Km', 'Manesar Golf Course': '7.3 Km', 'AapnoGhar': '9.6 Km', 'igi airport': '31 Km'}"
...,...,...
242,DLF Princeton Estate,"{'Sector 42-43 Metro Station': '1.8 Km', 'Paras Hospital': '2 Km', 'Ardee Mall': '2.6 Km', 'Zooper India Trampoline Park': '3.1 Km', 'DLF Golf and Country Club': '3.7 Km', 'The Shri Ram School Aravali': '3.9 Km', 'Taj City Centre Gurugram': '4 Km', 'Appu Ghar Water Park': '4.7 Km', 'PVR Drive in Theatre': '7.4 Km', 'golf course ext road': '7.6 Km', 'Duke Horse Riding Club': '8 Km', 'Surajgarh Gurgaon': '9.2 Km', 'igi airport': '15.2 Km'}"
243,Pyramid Urban Homes 2,"{'Aarvy Healthcare Super Speciality': '1.8 KM', 'St. Xavier's High School': '2 KM', 'Minda Industries Corporate Office': '3.1 KM', 'sapphire mall': '3.2 KM', 'Rampura Flyover, Naurangpur Rd': '3.7 KM', 'Nakhrola Stadium': '3.8 KM', 'Manesar toll plaza - Kherki Daula': '6.1 KM', 'Imt Manesar, Gurugram': '7.7 KM', 'Holiday Inn': '3 km', 'igi airport': '29.4 Km'}"
244,Satya The Hermitage,"{'dwarka expressway': '1.2 Km', 'S N International School': '1.2 Km', 'InfinityS Badminton Academy': '3.1 Km', 'gurgaon railway station': '3.3 Km', 'Gurgaon Dreamz Mall': '4.6 Km', 'Metro Hospital, Palam Vihar': '6.4 Km', 'nh8': '7.7 Km', 'HUDA Market, Sector 14': '7.9 Km', 'F9 Go Karting Gurgaon': '8.4 Km', 'The NorthCap University': '8.8 Km', 'infinity Business Park': '9.4 Km', 'Hero Honda Chowk': '9.4 Km', 'SkyJumper Trampoline Park Gurgaon': '10.1 Km', 'Huda Metro Station': '11.6 Km', 'igi airport': '21.7 Km'}"
245,BPTP Spacio,"{'Suncity School': '0.2 Km', 'Gurugram Road': '1 Km', 'dwarka expressway': '1.5 Km', 'Sunrise University': '4 Km', 'Delhi Jaipur Highway': '5 Km', 'Sethi Hospital': '5.5 Km', 'Gurgaon Dreamz Mall': '7 Km', 'gurgaon railway station': '7 Km', 'Infinity Business Park': '10.5 Km'}"
246,SS The Coralwood,"{'Sector 84 Road': '600 Meter', 'dps': '1.3 KM', 'dwarka expressway': '2 Km', 'sapphire mall': '2.7 Km', 'Hyatt Regency Gurgaon': '3.9 KM', 'Aarvy Hospital': '3.9 KM', 'AapnoGhar': '6 KM', 'Garhi Harsaru Junction': '7.3 KM', 'DPG Degree College': '10.4 KM', 'Skyview Corporate Park': '12.4 KM', 'igi airport': '28.1 KM', 'Manesar Golf Course': '8.4 KM', 'Nakhrola Stadium': '5.2 KM'}"

In [91]:
from collections import Counter
import pandas as pd

counter = Counter()

for x in df['LocationAdvantages']:
    counter.update(x.keys())   # ✅ directly use

key_counts = pd.Series(counter).sort_values(ascending=False)

print(key_counts)
# still ther are  some columns that are still not correnct like ng-8 etc

igi airport                         183
dwarka expressway                    80
sohna road                           49
park hospital                        34
gurgaon railway station              34
                                   ...
HDFC Bank ATM, Dhunela Ghamroj        1
Ashiana Anmol  Kid Centric Homes      1
Indianoil, Sohna - Gurgaon Rd         1
Taj Hotel & Family Restaurant         1
Skyview Corporate Park                1
Length: 988, dtype: int64

In [92]:
def distance_to_meters(distance_str):
    try:
        if 'Km' in distance_str or 'KM' in distance_str:
            return float(distance_str.split()[0]) * 1000
        elif 'Meter' in distance_str or 'meter' in distance_str:
            return float(distance_str.split()[0])
        else:
            return None
    except:
        return None

In [93]:
import ast
location_matrix={}
for index,row in df.iterrows():
    distances={}
    for location ,distance in row['LocationAdvantages'].items():
        distances[location]=distance_to_meters(distance)
    location_matrix[index]=distances
location_df=pd.DataFrame.from_dict(location_matrix,orient='index')
location_df.head()

,Bajghera Road,Palam Vihar Halt,dps,park hospital,gurgaon railway station,The NorthCap University,dwarka expressway,Hyatt Place Gurgaon Udyog Vihar,dwarka sector 21 metro,pacific mall,...,MCC Cricket Ground Dhankot,The Shri Ram School Aravali,Taj City Centre Gurugram,Minda Industries Corporate Office,"Rampura Flyover, Naurangpur Rd",Manesar toll plaza - Kherki Daula,"Imt Manesar, Gurugram",Holiday Inn,Sector 84 Road,Skyview Corporate Park
0,800.0,2500.0,3100.0,3100.0,4900.0,5400.0,1200.0,7700.0,7200.0,7400.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,550.0,NaN,NaN,NaN,NaN,6700.0,3800.0,NaN,7400.0,7500.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,5300.0,NaN,NaN,NaN,2500.0,8800.0,700.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69,1500.0,NaN,NaN,NaN,6500.0,6700.0,5100.0,NaN,8100.0,8200.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,1400.0,1400.0,NaN,4400.0,NaN,NaN,8100.0,8200.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [94]:
location_df.columns[10:50]

Index(['igi airport', 'Hamoni Golf Camp', 'fun n food waterpark',
       'Accenture DDC5', 'palam vihar halt', 'Tau DeviLal Sports Complex',
       'Hyatt Place', 'Altrade Business Centre',
       'AIPL Business Club Sector 62', 'Heritage Xperiential Learning School',
       'CK Birla Hospital', 'Paras Trinity Mall Sector 63',
       'sector 55 56 metro', 'De Adventure Park', 'golf course ext road',
       'DoubleTree by Hilton Hotel Gurgaon', 'sohna road',
       'Mehrauli-Gurgaon Road', 'Nirvana Rd', 'TERI Golf Course',
       'The Shikshiyan School', 'WTC Plaza', 'Luxus Haritma Resort',
       'BSF Golf Course', 'Rions Hospital', 'Gurgaon', 'Nehru Stadium',
       'Vasant Kunj', 'Pranavananda Int. School', 'DLF Site central office',
       'Holiday Inn Gurugram Sector 90', 'Krishna Hospital',
       'Royal Institute Of Science', 'sapphire mall', 'nh48',
       'Garhi Harsaru Junction', 'Manesar Golf Course', 'AapnoGhar', 'nh8',
       'DLF Corporate Greens'],
      dtype='object')

In [95]:
location_df.index = df.PropertyName

In [96]:
location_df

,Bajghera Road,Palam Vihar Halt,dps,park hospital,gurgaon railway station,The NorthCap University,dwarka expressway,Hyatt Place Gurgaon Udyog Vihar,dwarka sector 21 metro,pacific mall,...,MCC Cricket Ground Dhankot,The Shri Ram School Aravali,Taj City Centre Gurugram,Minda Industries Corporate Office,"Rampura Flyover, Naurangpur Rd",Manesar toll plaza - Kherki Daula,"Imt Manesar, Gurugram",Holiday Inn,Sector 84 Road,Skyview Corporate Park
PropertyName,,,,,,,,,,,,,,,,,,,,,
Smartworld One DXP,800.0,2500.0,3100.0,3100.0,4900.0,5400.0,1200.0,7700.0,7200.0,7400.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
M3M Crown,550.0,NaN,NaN,NaN,NaN,6700.0,3800.0,NaN,7400.0,7500.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Adani Brahma Samsara Vilasa,5300.0,NaN,NaN,NaN,2500.0,8800.0,700.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Sobha City,1500.0,NaN,NaN,NaN,6500.0,6700.0,5100.0,NaN,8100.0,8200.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Signature Global City 93,NaN,NaN,1400.0,1400.0,NaN,4400.0,NaN,NaN,8100.0,8200.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
DLF Princeton Estate,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Pyramid Urban Homes 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Satya The Hermitage,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
BPTP Spacio,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SS The Coralwood,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [97]:
location_df.max().max()

54500.0

In [98]:
location_df.fillna(54500.0,inplace=True)

In [99]:
location_df

,Bajghera Road,Palam Vihar Halt,dps,park hospital,gurgaon railway station,The NorthCap University,dwarka expressway,Hyatt Place Gurgaon Udyog Vihar,dwarka sector 21 metro,pacific mall,...,MCC Cricket Ground Dhankot,The Shri Ram School Aravali,Taj City Centre Gurugram,Minda Industries Corporate Office,"Rampura Flyover, Naurangpur Rd",Manesar toll plaza - Kherki Daula,"Imt Manesar, Gurugram",Holiday Inn,Sector 84 Road,Skyview Corporate Park
PropertyName,,,,,,,,,,,,,,,,,,,,,
Smartworld One DXP,800.0,2500.0,3100.0,3100.0,4900.0,5400.0,1200.0,7700.0,7200.0,7400.0,...,54500.0,54500.0,54500.0,54500.0,54500.0,54500.0,54500.0,54500.0,54500.0,54500.0
M3M Crown,550.0,54500.0,54500.0,54500.0,54500.0,6700.0,3800.0,54500.0,7400.0,7500.0,...,54500.0,54500.0,54500.0,54500.0,54500.0,54500.0,54500.0,54500.0,54500.0,54500.0
Adani Brahma Samsara Vilasa,5300.0,54500.0,54500.0,54500.0,2500.0,8800.0,700.0,54500.0,54500.0,54500.0,...,54500.0,54500.0,54500.0,54500.0,54500.0,54500.0,54500.0,54500.0,54500.0,54500.0
Sobha City,1500.0,54500.0,54500.0,54500.0,6500.0,6700.0,5100.0,54500.0,8100.0,8200.0,...,54500.0,54500.0,54500.0,54500.0,54500.0,54500.0,54500.0,54500.0,54500.0,54500.0
Signature Global City 93,54500.0,54500.0,1400.0,1400.0,54500.0,4400.0,54500.0,54500.0,8100.0,8200.0,...,54500.0,54500.0,54500.0,54500.0,54500.0,54500.0,54500.0,54500.0,54500.0,54500.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
DLF Princeton Estate,54500.0,54500.0,54500.0,54500.0,54500.0,54500.0,54500.0,54500.0,54500.0,54500.0,...,54500.0,54500.0,54500.0,54500.0,54500.0,54500.0,54500.0,54500.0,54500.0,54500.0
Pyramid Urban Homes 2,54500.0,54500.0,54500.0,54500.0,54500.0,54500.0,54500.0,54500.0,54500.0,54500.0,...,54500.0,54500.0,54500.0,54500.0,54500.0,54500.0,54500.0,54500.0,54500.0,54500.0
Satya The Hermitage,54500.0,54500.0,54500.0,54500.0,54500.0,54500.0,54500.0,54500.0,54500.0,54500.0,...,54500.0,54500.0,54500.0,54500.0,54500.0,54500.0,54500.0,54500.0,54500.0,54500.0
BPTP Spacio,54500.0,54500.0,54500.0,54500.0,54500.0,54500.0,54500.0,54500.0,54500.0,54500.0,...,54500.0,54500.0,54500.0,54500.0,54500.0,54500.0,54500.0,54500.0,54500.0,54500.0
SS The Coralwood,54500.0,54500.0,54500.0,54500.0,54500.0,54500.0,54500.0,54500.0,54500.0,54500.0,...,54500.0,54500.0,54500.0,54500.0,54500.0,54500.0,54500.0,54500.0,54500.0,54500.0

In [100]:
# Apply the SStandardScaler to the entire location dataframe
location_df_normalized = pd.DataFrame(scaler.fit_transform(location_df), columns=location_df.columns, index=location_df.index)

In [101]:
location_df_normalized

,Bajghera Road,Palam Vihar Halt,dps,park hospital,gurgaon railway station,The NorthCap University,dwarka expressway,Hyatt Place Gurgaon Udyog Vihar,dwarka sector 21 metro,pacific mall,...,MCC Cricket Ground Dhankot,The Shri Ram School Aravali,Taj City Centre Gurugram,Minda Industries Corporate Office,"Rampura Flyover, Naurangpur Rd",Manesar toll plaza - Kherki Daula,"Imt Manesar, Gurugram",Holiday Inn,Sector 84 Road,Skyview Corporate Park
PropertyName,,,,,,,,,,,,,,,,,,,,,
Smartworld One DXP,-7.959290,-15.652476,-3.734528,-2.997026,-2.832800,-3.145418,-1.750075,-10.240056,-4.843607,-6.021290,...,0.0,0.063888,0.063888,0.063888,0.063888,0.063888,0.063888,0.0,0.063888,0.063888
M3M Crown,-7.996942,0.063888,0.263632,0.343235,0.382909,-3.053250,-1.635193,0.090313,-4.822212,-6.008143,...,0.0,0.063888,0.063888,0.063888,0.063888,0.063888,0.063888,0.0,0.063888,0.063888
Adani Brahma Samsara Vilasa,-7.281544,0.063888,0.263632,0.343235,-2.988399,-2.904363,-1.772168,0.090313,0.216252,0.171075,...,0.0,0.063888,0.063888,0.063888,0.063888,0.063888,0.063888,0.0,0.063888,0.063888
Sobha City,-7.853863,0.063888,0.263632,0.343235,-2.729068,-3.053250,-1.577752,0.090313,-4.747330,-5.916112,...,0.0,0.063888,0.063888,0.063888,0.063888,0.063888,0.063888,0.0,0.063888,0.063888
Signature Global City 93,0.128478,0.063888,-3.866763,-3.107501,0.382909,-3.216316,0.605008,0.090313,-4.747330,-5.916112,...,0.0,0.063888,0.063888,0.063888,0.063888,0.063888,0.063888,0.0,0.063888,0.063888
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
DLF Princeton Estate,0.128478,0.063888,0.263632,0.343235,0.382909,0.335702,0.605008,0.090313,0.216252,0.171075,...,0.0,0.063888,0.063888,0.063888,0.063888,0.063888,0.063888,0.0,0.063888,0.063888
Pyramid Urban Homes 2,0.128478,0.063888,0.263632,0.343235,0.382909,0.335702,0.605008,0.090313,0.216252,0.171075,...,0.0,0.063888,0.063888,0.063888,0.063888,0.063888,0.063888,0.0,0.063888,0.063888
Satya The Hermitage,0.128478,0.063888,0.263632,0.343235,0.382909,0.335702,0.605008,0.090313,0.216252,0.171075,...,0.0,0.063888,0.063888,0.063888,0.063888,0.063888,0.063888,0.0,0.063888,0.063888
BPTP Spacio,0.128478,0.063888,0.263632,0.343235,0.382909,0.335702,0.605008,0.090313,0.216252,0.171075,...,0.0,0.063888,0.063888,0.063888,0.063888,0.063888,0.063888,0.0,0.063888,0.063888
SS The Coralwood,0.128478,0.063888,0.263632,0.343235,0.382909,0.335702,0.605008,0.090313,0.216252,0.171075,...,0.0,0.063888,0.063888,0.063888,0.063888,0.063888,0.063888,0.0,0.063888,0.063888

In [102]:
cosine_sim3=cosine_similarity(location_df_normalized)

In [103]:
cosine_sim3

array([[ 1.        ,  0.19180124,  0.12991712, ..., -0.08809644,
        -0.08809644, -0.08809644],
       [ 0.19180124,  1.        ,  0.14858223, ..., -0.03387922,
        -0.03387922, -0.03387922],
       [ 0.12991712,  0.14858223,  1.        , ..., -0.03473003,
        -0.03473003, -0.03473003],
       ...,
       [-0.08809644, -0.03387922, -0.03473003, ...,  1.        ,
         1.        ,  1.        ],
       [-0.08809644, -0.03387922, -0.03473003, ...,  1.        ,
         1.        ,  1.        ],
       [-0.08809644, -0.03387922, -0.03473003, ...,  1.        ,
         1.        ,  1.        ]], shape=(246, 246))

In [104]:
def recommend_properties_with_scores(property_name, top_n=5):
    # cosine_sim_score=cosine_sim3 # non weighted score only based on location
    cosine_sim_score=0.5*cosine_sim1+0.8*cosine_sim2+cosine_sim3
    sim_scores = list(enumerate(cosine_sim_score[location_df_normalized.index.get_loc(property_name)]))
    sorted_score=sorted(sim_scores,key=lambda x:x[1],reverse=True)
    top_indices=[i[0] for i in sorted_score[1:top_n+1]]
    top_score=[i[1] for i in sorted_score[1:top_n+1]]
    top_properties= location_df_normalized.index[top_indices].tolist()
    recommendations_df = pd.DataFrame({
        'PropertyName': top_properties,
        'SimilarityScore': top_score
    })
    return recommendations_df
recommend_properties_with_scores('DLF The Camellias')

          PropertyName  SimilarityScore
0  Salcon The Verandas         0.812439
1    DLF The Magnolias         0.591049
2      DLF The Aralias         0.555057
3    Parsvnath Exotica         0.397634
4        Pioneer Araya         0.384404

In [105]:
(3*cosine_sim3 + 5*cosine_sim2 + 6*cosine_sim1).shape

(246, 246)

In [106]:
print(list(location_df_normalized.columns))

['Bajghera Road', 'Palam Vihar Halt', 'dps', 'park hospital', 'gurgaon railway station', 'The NorthCap University', 'dwarka expressway', 'Hyatt Place Gurgaon Udyog Vihar', 'dwarka sector 21 metro', 'pacific mall', 'igi airport', 'Hamoni Golf Camp', 'fun n food waterpark', 'Accenture DDC5', 'palam vihar halt', 'Tau DeviLal Sports Complex', 'Hyatt Place', 'Altrade Business Centre', 'AIPL Business Club Sector 62', 'Heritage Xperiential Learning School', 'CK Birla Hospital', 'Paras Trinity Mall Sector 63', 'sector 55 56 metro', 'De Adventure Park', 'golf course ext road', 'DoubleTree by Hilton Hotel Gurgaon', 'sohna road', 'Mehrauli-Gurgaon Road', 'Nirvana Rd', 'TERI Golf Course', 'The Shikshiyan School', 'WTC Plaza', 'Luxus Haritma Resort', 'BSF Golf Course', 'Rions Hospital', 'Gurgaon', 'Nehru Stadium', 'Vasant Kunj', 'Pranavananda Int. School', 'DLF Site central office', 'Holiday Inn Gurugram Sector 90', 'Krishna Hospital', 'Royal Institute Of Science', 'sapphire mall', 'nh48', 'Garhi Harsaru Junction', 'Manesar Golf Course', 'AapnoGhar', 'nh8', 'DLF Corporate Greens', 'Miracles Apollo Cradle Hospital', 'Hyatt Regency Gurugram', 'Golden Greens Golf & Resorts Limited', 'Mount Olympus Junior School', 'Miracles Apollo Hospital', 'Savoy Suites, Manesar', 'Golden Greens Golf & Resorts', 'IMT Manesar', 'Amity University Gurugram', 'Euro International School, Sector- 109', 'Jai Sai Ram Hospital', 'Aryan Hospital', 'Idea Cosmic Plaza', 'Royal Institute Of Science & Management', 'Pataudi Road', 'Holiday Inn Sector 90', 'RPS International School', 'Aarvy Healthcare Hospital', 'Iris Broadway Mall', 'Imperia Mindspace', 'AIPL Business Tower', 'Heritage School', 'Lotus Valley Intl School, Gurgaon', 'Gurugram University', 'Omaxe Gurgaon Mall', 'Sushant University', 'Naurangpur Cricket Stadium', 'Naurangpur Road', 'Vatika Town Square-INXT', 'Ompee International School', 'Manesar Bus Stand', 'Yashlok Medical Centre', 'Euro International School', 'WorldMark Gurgaon', 'Capital Cyberscape', 'The Shriram Millennium School', 'DoubleTree by Hilton Hotel', 'Badshahpur Sohna Hwy', 'Nakhrola Stadium', 'Delhi - Jaipur Expressway', 'Vatika Town Square-INXT Mall', 'Savoy Suites', 'Bal Bharati Public School', 'Vatika Business Centre', 'Indira Gandhi Int. Airport', "St. Xavier's High School", 'Miracles Apollo Cradle', 'Ambience Mall New', 'Hyatt Regency Gurgaon', 'Elan Miracle Mall', 'Miracles Apollo Cradle Spectra Hospital', 'Agri Business Management Collage', 'Grand Hyatt Gurgaon', 'Duke Horse Riding Club', 'PVR Drive In Cinema', 'W Pratiksha Hospital', 'Metro World Mall', 'Unicosmos School', 'Faridabad Gurgaon Road', 'Bestech Business Tower', 'Appu Ghar', 'SkyJumper Trampoline Park', 'Axis Bank', 'KMP Expressway', 'Karma Lakelands', 'Jungle Safari & Trails', 'medanta hospital', 'Faridabad - Gurgaon Road', "Lingaya's Lalita Devi Institute", 'ASF Insignia SEZ', 'Banjara Market Gurugram', 'Central Plaza Mall', 'Paras Hospitals, Gurgaon', 'Vega School', 'Indian School of Hospitality', 'Vatika City Centre', 'Aatish Hospital', 'Info Technology Park Phase 2', 'Huda Metro Station', 'Southern Peripheral Rd', 'Global Ways School', 'Radisson Hotel', 'nh248a', 'Sector 55/56 Metro Station', 'Mavens Inn', 'Sanar International Hospital', 'Sector 53-54 Metro Station', 'IILM University, Gurugram', 'The Banyan Tree World School', 'The Big Tree Cafe', 'DLF Golf and Country Club', 'Aarvy Hospital', 'DPG Degree College', 'Shivani public school', 'Baghera University', 'Kutumbh Hospital', 'Bijwasan Railway Station', 'Global Foyer Mall', 'Phase 2 Metro Station', 'Gurgaon Dreamz Mall', 'Metro Hospital, Palam Vihar', 'Delhi Ajmer Expressway', 'Infinity Business Park', 'Huda metro station', "Rion's Hospital", 'Euro International School, Sector- 109.', 'Golf Course Ext Road', 'Heritage Xperiential Learning, CRPF Rd', 'Sector 54 Chowk Metro Station', 'Gurgaon - Delhi Expy', 'Genesis Hospital Sector 84', 'DPGITM Engineering College Sector 34', 'Holiday Inn Hotel Sector 90', 'SkyJumper Trampoline Park Gurgaon', 'National Tennis Academy Sector 98', 'Nouveau Medics Multispeciality OPD', 'Heritage Village Resort & Spa', 'Sector 86 Road', 'Genesis Hospital', 'Delh-Ajmer Expy', 'DPG Institute of Technology', 'Airia Mall', 'Amma Hospital', 'Eros City Square', 'Splendor Trade Tower', 'Narayana Junior College', 'Sector 55 Metro Station', 'Dharampur Main Road', "Oyster's Water Park", 'Vivanta Dwarka New Delhi', 'DLF Corporate Park', 'GD Goenka World School', 'KR Mangalam University', 'Smart View Hotel and Resort', 'Central Park Flower Valley', 'Shopping complex', 'Central Peripheral Road', 'Nakhrola Stadium Sector 81A', 'Imt Manesar', 'G D Goenka University', 'Fly India Adventure Resort', 'Vardaan Hospital', 'IMT Office Sohna', 'JMS Marine Square Mall', 'Vibrant Hospital', 'Prime Scholars Int. School', 'Ramgarh Farms & Resort', 'Basai Road', 'Shree Krishna Hospital', 'The Esplanade Mall', 'GEMS International School', 'Pranavananda International School', 'Greenway Hospital', 'National Tennis Academy', 'Paras Trinity Mall', 'Rajesh Pilot Road', 'Scottish High International School', 'KIIT College of Engineering', 'The Vivekananda School', 'Southern Peripheral Road', 'Holiday Inn Express Gurugram Sector 50', 'Early Basket Grocery shop', 'Aradhya Cricket Club Gurgaon', 'Imperial Heritage School', 'Daultabad Village Park', 'Skylark Cricket Academy', 'Yashroop Hospital', 'Gurgaon Old Railway Station', "Domino's Pizza", 'Conscient One Mall', 'Emerald Plaza Shopping Mall', 'Pawlywoof - Dog Park', 'SCC Drive-In Cinema', 'Shiksha Bharti Public School', 'Holiday Inn Express Gurugram', 'Sahara Mall', 'Dhanwapur Road', 'Govt. PG College', 'Basai Dhankot', 'Park Inn', 'IFFCO Chowk Metro Station', 'The Executive Centre', 'Euro Int School, Sector 37D, Gurugram', 'Reliance Trends Newtown Square Mall', 'SGT University', 'SGT Hospital 1', 'Suncity School', 'Green Field School', 'Narayana E Techno', 'Alpine Convent School', 'Little E Step –Pre School', 'Sheetla Mata Mandir', 'Captain Chandan Lal Marg', 'CD International School', 'Raheja Mall', 'Basai Dhankot Railway Station', 'First Step Play School', 'Sri Ma Montessori International', 'Dwaraka Expressway', 'Ansal Plaza', 'Proposed Metro Station', 'Delhi International Airport', 'KMP Corridor', 'Vega Schools Sector 48', 'Cloudnine Hospital Sector 47', 'PVR Drive In Theatre', 'City Hospital', 'NH 352W, Pataudi', 'Pathfinder Global School, Pataudi', 'Vistar Complex', 'BML Munjal University (BMU)', 'Bestech Central Square Mall', 'ORCHIDS The International School', 'Marengo Asia Hospitals', 'Sector 42-43 Rapid Metro', 'Sector 53-54 Rapid Metro', 'Bank Of Baroda', 'HDFC Bank ATM', 'Muincipal Corporation of Gurugram', 'One Horizon Center Bus Stop', 'Shalom Hills International School', 'Satyam Medicare Hospital', 'Anand Preschool', 'Choice pharmacy', 'Qutub Plaza', 'Sunset point', 'EPF Regional Office', 'IFFCO Chowk', 'Kingdom of Dreams', 'Gaytri Public School', 'KIIT College', 'SPM Hospital', 'Sealdah Railway Station', 'International Airport', 'Lemon Tree Hotel', 'CK Birla Hospital, Gurgaon', 'Golf Pavilion', 'Golf Course Road', 'Ardee Mall', 'Shiv Nadar School', 'NH 148A', 'Ambience Public School', 'Heritage Intl Xperiential School', 'Summer Fields School', 'Primamed Super Speciality Hospital', 'Uma Sanjeevani Health Centre', 'Anya Gurgaon', 'Hotel Golf View Suites', 'Apollo Pharmacy', 'Rx Pharmacy', 'Sector 42/43 Bus Stand', 'Genpact Chowk Bus Stop', 'Huda City Centre Metro Station', 'Sector 53 Metro Station', 'ICICI Bank ATM', 'Bharat Petroleum Retail Outlet', 'DLF Linear Park', 'Le Meridien Gurgaon', 'Sector 42-43 Metro Station', 'Faridabad - Gurgaon Rd', 'Ambience Mall', 'Fun N Food Village', 'F9 Go Karting Gurgaon', 'Proposed Metro corridor', 'N.H-8', 'Shiskshantar', 'Amity', 'Pathways', 'GD Goenka', 'Artemis', 'Max, Fortis', 'Apollo', 'Paras Trinity Shopping Mall', 'Swastik Multispeciality Hospital', 'AIPL Business Co Working Space', 'Lemon Tree Hotel Sector 60', 'MKD Hospital', 'PVR Drive in Theatre', 'Sant Soordas Sihi Metro Station', 'De Adventure Amusement Park', 'Vatika Business Park Sector 49', 'Suncity School, Sector 37D', 'The Signature Advanced Super Speciality', 'Gurugram University Kankrola', 'Candor TechSpace, Sector 48', 'IndusInd Bank ATM', "Cherub's Cradle", 'Mavens Orange - Hotel', 'Learning Stars School', 'State Bank of India', 'Deerika HyperMart', 'Triangular Park', 'artemis hospital', 'Sector 45 SO Post Office', 'FUEL NATION', 'HSBC', 'Women Police Station', 'Best IVF Centre', 'Huda City Centre', 'Gurugram Public School', 'Shikshantar - Primary School', 'Mamta Hospital', 'IG International Airport', 'Omaxe City Centre', 'DLF Grand Mall', 'Arvy Hospital', 'Matrikiran School', 'DLF Cyber City', 'Vatika Town Square', 'Global city centre', 'Gd goenka university', 'Vardaan hospital and trauma centre', 'Maharana pratap school', 'Garhi harsaru railway station Gurgaon', 'HUB 66', 'Sealdah', 'Sector 55-56 Rapid Metro Station', 'Hasanpur', 'The Oberoi', 'Euro Intl School, Sector- 109', 'Najafgarh Kapashera Road', 'Hong Kong Bazaar', 'Bharti International Convent School', 'Ashoka International School', 'The Oberoi Gurgaon', 'GD Goenka Public School', 'Chauma Road', 'Chirag Hospital', 'Sector-21 Metro Dwarka', 'AIPL Joy Street Mall', 'iON Digital Zone (Gurugram)', 'HUDA Mini Golf Course', 'IMT Road', 'Sohna Gurgaon Road', 'Spaze Itech Park', 'Polaris Hospital', 'RBSM Public school', 'Health Care Pharmacy', 'Sector 54 Chowk', 'EuroKids Preschool Suncity', 'YES Bank ATM', 'Suncity School Gurgaon', 'Suncity Shopping Complex', 'Vallores Pre School', 'Umkal Hospital', 'Haryana City Gas', 'Marigold Secondary School', 'Alpine Hospital', 'Pushpanjali Hospital', 'Golf Course Extension Rd', 'Country Inn', 'Westin', 'The Millenium School', 'Rajiv Chowk - Sohna Highway', 'KMP corridor', 'Central Park Resorts', 'GD Goenka University', 'Swastik Hospital Sec 66', 'Adarsh Senior Secondary School', 'Golf Course Extension', 'International Tech Park Gurgaon,', 'Ananta Hospital', 'Indus World School', 'Golf Corse Ext. Rd.', 'National Highway-48', 'Prime Scholars International School', 'Shri Balaji’s Multispeciality Hospital', 'Euro International School, Sector 37D', 'Park Inn, Gurgaon', 'DLF World Tech Park', 'Star Mall', 'The Hive Shopping Mall', 'Yaduvanshi Shiksha Niketan', 'Royal Institute Of Science and Mgt', 'Newtown Square Mall', 'NH 352W', 'Eros Corporate Park', 'Manesar Road', 'Euro International School, Sec 84', 'Huda Metro Station (Gurugram)', 'InfinityS Badminton Academy', 'Sanskar Bharti Public School', 'Manipal Hospital, Gurugram', 'HUDA Market, Sector 14', 'Delhi Gurgaon Expressway', 'SCC Rooftop Drive-In', 'The Oberoi, Gurgaon', 'Kings International School', 'HUDA Market', 'Basai Metro Station', 'CBR Cricket Ground', 'Rapid Metro Sector 55-56', 'Kunskapsskolan School', 'Omaxe Celebration Mall', 'Gurgaon - Delhi Expy, Sector 75A', 'International Tech Park Gurgaon', 'Shalom Presidency School', 'Sector 55-56 Rapid Metro', 'Jinga Lala Theme Park Gurgaon Delhi', 'Pataudi Rd, Sector 95B', 'RELIANCE TRENDS Newtown Square Mall', 'Aarvy Healthcare Super Speciality', 'Approved Sector 37 Mero Station', 'Signature Hospital', 'Xavier’s International', 'Alpine School', 'Esplanade Mall', 'Sector 10 Market', 'Blue Bells Public School', 'infinity Business Park', 'Galleria 108 Mall', 'Manipal Hospital', 'Vivanta New Delhi, Dwarka', 'Bharat Ram Global School', 'Canara Bank ATM', 'Yes Bank', 'Arc Hospital', 'Canara Bank', 'Axis Bank ATM', 'City Square', 'Shishu Kalyan School', 'Rathore IMT Hospital', 'DSD College', 'Patil Station', 'Amity University', 'ICFAI University', 'Indira Gandhi Airport', 'Sapphire 83', 'Cambridge Montessori', 'Hyatt Regency', 'Rao Bharat Singh International School', 'Aarvy Healthcare', 'Aapno Ghar', 'Cambridge College Of Education', 'Iffco Chowk', 'Euro International School, Sector 84', 'Dharampeth Main Road', 'Old Delhi Gurgaon Road', 'Rotary Public School', 'Candor Techspace', 'Manipal Hospital, Palam Vihar', 'Moulsari Avenue', 'Adarsh public school,Garhi Harsaru', 'PHC Garhi Harsaru', 'Excellere World School', 'Aman Hospital & Surgical Centre', 'Neemrana Palace', 'K. R. Mangalam University', 'Global City Centre', 'Vishwas Hospital', 'Ibis Hotel', 'Horizon 1 Mall', 'Sector 42-43 Metro station', 'Ernst & Young', 'Paras Hospital', 'Gurgaon Faridabad Highway', 'Mount Olympus School, Sec 79', 'Singhania University, Manesar', 'Capital Business Park', 'Old Sohna Dhani Road', 'GD Goenka Signature School', 'Vardaan Hospital & Trauma Centre', 'Public Bazar', 'GD Goenka School', 'Vatika Business Park', 'Bharat Petrol Pump', 'The Millennium School', 'IndusInd Bank', 'Tau Devi Lal Sports Complex', 'Children Park', 'Medanta Dialysis Center', 'Central Park, Sohna Rd', 'HDFC Bank ATM, Dhunela Ghamroj', 'Ashiana Anmol  Kid Centric Homes', 'Indianoil, Sohna - Gurgaon Rd', 'Taj Hotel & Family Restaurant', 'V-Square Sohna New Residential', 'G D Goenka World School', 'The Phoenix Project, Sohna - Gurgaon Rd', 'Signature Global Park', 'Signum 36', 'Kotak Mahindra Bank, MBS Tower', 'Pasco Automobiles, Alipur, Sohna', 'Sohna Bus Stand', 'Imperio School', 'Ektaa Hospitals', 'Vipul Trade Business Centre', 'Radisson Hotel Gurugram', 'Airia Mall Sector 68', 'Damdama More', 'Civil Hospital', 'K.R. Mangalam University', 'Western Peripheral Expressway', 'Bhondsi Nature Park', 'Enkays Hospital', 'Lemon Tree Hotel,', 'Ram Krishna Public School', 'Aravalli Hill View Point', 'Gurugram Global Heights School', 'Satya The Hive Mall', 'Gurugram Road', 'The Signature Super Speciality Hospital', 'Sunrise University', 'Country Inn & Suites by Radisson', 'Yonex Badminton Stadium', 'Grand Hyatt', 'Au Grand Air', 'Indira Gandhi Eye Hospital', 'Double Tree by Hilton', 'Swastik Hospital', 'Jinaglala Theme Park', 'Scottish International School', 'Ap Sports cricket ground', 'Nischay Cricket Academy', 'DLC Cricket Ground', 'Drona Sports Village', 'Ramada by Wyndham Gurgaon', 'Mehrauli-Gurgaon Rd', 'Surajgarh Gurgaon', 'Apex Plus Hospital', 'ZEN Golf Range & Academy', 'The Banyan Tree Hiking Area', 'MG Road', 'Plaza Mall', 'MGF Metropolitan Mall', 'Lancers International School', 'Gurjar Samrat Jaipal Khatana Marg', 'Signature Global Infinity Mall Sohna', 'Vidya Niketan Sr Sec School', 'Sanjivani Hospital', 'Spectra Hospital', 'Golf Course Extn Road', 'Tulip Violet Society, Sector 69', 'Federal Bank Sector 71', 'Kunskapsskolan International', 'Southern Peripheral Rd, Gurugram', 'Ektaa Hospitals  Main Sohna Rd', 'Central Bank Of India Sohna Rd', 'Sanjeevani Hospital - Child Specialist', 'VATIKA BUSINESS PARK Sohna Rd', 'IndianOil, Hasanpur', 'Axis Bank, Sohna Rd', 'Shambhu Dayal High School', 'Global City Centre Mall', 'Vardaan Hospital and Trauma Centre', 'Ascendas OneHub Gurgaon', 'IRIS Broadway Mall', 'Flying Wings Badminton Academy', 'Saraswati Model School', 'Orchid Business Park', 'Farrukh Nagar Railway Station', 'M3m 65th Avenue Mall', 'Rapid Metro Sector 56', 'Sneh Hospital', 'Gems International School', 'National Highway 8', 'Appu Ghar Water Park', 'Tennis Vidyalaya (Tennis Academy)', 'Zooper India Trampoline Park', 'Teri Golf Course', 'Park Dr, DLF Phase 5', 'Paras Hospitals', 'Heritage badminton academy', 'Green Field Public School', 'Kadipur Industrial Area', 'Spazedge IT Park', 'JMD Megapolis', 'More Hypermart , Vipul business park', 'Basant Valley Global School', 'The Paras World School', 'Vipul Trade Centre', 'WorldMark Gurgaon, Maidawas Rd', 'Western Peripheral Expy, Gurugram', 'Raghunath Bal Vidya Mandir School', 'ESIC Hospital', 'S N International School', 'Infinitys Badminton Academy', 'Country Inn and Suites by Radisson', 'Sector 29 Gurgaon Pubs and Bars', 'Emaar Business Park', 'Southern Peripheral Rd, Dhani', 'Omaxe City Centre Mall', 'Ektaa Hospital', "St. Xavier's School", 'PVR Drive In Theater', 'American Express', 'IDFC FIRST Bank', 'Sector 42-43', 'Sector 53-54', 'MGF Megacity Mall', 'Fortis hospital', 'Pataudi road', 'Double Infinity market', 'Bamroli Cricket Ground', 'Aman Hospital', 'Kidzee', 'Paras Trinity', 'AIPL Business Club', 'Sector 55-56 rapid metro station', 'Narayana e-Techno School - Manesar', 'HDFC Bank, Pataudi Rd', 'SS Omnia, Sector 86', 'Canara Bank - Nawada Fatehpur', 'ICICI Bank ATM, Sector 86', 'Silver Streak Multi Speciality', 'RHM Public School', 'Minda Industries Nawada Fatehpur', 'Numberdar market, IMT Manesar', "Sodhi's Supermarket, Sector 82", 'M3M SCO Shop cum Office', 'Sector 42-43 Rapid Metro Station', 'Quality Inn Gurgaon', 'Minda Industries Limited', 'Central Park II Road', 'Omex City Centre Mall', 'Damdama Lake Rd', 'Sohna Hill Viewpoint', 'KR Mangalam University Sohna', 'Country Inn & Suites By Radisson', 'Hero Honda Chowk', 'Jagdish Super Market', 'Gyaananda School', 'Bharat Petroleum Shree Shyam Filling', 'The Club, International City', 'Conscient One', 'ICICI BANK ATM, Annapurna MKT', 'ESIC Dispensary', 'Canara Bank New Palam Vihar', 'Dwarka', 'Radha Krishan Mandir', 'Daultabad Stadium', 'Gurgaon Gramin Bank', 'IGIA Airport', 'SCR Model School', 'Golden Tulip Suites Gurgaon', 'South point Mall', 'Pathways School Gurgaon', 'Kidzee Sec-93', 'Jhankar Group of Institutions', 'Heritage Badminton Academy', 'Euro Intl School, Sector 37D, Gurugram', 'Sethi Hospital', 'HDFC Bank', 'The Sixth Element School', 'K.R.Mangalam World School', 'Sushil Park', 'Peer Baba Ki Mazar', 'Punjab National Bank', 'CoNexus.Life B35', 'Medhaam Pre School & Daycare', 'Moksh Wellness Pvt Ltd.', 'Marriott Courtyard', 'World Tech Park', 'Athena', 'Bharat Petroleum Petrol Pump', 'Sanskar Jyoti School', 'Arc Multi Speciality Hospital', 'Narayana e Techno School', 'Medeor Hospital, Manesar', "Guls' Kitchen", 'The Nook', 'Open Tap', 'Frescos', 'Subway', 'BOB ATM', 'PNB ATM', 'HDFC bank ATM', 'YES bank ATM', 'Citibank ATM', 'Gurugram Hospital', 'Govind Hospital', 'Manish Gallexie 91', 'Silver Streak Multi Speciality Hospital', 'Holiday Inn Gurugram', 'Airport', 'Vatika Sector Road', 'Gurugram University Sector 87', 'CNG Petrol Pump', 'Miracles Apollo Cradle/Spectra Hospital', 'Vivek Model School', "McDonald's India 24 Hours", 'Garhi Budhera Road', 'Iris Broadway Gurugram', 'iGrow Montessori Play School', 'Matrikiran High School', 'Badsa AMS Hospital', 'GlobalHealthcare Multispeciality', 'Cricket Academy', "V'Lante Mall", 'Patli Railway Station', 'V Club', 'Fitso Sector 48 Spuddy, Badminton', 'Lotus Valley International School', 'Badshapur Sohna Highway', 'Golf Course Rd', 'Bharat Singh fuel company', 'Basai Enclave Park', 'CANARA BANK', 'Bank Of Baroda ATM', 'The Holy Kingdom Public School', 'Shiv Mandir', 'Open gym garden', 'KFG sports club Parking', 'ESIC HOSPITAL', 'Sector 37 Police Station', 'Alfaa Health Care Hospital', 'Euro Intl School Sec-51', 'Mall Fifty One', 'K.D. Hospital', 'Gurgaon Road', "Saint Paul's School", 'Indus valley Public School', 'MDS Public School', 'Signature Super Speciality Hospital', 'Harsaru Village Bus Stop', 'Health care pharmacy', 'Jadon Pharmacy', 'JMS Crosswalk', 'Essar Petrol Pump', 'The Heritage Pride Modern School', 'SS Omnia Mall', 'Miracles Apollo Cradle / Spectra', 'Gurgaon Toll', 'Propose Metro Station', 'Rajiv Chowk', 'Lions Public School', 'M3M Cosmopolitan', 'M3M International Financial Center (IFC)', 'Holiday Inn Express Gurugram Sec 50', 'ICICI ATM', 'Sai Sports Club cricket ground', 'Silver Streak Hospital', 'Gurukul Preschool', 'HP PETROL PUMP Unnamed Rd', 'INOX Cinema', 'Nawada Cricket Accadmy', 'Arc Multi Speciality', 'Sanjeevani Hospital', 'Baba Kanala Chowk', 'Pataudi Rd', 'Dronacharya College of Engineering', 'Netaji Subhash Marg', 'Euro International School, sector- 51', 'NH 248', 'Faridabad', 'Delhi-Mumbai Expressway', 'IMT Sohna', 'Kundli Manesar Palwal Expressway', 'KR Mangalam', 'SCJ Academy', 'Taj', 'Damdama Lake', 'Ascendas OneHub Gurgaon Business Park', 'GD Goenka High School', 'GD Goenka University, Gurugram', 'Jhankar Senior Secondary School', 'Entertainland Mall', 'Aravalli Hills', 'Delhi', 'Red Roses P

In [107]:
location_df_normalized.columns.value_counts()

Bajghera Road                         1
Narayana e-Techno School - Manesar    1
SS Omnia, Sector 86                   1
Canara Bank - Nawada Fatehpur         1
ICICI Bank ATM, Sector 86             1
                                     ..
Gurugram University Kankrola          1
Candor TechSpace, Sector 48           1
IndusInd Bank ATM                     1
Cherub's Cradle                       1
Skyview Corporate Park                1
Name: count, Length: 988, dtype: int64

In [108]:
location_df[location_df['Bajghera Road']<2000]['Bajghera Road'].sort_values()

PropertyName
M3M Crown              550.0
Smartworld One DXP     800.0
Sobha City            1500.0
Name: Bajghera Road, dtype: float64

In [537]:
import pickle
with open('location_df.pkl','wb') as f:
    pickle.dump(location_df,f)

In [110]:
import pickle
with open("cosine_sim1.pkl",'wb') as f:
    pickle.dump(cosine_sim1 ,f)
with open("cosine_sim2.pkl",'wb') as f:
    pickle.dump(cosine_sim2 ,f)
with open("cosine_sim3.pkl",'wb') as f:
    pickle.dump(cosine_sim3 ,f)